### ISSUE TITLE
[Bug]: Loot Crate can't be opened

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#102]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.90

### Describe your issue

Hat crates from the coin shop can't be opened

### Additional Information

![image](https://user-images.githubusercontent.com/79115447/208251752-f76ce38e-6b6a-4dff-b493-34bf05be5f52.png)

**Comment by dr3ams** [comment]
fixed for the next update
