### ISSUE TITLE
[Bug]: Crashing due to Corail Tombstone

### ISSUE THREAD

**Issue by Litaeus** [dr3ams/Roguelike-Adventures-and-Dungeons-2#103]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

V0.9

### Describe your issue

Used Corail Tombstone scroll on friend and he crashed then I crashed then he crashed for whole duration of potion effect which lasted 10 minutes of in game time while we were in game.

### Steps to reproduce the issue

Use a scroll on friend and crash them with yourself

### Additional Information

[crash-2022-12-17_17.29.24-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10252977/crash-2022-12-17_17.29.24-client.txt)
Also we are playing on Bisect Hosting with a 6GB server, server did not crash the crashes were client side.

**Comment by DoctorMage** [comment]
can you send the latest.logs plese

**Comment by VanyaBaou** [comment]
Crash is an issue with Carrots Lib (org.jwaresoftware.mcmods.lib)
Both mods closed source
Will need to do tests with just the two mods installed and report to the dev(s)

**Comment by Corail31** [comment]
https://github.com/Corail31/tombstone_lite/issues/131
