### ISSUE TITLE
Death's odium

### ISSUE THREAD

**Issue by honeybadgerkc3I** [dr3ams/Roguelike-Adventures-and-Dungeons-2#104]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

.9

### Describe your issue

Death's odium reversals don't exist. If you lose the armor with death's odium, there is no way of getting that health back (excluding extra hearts from something else which also seem to not work). All I can find to get the health back is to wear the armor, which broke, use /unique_enchantments deleteCurse, or Death's odium cookie all of which don't exist. Found that someone posted on unique enchantments issues about this but hasn't updated if the intended options have worked as it was posted in the past three days so I'm unsure if this is on the modpack's end or the mod, though reading other updates on RAD (haven't played that one) it seems the solutions should exist. Also wearing a new pair of armor with the enchantment doesn't restore health

### Steps to reproduce the issue

1. Wear something with Death's odium 2. Die a bunch 3. Lose the armor (mine broke) 4. Try to use "/unique_enchantments deleteCurse" or Death's odium cookie 5. See that they aren't there.

### Additional Information

![2022-12-18_04 52 36](https://user-images.githubusercontent.com/120918165/208294433-dd576c19-3e50-4fcf-8fbb-829721152881.png)
![2022-12-18_04 53 15](https://user-images.githubusercontent.com/120918165/208294434-1bdede55-629e-463a-a3d7-4db30b1a2df1.png)

**Comment by DoctorMage** [comment]
enchant a cookie with the curse deaths odium and it will remove the curseseffects

**Comment by DoctorMage** [comment]
either have the cookie in a stack or something with death's odium in your off hand then eat it

https://streamable.com/ryxwjr
