### ISSUE TITLE
[Bug]: Simple Storage Network Remote collector crash

### ISSUE THREAD

**Issue by ILove07Gold** [dr3ams/Roguelike-Adventures-and-Dungeons-2#108]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

0.9 (latest)

### Describe your issue

crash after crafting the item collector from simple storage network. i recommend you disable this item for players/. In the past ive used this item on other modpacks and its always crashed/caused item disappearing issues. I don't think the mod creator fixed the issues with it. 

### Additional Information

[crash-2022-12-22_12.34.45-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10290218/crash-2022-12-22_12.34.45-client.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10290219/latest.log)

**Comment by ILove07Gold** [comment]
i can't even open up my game anymore. I'm removing simple storage network mod from my game.

**Comment by VanyaBaou** [comment]
Known issue, posted to dev's github https://github.com/Lothrazar/Storage-Network/issues/471

**Comment by ILove07Gold** [comment]
> 

thoughts on removing the mod completely? I understand it is a drastic action, but ive had problems with this mod a whole year ago and to see it still not fixed does not give me confidence in the mod. I know there is an entire section dedicated towards simple storage in the quest section, but i really dont feel like its stable enough.

**Comment by Throwawayaccount25** [comment]
download NBT explorer from here: https://github.com/jaquadro/NBTExplorer and remove it from your inventory, its not perfect but you will at least be able to play (you need to remove it from player data (long-alfa-numberic-name.dat) file and world data file (level.dat))
