### ISSUE TITLE
Curse Ring/Crashing 

### ISSUE THREAD

**Issue by xSharkBtw** [dr3ams/Roguelike-Adventures-and-Dungeons-2#11]
Please help! Some friends and I downloaded this modpack and its fun for the most part. but at the beginning I was kind of dumb not reading anything and just put the curse ring on. is there a way to take this off with a potion/going into creative/having the server admin clear my inventory?  It makes the mod honestly so much harder and not fun rn because everything is 1 shoting me and killing me over and over and I can't kill anything because of it. 

Another thing Me and My friend have 16gb of ram but keep getting this error code if we close minecraft and then try to load it back up. -805306369 the only fix we found to this so far is uninstalling reinstalling everytime we wanna play again but this is really annoying to do every single time to play. Please help asap, Thanks!

**Comment by dr3ams** [comment]
> this error code if we close minecraft and then try to load it back up. -805306369 the only fix we found to this so far is uninstalling reinstalling everytime we wanna play again but this is really annoying to do every single time to play.

Can't help you without logs. Locate your instance folder and upload **latest.log** from logs folder somewhere (Pastebin.com, gist.github.com)

**Comment by dr3ams** [comment]
Rind of the Seven Curses will be removed from starting invetory in next update. Will be added as quest reward.
