### ISSUE TITLE
[Suggestion]: Need a pipe mod

### ISSUE THREAD

**Issue by logalog42** [dr3ams/Roguelike-Adventures-and-Dungeons-2#110]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Sorry I haven't done a lot of looking but I've been playing around with bees recently and it highlighted the need for a lite technology mod. We need pipes/cables for routeing things (mainly honey) as well as a few more power options because honey generator is just not enough. I'll look into what would be a good fit and make a suggestion.

**Comment by VanyaBaou** [comment]
This is not a tech modpack
Do not expect any tech mods to be added

**Comment by logalog42** [comment]
No I'm not talking about a full on tech mod. I was thinking more like [pipes](https://www.curseforge.com/minecraft/mc-mods/pipez) I just want a way to move my honey around and maybe the little bit of power from the honey generator so I can spread it out. Because right now things are just clunky.

**Comment by VanyaBaou** [comment]
Use Rats
Use SSN
Adding Pipes unlikely

**Comment by logalog42** [comment]
Alright thanks for the info!
