### ISSUE TITLE
[Bug]: Gold Coin Reward Dupe

### ISSUE THREAD

**Issue by GodLikeInfernal** [dr3ams/Roguelike-Adventures-and-Dungeons-2#111]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

0.95

### Describe your issue

Gold Coin --> Dungeon's Artifacts Crate unlimited items. Doesn't use the gold coin but lets you repeatedly use the crate.
Same with the weapons crate.

### Steps to reproduce the issue

1. obtain gold coin
2. go to coin shop and use the gold weapon crate or artifact crate
3. profit

### Additional Information

![2022-12-23_19 11 15](https://user-images.githubusercontent.com/25142071/209417325-2ade403f-0a96-4d9b-ab23-eb0338469d55.png)

**Comment by dr3ams** [comment]
fixed in 0.95
