### ISSUE TITLE
[Suggestion]:  Easier Villager/mobs moving

### ISSUE THREAD

**Issue by logalog42** [dr3ams/Roguelike-Adventures-and-Dungeons-2#112]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I'm sorry I don't know what this falls under. But is there a way we could have to move villagers easier? I'm not sure if there is an item that was removed or if none of the mods have something. But a simple [pick-up](https://www.curseforge.com/minecraft/mc-mods/carry-on) mod would be nice. I'm no expert on villagers but I run into a bunch as I'm out exploring and I'd like to make use of trading. If it was designed this way then I'll close it but I thought I would ask.

**Comment by VanyaBaou** [comment]
Warp Scroll + Blink from Ars Nouveau
Extradimensional Eye from Enigmatic Legacy

If you aren't sure if something already exists you should try searching our Discord, and if you can't find the answer just ask.
