### ISSUE TITLE
[Bug]: Trying to add enchanted book to an artifact crashes the game

### ISSUE THREAD

**Issue by Chifilly** [dr3ams/Roguelike-Adventures-and-Dungeons-2#114]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.95a

### Describe your issue

Trying to add an enchantment with an enchanted book in an anvil to an artifact crashes the game.

### Steps to reproduce the issue

1. Put an artifact in an anvil (tested with both vanilla and modded anvils)
2. Add the enchanted book (tested with Mending and Tombstone Soulbound) to the anvil (both click and move and shift click tested)
3. The game crashes

### Additional Information

* [crash log](https://gist.github.com/Chifilly/e35a7ae80de57ba55231a224abc03cd4)

**Comment by VanyaBaou** [comment]
Dev of Dungeons Gears is aware of the issue and stated a fix should be coming in a future update
For now don't enchant it
