### ISSUE TITLE
[Bug]: Unobtainable Relic from Crates

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#115]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

Baubles that are unobtainable in normal gameplay (seemly disabled for unknown reasons) were obtained through the artifact crates.

### Steps to reproduce the issue

buy artifact crates with monster coin

### Additional Information

![image](https://user-images.githubusercontent.com/79115447/209446493-350cfbe8-7323-426c-908b-6fed52100023.png)

**Comment by RecyclingTiger** [comment]
Going to close this as completed as the water candle was removed during the crate rework back in 1.2
