### ISSUE TITLE
[Suggestion]: Atum and Eye of the Dragons

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#116]
### General Info

- [X] I would like to propose new mod
- [X] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Problem One: Atum serves absolutely zero purposes in this pack and it's just a dimension with sand, enemies, and pyramids.
Also, it's boring and meaningless to have players collect every single item in the mod.
Solution: Buff Atum armor/weapons to make it more attractive. Rework the quest and leave only the important items like the Godforge and a brief tutorial for the pyramids.

Problem Two: Eye of the dragons is a very bad mod. The eyes can lead to dead dragons (totally bs) and the distance is so short that I can see the dragon clearly when I can finally use the eye. The worst part is that the mod is not configurable at all.
Solution: Remove the mod and maybe add the Scannable mod with recipe tweaks

**Comment by VanyaBaou** [comment]
Scannable was in the pack during alpha and was removed due it not fitting into the theme(s).

**Comment by VanyaBaou** [comment]
Atum also was given PMMO XP boosts on like EVERY item
Current state doesnt seem to warrant any buffs to be more "attractive"

Adding quest info is a good idea though
