### ISSUE TITLE
[Bug]: XP Boost Enchantments

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#117]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

XP boost enchants like insight, boosted gives players extra experience **based on their current XP level** and players can snowball the XP.

### Steps to reproduce the issue

1. Get high XP level
2. Use armor that has insight, boosted, sage's blessing enchants
3. Do anything that gives you XP (killing a dragon, bosses, etc)

### Additional Information

![image](https://user-images.githubusercontent.com/79115447/209463623-8e06f4c7-85de-4f98-b684-fdb9e90e9828.png)
![image](https://user-images.githubusercontent.com/79115447/209463824-9e75f658-3c14-4b80-9c7e-cf29387dc1fe.png)
 
![image](https://user-images.githubusercontent.com/79115447/209463951-6790abf2-cd7e-4162-86a4-509f4f834a4b.png)

![image](https://user-images.githubusercontent.com/79115447/209463887-300ff377-3dc5-425e-ab69-491455791854.png)
![image](https://user-images.githubusercontent.com/79115447/209463892-88b2c80b-9ec9-4d42-a9e6-45c99a46db12.png)
![image](https://user-images.githubusercontent.com/79115447/209463894-bbd47be3-cfdc-4b2f-8763-38d5ac715adc.png)
![image](https://user-images.githubusercontent.com/79115447/209463902-27839e6e-f6c1-470d-b7f4-6610000e7818.png)
![image](https://user-images.githubusercontent.com/79115447/209463926-69e50d55-3777-4e16-8a43-29c256279bd8.png)

**Comment by VanyaBaou** [comment]
Has to do with Sage's Blessing's transcended effect
Mod dev (Xaikii) is aware of the issue

**Comment by VanyaBaou** [comment]
should be fixed in latest https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/a7d67939495495ebea60ca96160e7050d58c1ff6
