### ISSUE TITLE
[Suggestion]: All Bosses Should be Spawned as Champions upon Entering Expert/Master mode

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#118]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The Exper/Master mode is a good approach to keep rookies away from impossible strong mobs while making the game more challenging for people who know what they are doing in the mid-end game.
But most of the Expert/Master changes feel pretty bland later on and there are bosses that stay with 50 to 200hp after Expert/Master mode (especially bosses in Mowzie's mobs) while the other mobs like stray and zombies have 700 to even 1024 (I think this is the cap) hp and can one hit a player in netherite armor which is quite strong compared to those "bosses."

So I think all bosses should spawn as 3-star+ champions after Expert/Master mode. This will make the end game significantly harder, and bring challenges to the progression.

**Comment by RecyclingTiger** [comment]
Added in 1.9
