### ISSUE TITLE
[Suggestion]: Blacklist Mobs from Summoning by Praying

### ISSUE THREAD

**Issue by 12-4-25** [dr3ams/Roguelike-Adventures-and-Dungeons-2#119]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Players can sometimes summon familiars by praying to a decorative grave with the Ankh of Pray.
Bosses like the Nether Keeper from Stalwart Dungeons and the dragons from Ice and Fire should be blacklisted from the Familiar Receptacle and praying.
![2022-12-26_08 31 14](https://user-images.githubusercontent.com/79115447/209486637-a19bee94-f90c-4345-a81a-4bb41ee066be.png)
![2022-12-26_08 31 30](https://user-images.githubusercontent.com/79115447/209486644-93ffcc7e-4fcc-4e92-9025-6ff2349328e6.png)
![2022-12-26_08 41 16](https://user-images.githubusercontent.com/79115447/209486658-0ade8649-c9ca-4778-aa42-c119549f909c.png)

**Comment by DoctorMage** [comment]
moved to #260
