### ISSUE TITLE
[Bug]: Buttons missing from upper left corner of inventory

### ISSUE THREAD

**Issue by v1nsai** [dr3ams/Roguelike-Adventures-and-Dungeons-2#120]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.95a

### Describe your issue

When starting a new RAD2 instance with no additional mods, the buttons for switching gamemode and time and the others are missing from the top left of the screen.

I've looked through config files for anything relevant, and I've tried RAD2 0.95 and 0.95a.  From what I can tell this is part of FTB Library and should "just work" and there doesn't seem to be any config for it.

Attached is a screenshot and my `latest.log` from the logs folder.  I couldn't find FTB Library complaining about anything and nothing is actually crashing, not sure what else to look for.

### Steps to reproduce the issue

* Create new RAD2 instance
* Create new world
* Enter world
* No buttons in top left

### Additional Information

[latest.log from RAD2 instance folder](https://gist.github.com/v1nsai/2eb22ae3aa82ff2074c8c334bca0d5cd)

[Screenshot of my inventory on login](https://imgur.com/a/ijDIBir)

**Comment by VanyaBaou** [comment]
**config\sidebar_buttons.json** should be the config
They're set to false, so even with op/cheats you don't see them
