### ISSUE TITLE
[Suggestion]: Undergarden Quests Change

### ISSUE THREAD

**Issue by CryoMaelstrom** [dr3ams/Roguelike-Adventures-and-Dungeons-2#124]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Some of the quests for Undergarden ore require the ore blocks. Unfortunately, some ores do not drop the block when mined, and instead drop nuggets, or the raw materials, making the quests impossible to complete without a silk touch pickaxe. The ores that don't drop their block form are Cloggorum, Regalium, and Utherium. Perhaps instead of needing the ore block in your inventory, u could make it complete upon mining the block? Or at least make it completeable without silk touch. Thank you!

**Comment by VanyaBaou** [comment]
should all be fixed
