### ISSUE TITLE
[Suggestion]: Lead Ingot Quest Change

### ISSUE THREAD

**Issue by CryoMaelstrom** [dr3ams/Roguelike-Adventures-and-Dungeons-2#125]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The lead ingot quest in World Exploration requires a specific Lead Ingot to be completed. I believe there are two Lead Ingots in the mod, and it would be nice for it to accept both types.

**Comment by VanyaBaou** [comment]
Please update your modpack, that is already fixed in the latest versions.
