### ISSUE TITLE
[Suggestion]: Greek Fantasy Quest/Bronze Block

### ISSUE THREAD

**Issue by CryoMaelstrom** [dr3ams/Roguelike-Adventures-and-Dungeons-2#127]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Greek Fantasy Quests say to use Bronze Blocks to summon bosses like the Bronze Bull and Talos. No Bronze Blocks exist in the pack, and Ichor Infused Blocks are used instead.

**Comment by VanyaBaou** [comment]
fixed
