### ISSUE TITLE
[Bug]: getting pmmo skills reseted

### ISSUE THREAD

**Issue by GustavoTDomingues** [dr3ams/Roguelike-Adventures-and-Dungeons-2#128]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

0.95a

### Describe your issue

a player on my server got killed and all his skills got resected
is there any item or specific behavior that can cause that to happen?
 

### Additional Information

![image](https://user-images.githubusercontent.com/94856330/210276531-75712be7-5ad4-4f0a-9436-10c6ba783535.png)
the player had this artefact with it

**Comment by DoctorMage** [comment]
what server provider are you using and is it in online mode?

**Comment by GustavoTDomingues** [comment]
im not using a server provider, i did my own dedicated machine and yes it is in online mode

**Comment by DoctorMage** [comment]
specs of the machine your hosting the server on
windows or linux
and did you make any config changes/ mod additions as well as how are you starting the server

**Comment by GustavoTDomingues** [comment]
its linux debian with 32gb of ram 
i did make some changes cuz of some bugs in your server pack that keept crashing the server
i higly doubt that's one of the problems cuz i just upgraded some of the mods u had on it

**Comment by DoctorMage** [comment]
what changes
what mods did you update

**Comment by GustavoTDomingues** [comment]
dungeons-gear to dungeons_gear-1.16.5-3.2.4.jar
dungeons-libraries to dungeons_libraries-1.16.5-1.0.3.jar
Ice_and_Fire to iceandfire-2.1.11-1.16.5-SNAPSHOT+build.2022-10-07.jar

**Comment by DoctorMage** [comment]
do you have any idea on how the player died and also how to use an nbteditor

**Comment by GustavoTDomingues** [comment]
i checked the logs and it just said that the player died to a zombie
ps. there was something on the logs talking about "soulcrystal" do by any chance know what it is and if it may have any relation with that happening?

i have no ideia what your referring to as nbteditor

**Comment by DoctorMage** [comment]
can you send the log file of it please also most likely hard reset so you will have to manually add back any lost pmmo levels

/pmmo admin playername skillname level number

**Comment by GustavoTDomingues** [comment]
so basically it might be a bug its not something that its supposed to happen?

**Comment by DoctorMage** [comment]
Yes its a bug only seen it happen twice second time is with you

in the server go to \world\data
grab this file and send it here pmmo.dat

**Comment by GustavoTDomingues** [comment]
oh ok that makes so much more sense

heres the file
[pmmo.zip](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10341350/pmmo.zip)

**Comment by DoctorMage** [comment]
whats the name of the player that had there skills reset

**Comment by GustavoTDomingues** [comment]
WeiDragzerus i think

**Comment by DoctorMage** [comment]
apologies for late respone but searching that player name has no results need exact mc player name 

Regarding the first time this occured the server was being ran in offline mode and the person who it happened to was playing on a cracked launcher, this is why I asked that specifically running a server in offline mode and having cracked players on can have issues with certain game data being saved
