### ISSUE TITLE
[Bug]: Can't cast a spell

### ISSUE THREAD

**Issue by BlankDolll** [dr3ams/Roguelike-Adventures-and-Dungeons-2#130]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PCL

### Modpack version

0.95a

### Describe your issue

There is this magic spell that needs magic level 5 to cast.I'm level 20 but still couldn't cast it.
![image](https://user-images.githubusercontent.com/122148560/211141370-76141411-25e3-4cf9-9e61-7af227bb6c42.png)

### Additional Information

![image](https://user-images.githubusercontent.com/122148560/211141364-5d73b684-c6cb-465f-8385-9c96908fd01c.png)
![image](https://user-images.githubusercontent.com/122148560/211141383-7e96c861-4afd-4258-97e7-e715f1c9de6f.png)

**Comment by DoctorMage** [comment]
what's pcl dont shorten launcher names?

**Comment by DoctorMage** [comment]
plain craft launcher
unsupported launcher 

please use 
Curseforge, Multimc, Atlauncher, Gdlauncher to play this modpack
