### ISSUE TITLE
[Bug]: Help i don't know what's happening :'(

### ISSUE THREAD

**Issue by DemangelM** [dr3ams/Roguelike-Adventures-and-Dungeons-2#132]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

0.95a

### Describe your issue

Whenever I try to launch the modpack, it loads for 10 seconds, then instantly crashes ! Help :'(

Here's my logs :

ATLauncher :

[atlauncher.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10373108/atlauncher.log)

RAD 2 :

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10373111/latest.log)

### Additional Information

ATLauncher :

[atlauncher.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10373119/atlauncher.log)

RAD 2 :

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10373116/latest.log)

**Comment by Honeth** [comment]
#131 This person had this issue on CurseForge, seems like changing the fml version from 36.2.33 to 36.2.34. Should fix your problem. unsure if ATLauncher has a simple option where you can change which forge mod loader version it uses.

**Comment by DemangelM** [comment]
It didn't work on my old instance, but it seems to have worked by creating a new instance and changing the forge version (which is possible simply on ATLauncher). I'll update if it re-crashes ! Thanks :)
