### ISSUE TITLE
[Bug]: Modpack freezes when loading world

### ISSUE THREAD

**Issue by DemangelM** [dr3ams/Roguelike-Adventures-and-Dungeons-2#135]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

0.95a

### Describe your issue

When I try to load my singleplayer world, it freezes and I have to Alt F4 to exit and it exits with this error in the console : [Server thread/ERROR] Exception stopping the server....

### Additional Information

[atlauncher.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10382467/atlauncher.log)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10382473/latest.log)
[crash-2023-01-10_12.57.04-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10382475/crash-2023-01-10_12.57.04-server.txt)

**Comment by DoctorMage** [comment]
You need to make a new world and copy over the folder called server config into your old world something corrupted some mod configs

**Comment by DemangelM** [comment]
Ok thx ! :)
