### ISSUE TITLE
[Bug]: Crash when accessing FTB Shop

### ISSUE THREAD

**Issue by GallX01** [dr3ams/Roguelike-Adventures-and-Dungeons-2#138]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

When i will access to the shop in multiplayer the game instantly crashes and this happened just in multiplayer

### Steps to reproduce the issue

1.Go to the quest menu
2.Click or just pass the cursor on the shop icon
3.My game crashes

### Additional Information

[crash-2023-01-13_12.47.51-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10411247/crash-2023-01-13_12.47.51-client.txt)

**Comment by VanyaBaou** [comment]
Is the server in offline or online mode?

**Comment by GallX01** [comment]
Online

**Comment by DoctorMage** [comment]
next time it happens can you grab the debug and latest.logs from teh server

**Comment by Rifonn** [comment]
I have same problem but I use offline server.  I am using the latest version of the modpack.
[debug.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10429209/debug.log)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10429212/latest.log)

**Comment by DoctorMage** [comment]
> I have same problem but I use offline server. I am using the latest version of the modpack. [debug.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10429209/debug.log) [latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10429212/latest.log)

Do not run the server in offline mode otherwise ftb shop will not work correctly 
and end up crashing

Their are also other issues with offline mode from mods not saving info correctly

**Comment by GallX01** [comment]
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10434080/latest.log)
[debug.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10434081/debug.log)

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/212879352-aff99456-e6c6-42c8-90fe-8ec6a2edf745.png)


> [latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10434080/latest.log) [debug.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10434081/debug.log)

**READ ABOVE** I literally said and stated the reason why servers should not be run in offline mode
run the server in online
