### ISSUE TITLE
[Bug]: Famine's Odium curse consumes Lunchbox.

### ISSUE THREAD

**Issue by kalutro** [dr3ams/Roguelike-Adventures-and-Dungeons-2#14]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.2

### Describe your issue

This may be intended behavior, though I hope not. I was using an Iron Pickaxe with the curse Famine's Odium II, which will consume one random food from my inventory. With any actual food item, one item gets eaten. With the Lunchbox, it will consume the actual Lunchbox, no matter how much food is inside. I assume this happens because the Lunchbox is considered a food item.

I'm not sure if the Lunchboxes can be blacklisted.

### Steps to reproduce the issue

Have a Lunchbox with food inside. Mine was Golden with multiple stacks of food.
Have an item with Famine's Odium. Mine was an Iron Pickaxe.
Wait about 2 minutes.

### Additional Information

n/a

**Comment by VanyaBaou** [comment]
Unique Enchantments dev is aware of this issue and we're awaiting an update from them

**Comment by DoctorMage** [comment]
fixed in 0.9
