### ISSUE TITLE
Crashing upon loading the Modpack. Crash says it's a rendering overlay as Description

### ISSUE THREAD

**Issue by blackbladiz** [dr3ams/Roguelike-Adventures-and-Dungeons-2#142]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

While the game is doing the Memory Heap thing it will crash after some time. Where it says Atlas Stitching: minecraft:textures/atlas/beds.png. This usually is when it takes a while to do the Memory Heap.
[crash-2023-01-16_02.15.24-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10423852/crash-2023-01-16_02.15.24-client.txt)

### Steps to reproduce the issue

1. Launch Curseforge
2. Click play on Modpack
3. Click Play with the modpack and forge selected
4. Wait for the Heap to finish
5. Crash and get same error every time.

### Additional Information

Out of the countless times I've tried this I only managed to get to the title screen once and load into a single player game.

**Comment by DoctorMage** [comment]
pc specs
cpu model name
total ram

**Comment by blackbladiz** [comment]
> pc specs cpu model name total ram

(Copied from  Settings)

Processor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
Installed RAM	64.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Graphics card is a MSI Geforce RTX 3060 12gb

Anything else needed?

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/212772609-3f108e18-e4c5-4ee6-98de-bdbba452085d.png)
if you havent change ram allocation 8192 mb

**Comment by blackbladiz** [comment]
> ![image](https://user-images.githubusercontent.com/85318453/212772609-3f108e18-e4c5-4ee6-98de-bdbba452085d.png) if you havent change ram allocation 8192 mb

Seen this in another post and had already done that,

**Comment by DoctorMage** [comment]
go to the folder were you have curseforge store modpacks
or right click modpack icon click open folder then at the top click instances
then delete the modpack

and try a clean install
