### ISSUE TITLE
[Bug]: no nether fortress

### ISSUE THREAD

**Issue by butterbal1** [dr3ams/Roguelike-Adventures-and-Dungeons-2#144]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

1.16.5

### Describe your issue

i have searched the nether for an hour in creative and teleporting everywhere and have not found a single nether fortress. i have typed the command in a lot and it pops up no structure has been found nearby

### Additional Information

1

**Comment by DoctorMage** [comment]
mod that reworks them do 
/locate bygonenether:fortress
