### ISSUE TITLE
[Bug]: Hang on loading world

### ISSUE THREAD

**Issue by xzh3r** [dr3ams/Roguelike-Adventures-and-Dungeons-2#145]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism Launcher

### Modpack version

0.95a

### Describe your issue

A bug happened!
The game hangs on "Joining game.." when trying to load my newly generated world. The world generates perfectly fine, I just can't join it because of it hanging.

### Steps to reproduce the issue

1. Click Singleplayer
2. Create world with the Realistic worldtype
3. Wait
4. Hangs

### Additional Information

https://mclo.gs/CboZbv1
Log file

Specs:
Intel Core i7-8700K
NVIDIA GeForce GTX 1060 3GB
16GB 2666 MHZ RAM

**Comment by DoctorMage** [comment]
Are you using prism "portable" version or exe

**Comment by DoctorMage** [comment]
Also how much ram allocated to the modpack

**Comment by xzh3r** [comment]
I'm using the exe prism launcher

I have 3456 MiB allocated to the pack, I can't use much because my pc idles at like 50% memory usage with firefox, discord, steam, lightshot, and logitech g hub open

**Comment by DoctorMage** [comment]
modpack needs around 6gb or ram minium 8gb to be safe
