### ISSUE TITLE
better end armours have no requirements to wear

### ISSUE THREAD

**Issue by dr3ams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#15]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.2

### Describe your issue

A bug happened!

### Steps to reproduce the issue

-

### Additional Information

-

**Comment by VanyaBaou** [comment]
this was a false alarm for the user experiencing it, they hit the Keybind to Toggle Tooltips on accident

message [here](https://discord.com/channels/512339624627011586/1009037724600250399/1012443694814732340)
> I guess it toggled off at some point
