### ISSUE TITLE
[Bug]: All my Project MMO skills have reset

### ISSUE THREAD

**Issue by Gav1nL33** [dr3ams/Roguelike-Adventures-and-Dungeons-2#151]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.95a

### Describe your issue

Upon re entering my world, I noticed certain armour, weapons and artifacts were suddenly unable to be worn or used so I checked my skills and they have all reset to nothing, there is no left hand bar and no skills within the Project MMO skills tab, I have reloaded the world and it is still the same.

### Additional Information

My Skills tab:
![image](https://user-images.githubusercontent.com/73658194/213763003-435ab4ff-4151-48a8-9320-746ec39c4b7f.png)
Proof that I have done quests that grant experience to skills:
![image](https://user-images.githubusercontent.com/73658194/213763373-9a124481-c397-4af6-8e57-e38cd53f4bee.png)
Latest log:
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10468635/latest.log)

**Comment by Gav1nL33** [comment]
Also just to not, this is a singleplayer world

**Comment by DoctorMage** [comment]
Did anything happen to your pc while playing the modpack or anything happen to your pc like a sudden power cut

**Comment by Gav1nL33** [comment]
I reset my computer but I left the game before I did that

**Comment by DoctorMage** [comment]
reset your computer how?

**Comment by Gav1nL33** [comment]
Going to power options and clicking restart

**Comment by DoctorMage** [comment]
and minecraft was fully closed right not running in the background?

**Comment by Gav1nL33** [comment]
The world was but I dont believe minecraft itself was

**Comment by DoctorMage** [comment]
apologies for late response but for now cheat back your levels /pmmo admin playername set skillname level  (level is the level you wish for skill to be) no clue on what the cause could be

**Comment by Gav1nL33** [comment]
Thank you!

**Comment by DoctorMage** [comment]
moved to #232
