### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Thebane56** [dr3ams/Roguelike-Adventures-and-Dungeons-2#152]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

.95a

### Describe your issue

I crash sometimes. I'm not sure what's causing it.  It's happening often. The only change to the mod pack was using the newer Dungeon gear and Dungeon library mod to fix an earlier crash.

### Steps to reproduce the issue

It often happens when I'm being attacked by a mob but the mobs have varied and the latest one is a vanilla cave spider.

### Additional Information

[crash-2023-01-20_20.39.35-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10471512/crash-2023-01-20_20.39.35-server.txt)
[crash-2023-01-20_20.32.06-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10471513/crash-2023-01-20_20.32.06-server.txt)
[crash-2023-01-20_19.49.26-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10471514/crash-2023-01-20_19.49.26-server.txt)

**Comment by DoctorMage** [comment]
Dont use any armour from ars arsenal
