### ISSUE TITLE
[CRASH:] Server crashing after first person join server

### ISSUE THREAD

**Issue by puddovsky** [dr3ams/Roguelike-Adventures-and-Dungeons-2#153]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Crystal Launcher

### Modpack version

0.95a

### Describe your issue

Hello, I have such a problem, I uploaded the package, everything theoretically should be fine, but if anyone joins the server, it immediately crashes and turns off 

### Additional Information

[crash-log.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10475363/crash-log.txt)

**Comment by DoctorMage** [comment]
crystal launcher is unsupported
