### ISSUE TITLE
[Bug]: Ice and Fire "IStuckHandlerEntity" Crash

### ISSUE THREAD

**Issue by Pacionist** [dr3ams/Roguelike-Adventures-and-Dungeons-2#154]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.9.5a

### Describe your issue

I think it's this issue - https://github.com/AlexModGuy/Ice_and_Fire/issues/4606
Maybe any pathfind mods need to be configured?

### Steps to reproduce the issue

1. Just play a game
2. Meet a dragon even if you don't see him and crash.

### Additional Information

This is my last log file.
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10494131/latest.log)
And this is my crash report file.
[crash-2023-01-25_00.09.28-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10494141/crash-2023-01-25_00.09.28-server.txt)

**Comment by Pacionist** [comment]
I modified a modpack and downloaded latest snapshot of Ice and Fire mod, then killed a dragon and my game doesn't crash, so it works fine.
This mod needs to be updated in modpack

**Comment by DoctorMage** [comment]
Until ice and fire puts that version on curseforge users will manually have to add it to the modpack

**Comment by VanyaBaou** [comment]
For anyone that doesn't understand how to get the latest snapshot, go [here](https://github.com/AlexModGuy/Ice_and_Fire/releases)
And please make sure you are downloading the one for 1.16.5

**Comment by VanyaBaou** [comment]
Ice and Fire has updated on CurseForge, so instead of getting the snapshot from their github, update the mod itself.

**Comment by DoctorMage** [comment]
fixed in 1.2 with ice and fire update
