### ISSUE TITLE
[Bug]: Crash when shooting villagers and Skeleton horses with bow or crossbow

### ISSUE THREAD

**Issue by colerosemergy** [dr3ams/Roguelike-Adventures-and-Dungeons-2#156]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

Whenever I shoot villagers, or skeletons riding skeleton horses with a bow or crossbow the server crashes.

(Please note, I have added two mods, Ars omega and Ars elemental, but this crash was happening before I added them as well.)

### Steps to reproduce the issue

1. Find Villager or Skeleton on skeleton horse
2. Shoot with bow or crossbow
3. Server crashes.

### Additional Information

[crash-2023-01-25_07.44.50-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10501072/crash-2023-01-25_07.44.50-server.txt)

**Comment by DoctorMage** [comment]
do you have naughty effect from christmas spirit mod when doing this?

**Comment by ToolB0xx** [comment]
I have the same issue, to add to it, I also crash when shooting arrows at wolves, villagers, or named npcs. This does not happen when I shoot a regular vanilla unenchanted bow. But an enchanted bow shooting at any of these entities crashes the server instantly.

**Comment by DoctorMage** [comment]
what enchants does your bow have

**Comment by colerosemergy** [comment]
Sorry I haven't been responding to this. I believe the naughty effect may be the issue since I also seem to crash when killing the wolf summons of the Ars wolf things. When I have time I am going to try some testing without the mod and see if that fixes the issue.

**Comment by DoctorMage** [comment]
cause is christmas spirit remove the mod or drink milk to get rid of naughty effect
