### ISSUE TITLE
Twilight forest Portal creating 3 at once 

### ISSUE THREAD

**Issue by Thunderrock424242** [dr3ams/Roguelike-Adventures-and-Dungeons-2#157]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge 

### Modpack version

.95a

### Describe your issue

So I made a portal and I went through. And walked around a bit went back and it made another portal 500 blocks away. Idk if there are report logs for this type of issue.

### Steps to reproduce the issue

1. Make a twilight forest portal 2. Go through it 3. Go through it again 

### Additional Information

I don’t know if there are any logs for this or how to get it.

**Comment by VanyaBaou** [comment]
sounds like an issue more on twilight forest's end
which means we cant expect any fix
if you are on multiplayer (you checked that it happens in multi-player as well) it probably has something to do with pre-existing ones from other players, like normal nether portals linking to existing ones
