### ISSUE TITLE
Crash when Right Clicking mobs

### ISSUE THREAD

**Issue by Pergatory666** [dr3ams/Roguelike-Adventures-and-Dungeons-2#159]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

.96

### Describe your issue

Multiplayer Server crashes whenever we right click a person named mob. The goblin trader and villagers worked fine, but the people crash us out. 

### Additional Information

**Please send the crash report file next time

**Comment by DoctorMage** [comment]
update the modpack to 0.96a
