### ISSUE TITLE
[Bug]: Hitting a reflective champion with an axe Enchanted with Focus Impact and Frost Aspect clears your inventory

### ISSUE THREAD

**Issue by RecyclingTiger** [dr3ams/Roguelike-Adventures-and-Dungeons-2#16]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.2 beta

### Describe your issue

When hitting a reflective champion with an axe with Focus Impact 3 or higher and Frost Aspect 2 or higher at least twice, you enter a weird death state where you are still alive but not. Clicking respawn clears your inventory including tombstone soulbound ones but not curios, arcs, or other modded inventories. This happened twice on a server, and after the second time of an admin having to backup my inventory I went ahead and investigated on a singleplayer world.  This is how I discovered these enchantments were causing the bug.

### Steps to reproduce the issue

1. Get any axe (tested with stone axe, wooden axe & axe of a thousand metals)
2. Enchant it with at least Focus Impact III and Frost Aspect II
3. find or summon a mob the "reflective" champion trait (use _/champions summon zombie 1 reflective_) to spawn one
4. in survival mode, hit the reflective mob at least twice. You will notice you are getting the freezing effect.
5. if done correctly, game says you died but no grave or death message appears
6. clicking respawn clears your inventory but keeps curios and other items

### Additional Information

![2022-08-26_13 03 00](https://user-images.githubusercontent.com/89662661/186982619-917e01bd-f266-4a13-bdeb-3a132c1e9466.png)

**Comment by VanyaBaou** [comment]
Issue fixed with Reflective changes
