### ISSUE TITLE
[Bug]: Game freezes at "Joining world.." upon loading existing world

### ISSUE THREAD

**Issue by NickTheRipperEX** [dr3ams/Roguelike-Adventures-and-Dungeons-2#160]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.96a

### Describe your issue

Decided to finally make the switch from RAD to RAD2 last week, and I've been consistently having the same issue each time I start it. Downloaded the latest version of the pack, and had a blast playing in it for a few hours. I didn't go into any other dimensions, I focused on getting a base of operations made. Started it up the next day and it wouldn't load into my world at all, got stuck on "Joining world..." and the logs showed it was stuck on saving dimensions, none of which I had visited. I left it for over 30 minutes at one point hoping it would suddenly load to no luck. Specifically, it will freeze on "Saving Chunks for level" for one of the modded dimensions in the log.

I went through and, one-by-one, deleted the subfolders under "dimensions" in my world folder to get it to load further before each launch, and it would regenerate that folder and continue loading until another modded dimension caused it to freeze. It would hang randomly on one of the modded dimensions, usually going in the order of `twilightforest:twilightforest` or `twilightforest:skylight_forest` first, then `good_nights_sleep:good_dream`, `blue_skies:everdawn`, `the_bumblezone:the_bumblezone`, `feywild:market_place_dimension`, etc. Basically I had to delete nearly every modded dimension before starting the world in order to get it to load.

I had this issue starting with 0.95a, but held off a week on reporting it to see if anyone else brought up having an issue like this, which I had not seen in previous issues. Saw version 0.96 and 0.96a were released today and tried both of them with no further success.

I have been able to replicate this issue multiple times. I have created several new worlds in trying to confirm and troubleshoot the problem.

I have tried:
- Uninstalling and reinstalling the pack.
- Creating new worlds to start from scratch
- Downgrading to a previous version of the pack (currently only tried version 0.9)
- Upgrading to a newer version of the pack (from 0.95a to 0.96a)
- Allocating more RAM (up to 12GB)
- Reinstalling the latest version of Java
- Deleting the "dimensions" folder or the relevant subfolders causing the loading to freeze inside my world folder. This did allow the world to load, but isn't ideal for the future when I start exploring other dimensions.

### Steps to reproduce the issue

1. Clean install of the pack through CurseForge, select the latest version (at this time, 0.96a)
2. Launch the modpack in CurseForge with approximately 8-12GB of RAM allocated.
3. Create and play in a fresh world with default world generation settings for any amount of time without going to any other dimensions
4. Close the client.
5. Relaunch the modpack.
6. Open previous world from step 3.
7. Game hangs on "Joining world..." message and does not respond or load further. Completely unresponsive to any input other than changing window size and/or minimizing.
8. Open Task Manager and end task "Java(TM) Platform SE binary" to get game to close

### Additional Information

[latest.log on pastebin](https://pastebin.com/cMWKRHFA)

Unfortunately no crash report because doesn't generate one for this, it just freezes and doesn't ever crash or trigger the creation of a crash report when this problem occurs.

**Comment by DoctorMage** [comment]
try a different launcher like atlauncher gdlauncher or multimc/ prism mc
curseforge has been having issues

**Comment by NickTheRipperEX** [comment]
Just tried AT Launcher with a fresh install, it's still giving me the same issue.

New log: https://paste.atlauncher.com/view/7a1ed68b-5395-499d-bb6f-8eaec105ced0

**Comment by DoctorMage** [comment]
pc specs? just as a sidecheck

total ram
cpu exact model name
gpu

**Comment by NickTheRipperEX** [comment]
Sure thing! It's not entirely up to date, but this rig can run Cyberpunk with relatively no issues

**Motherboard:** Asus TUF GAMING X570-PLUS (WI-FI)
**Processor:** AMD Ryzen 9 5900X 3.7 GHz 12-Core Processor
**RAM (total):** 32 GB (**Two sets of:** Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4-3200 CL16 Memory)
**GPU:** NVIDIA GeForce GTX 1080 Ti

**Comment by DoctorMage** [comment]
just to confirm you are not making a network collector each time?

**Comment by NickTheRipperEX** [comment]
No, most of the time when I was testing this I just created a new world, then quit and tried to reload the client to see if it happened again.

**Comment by DoctorMage** [comment]
This does sometimes happen to me but upon loading into the world a second time it's fine
but since its consistant and happening on multiple launchers can you join the discord 
easier to communicate there also if you can make a zip file of one the worlds you can load into 
https://discord.gg/uajZYPQY

**Comment by NickTheRipperEX** [comment]
Just joined it.

Here's a zip file for one the of worlds that's giving me issues with loading.
[New World.zip](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10531816/New.World.zip)

**Comment by MoAccelerator** [comment]
I also have the same problem. After investigation, it seems that it is caused by ElenaiDodge2.
When entering the world, ElenaiDodge2 will obtain the list of sponsors from the patreon website. If the network cannot access patreon, there will be no response for a long time. Only after reaching the timeout period set by ElenaiDodge2 can you enter the world normally.
This error was only discovered after I used a server core with better analysis capabilities.
![image](https://user-images.githubusercontent.com/45995147/222692649-aed18878-74d2-4784-aee9-59802402f10b.png)

**Comment by DoctorMage** [comment]
reported twice on elenai git no reponses thank you for confiriming the cause
