### ISSUE TITLE
[Bug]: Still crashing when trying to interact with named player NPCs.

### ISSUE THREAD

**Issue by Snagater** [dr3ams/Roguelike-Adventures-and-Dungeons-2#164]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curse Forge

### Modpack version

0.96a

### Describe your issue

When any player tries to right click and interact with a named player NPC the server will crash. Players receive a java.lang.StackOverflowError message.

### Steps to reproduce the issue

1. Load into a world.
2. Find a named player NPC.
3. Right click them to interact.
4. Server crashes.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10524228/latest.log)
[crash-2023-01-27_16.53.38-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10524229/crash-2023-01-27_16.53.38-server.txt)

**Comment by DoctorMage** [comment]
for now remove human companions mod

**Comment by wesley-crick** [comment]
@DoctorMage The latest version of human companion should have this fix included.
https://www.curseforge.com/minecraft/mc-mods/human-companions/files

Can that mod be updated? Thanks!

**Comment by DoctorMage** [comment]
Have tested the most recent update and everything seems fine so will switch to that version 

https://www.curseforge.com/minecraft/mc-mods/human-companions/files/4381002

**Comment by VanyaBaou** [comment]
mod was updated with fix for relevant issue(s)
