### ISSUE TITLE
farming xp

### ISSUE THREAD

**Issue by mason24685** [dr3ams/Roguelike-Adventures-and-Dungeons-2#167]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Make it so when you right click a crop to harvest it, you get farming xp.

**Comment by VanyaBaou** [comment]
don't believe thats something we can implement on our end
also this is not a good idea given how the pack is designed
farming xp is given from natural growth ticks, allowing bone meal harvesting to give xp goes against the pack
