### ISSUE TITLE
vindicators are way to strong.

### ISSUE THREAD

**Issue by mason24685** [dr3ams/Roguelike-Adventures-and-Dungeons-2#168]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

self explanatory

**Comment by VanyaBaou** [comment]
not really self explanatory
they are supposed to be strong, as they are in vanilla

no idea what difficulty you are at (PMMO Power, Harder Farther, Maj's Difficulty, ImprovedMobs, etc.) or if its a champion and/or apoth boss you fought perhaps

not knowing anything about it doesn't help
please provide actual information
