### ISSUE TITLE
[Bug]: Shop in multiplayer servers boots everyone off

### ISSUE THREAD

**Issue by Rizz0Z** [dr3ams/Roguelike-Adventures-and-Dungeons-2#169]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.96a

### Describe your issue

When playing multiplayer and going to the FTB quest gui and clicking on the FTB shop icon it boots everyone off and sometimes causes the server to crash.

### Steps to reproduce the issue

1. Go into the multiplayer server
2. Open your FTB Questing menu
3. Press the shop icon

### Additional Information

[crash-2023-01-29_18.11.02-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10531609/crash-2023-01-29_18.11.02-client.txt)
[crash-2023-01-29_18.50.48-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10531610/crash-2023-01-29_18.50.48-fml.txt)
[crash-2023-01-29_20.16.10-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10531611/crash-2023-01-29_20.16.10-client.txt)

**Comment by Dzentelmenn** [comment]
> tell the server owner to stop the server go to server properties have online-mode=true not false then start the server
> 
> the server having this option as false will end up causing crashes and other issues from pmmo data not saving correctly and shop causing a crash due to not being able to save information correctly.

The question is how to transfer quests and skills acquired by a particular player if the server was running on online-mod=false?
If you can specify which files contain it
