### ISSUE TITLE
[Bug]: Server Keeps Crashing with Apotheosis mod?

### ISSUE THREAD

**Issue by xtj1234** [dr3ams/Roguelike-Adventures-and-Dungeons-2#171]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.95a

### Describe your issue

Server keeps crashing because of Apotheosis mod? Not sure what to do from here to stop crashing. It crashes every few hours.

### Steps to reproduce the issue

1. Turn on Server.
2. Friends join Server.
3. Server crashes because of 'Exception ticking world' with the same error in an hour or two.

### Additional Information

[2023-01-31-1.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10546000/2023-01-31-1.log)

[crash-2023-01-31_03.05.14-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10546002/crash-2023-01-31_03.05.14-server.txt)

**Comment by DoctorMage** [comment]
update teh modpack to 0.96a
