### ISSUE TITLE
[Bug]: Alchemy skill not present

### ISSUE THREAD

**Issue by suckinsyn** [dr3ams/Roguelike-Adventures-and-Dungeons-2#173]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

RAD2 - 0.96a [MC1.16.5]

### Describe your issue

I'm not getting any Alchemy exp, it's not present in the skill list either. Can't progress healer tree.

### Additional Information

Pack is not crashing..

**Comment by DoctorMage** [comment]
Yea something broke it in the most recent update

**Comment by DoctorMage** [comment]
https://github.com/Caltinor/Project-MMO-2.0/issues/204

**Comment by VanyaBaou** [comment]
awaiting project mmo update on CurseForge containing the fix
will be updated on our end when possible

**Comment by DoctorMage** [comment]
fixed in 1.1
