### ISSUE TITLE
[Bug]: crash report

### ISSUE THREAD

**Issue by WeirdSilver** [dr3ams/Roguelike-Adventures-and-Dungeons-2#175]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

0.96

### Describe your issue

Not entirely sure what's wrong. I had 15G allocated for the server, it's just me and one other person. We both got on and start playing but it crashes maybe 5 minutes later and says I have an overload issue. They tell me it has too much, I drop it to 10G, and it doesn't even load spawn. So I then up it to 12G, it loads spawn but we can't get on. They tell me they got it confused with client and tell me to up it to 18G and I do. We can't log on. When we tried joining after launching it after all this is it says the server closed. I'm trying to log on with ATLauncher, my friend is using CurseForge. The server is being hosted through my computer, not a launcher.

### Steps to reproduce the issue

1. Launch server with 18G
2. Launch client through ATLauncher
3. Try and direct connect

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10607750/latest.log)
[crash report.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10607751/crash.report.txt)

**Comment by suckinsyn** [comment]
Try removing humancompanions mod and test

**Comment by DoctorMage** [comment]
Yeah for now do not interact with human companions

current options are down dating the mod to version 0.5.1 or removing the mod entirely
