### ISSUE TITLE
[Bug]: Hovering the cursor over any icon in the Goblin Trader window will cause the icons for all subsequent trades to disappear.

### ISSUE THREAD

**Issue by kalutro** [dr3ams/Roguelike-Adventures-and-Dungeons-2#18]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.3

### Describe your issue

Hovering the cursor over any icon in the Goblin Trader window will cause the icons for all subsequent trades to disappear.

### Steps to reproduce the issue

Hover the cursor over an icon in the Goblin Trader window.

### Additional Information

GIF of the bug in action.

![javaw_WjSyErd7EA](https://user-images.githubusercontent.com/69569507/187322727-2d73e617-f355-4598-b468-254ef0371f9a.gif)

As an aside, the tooltips for the coins should be updated to reflect their availability from Goblin Traders.

**Comment by VanyaBaou** [comment]
May be related to https://github.com/AHilyard/LegendaryTooltips/issues/43

**Comment by DoctorMage** [comment]
moved to #232
