### ISSUE TITLE
[Suggestion]: Optionally disable armor being "too hot to wear"

### ISSUE THREAD

**Issue by TigerBonez** [dr3ams/Roguelike-Adventures-and-Dungeons-2#182]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

For me personally, even if it does add realism and difficulty, temperature systems in games have always been a huge turn-off, so not being able to wear certain armor types because they're "too hot", and then having them launched out of your inventory with a plethora of debuffs just isn't enjoyable for me.
There might be a way to do this already, but I can't for the life of me find out which mod adds this so I can disable it, so at the very least, maybe this should somehow be made more apparent to be able to change? I'll take the blame if I'm missing something right in front of my face, but if this isn't already a feature, well here's my suggestion.

**Comment by VanyaBaou** [comment]
has nothing to do with temperature
it's Project MMO's stupidly phrased message about you not meeting the strict skill level requirement(s) for an item

reworded on our end next update, see https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/a1e2d0af74852529bdb58d10108cc628a4cf52c7
