### ISSUE TITLE
[Bug]: need to update human companions mod

### ISSUE THREAD

**Issue by chrysoljq** [dr3ams/Roguelike-Adventures-and-Dungeons-2#184]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

server openjdk11

### Modpack version

0.96beta

### Describe your issue

server crash because of human companions mod. just right click this mod's mobs. https://github.com/justinwon777/HumanCompanions/issues/33 

### Steps to reproduce the issue

 just right click this mod's mobs. 

### Additional Information

[https://pastebin.com/vD2j7Bvd](crash-2023-02-08_22.40.00-server.txt)

**Comment by DoctorMage** [comment]
yes we know have to wait for next modpack update
until then manually update the mod
