### ISSUE TITLE
Can't Climb Ladder/All ladder turn into decoration laddders[Bug]: 

### ISSUE THREAD

**Issue by HittingJH** [dr3ams/Roguelike-Adventures-and-Dungeons-2#189]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.0

### Describe your issue

I have ladder's in my house and I went to try and climb them up and fell to the bottom of the hole, I went into creative to see if all the ladders were like that and most of them become the normal minecraft ladder, but i can't climb it at all. The only ladder that doesn't turn into a normal ladder is the Iron ladder from twilight forest but i can't climb that either

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10700127/latest.log)

**Comment by DoctorMage** [comment]
update to 1.0a
