### ISSUE TITLE
[Bug]: world loading crash

### ISSUE THREAD

**Issue by raventhekeeper** [dr3ams/Roguelike-Adventures-and-Dungeons-2#19]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.16.5

### Describe your issue

A bug happened!

### Steps to reproduce the issue

simply creating a world will crash the game or cause it to not respond.

### Additional Information

[crash-2022-08-30_22.27.48-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9459095/crash-2022-08-30_22.27.48-server.txt)
[crash-2022-08-31_01.13.10-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9459096/crash-2022-08-31_01.13.10-server.txt)

**Comment by DoctorMage** [comment]
Ticking memory connection
For anyone having this issue in the future its normally to do with ram allocation
Make sure at least 6.5gb + ram is allocated to the pack
8gb to the safe
