### ISSUE TITLE
[Bug]: Sleeping Bag Quest doesn't recognize Update Aquatic's default uncoloured sleeping bag

### ISSUE THREAD

**Issue by 0Pdude** [dr3ams/Roguelike-Adventures-and-Dungeons-2#192]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism Launcher

### Modpack version

1.0a

### Describe your issue

The sleeping bag quest in the ftb quests page in-game doesn't recognize the default uncoloured sleeping bag from Update Aquatic as a valid item. However, it does recognize all coloured variants. I think it's because the default sleeping bag wasn't assigned a certain tag for the quest to detect.

### Additional Information

![image](https://user-images.githubusercontent.com/59374558/218287493-1ef1884a-a36a-4d0e-ba2a-c9a53cc561ce.png)

**Comment by VanyaBaou** [comment]
fixed in https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/34f3e9088c1febb9629ca6c7b6a01166f9a23bc8
