### ISSUE TITLE
[Bug]: the Lead cause a crash

### ISSUE THREAD

**Issue by GYPpro** [dr3ams/Roguelike-Adventures-and-Dungeons-2#204]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

PCL

### Modpack version

1.0a

### Describe your issue

A crash happened when i tie a Lead to the fence.
it also accored in single-player.

### Steps to reproduce the issue

 tie a Lead to the fence the remove it.

### Additional Information

[crash-2023-02-18_23.25.11-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10774635/crash-2023-02-18_23.25.11-server.txt)

**Comment by DoctorMage** [comment]
solpotato

**Comment by DoctorMage** [comment]
this only happens if nothing is attached to the lead so you attach it to yourself
