### ISSUE TITLE
Crafted Network Collector

### ISSUE THREAD

**Issue by xXAu5t3nXx** [dr3ams/Roguelike-Adventures-and-Dungeons-2#207]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curse Forge

### Modpack version

1.16.5-0.95a

### Describe your issue

A bug happened!

[crash-2023-02-22_12.11.23-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10807026/crash-2023-02-22_12.11.23-client.txt)

Every time i try to load into the server(which i host on Shockbyte) the game tells me this: 
22.02 18:10:27 [Server] Server thread/INFO [radenchants/]: (xXAu5t3nXx, the Knight) has prevented spawn of Mob (Bat) chunkX: -7 / chunkZ: -19 / Pos [BlockPos{x=-98, y=33, z=-300}] / Radius (1)  

sometimes for just one mob, sometimes for several mobs(some are vanilla mobs like zombies and some are modded mobs like blobfish). It crashes my game. This has happened over and over. I have tried debugging my curseforge, i have deleted all the mods and reinstalled them etc. Others have joined the server and had no issues.

Please help. 

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10807050/latest.log)

**Comment by DoctorMage** [comment]
first thing 
update the modpack to 1.0a 
second thing you crafted a network colelctor that has a bug were it will receieve a trait that as long as its in the players inventory your game will crash

you need to use an nbt editor to remove the item

https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win

**Comment by xXAu5t3nXx** [comment]
how do i do this? I'm not very technical and the friend I have that is cannot be online tonight. is there a step by step guide somewhere?

**Comment by xXAu5t3nXx** [comment]
I was able to figure it out. Thank you!
