### ISSUE TITLE
[Bug]: Dragonslaying XP gain problems

### ISSUE THREAD

**Issue by BreifSpeltWrong** [dr3ams/Roguelike-Adventures-and-Dungeons-2#209]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0a

### Describe your issue

A bug happened! - No XP gained from killing dragons:
Weapons used: Diamond & iron rapiers, Iron longswords

### Additional Information

No crash

**Comment by DoctorMage** [comment]
Pmmo being trash and not registering the hit not really a way to fix it other than just make sure nothing is near the dragon when its nearing death
