### ISSUE TITLE
[Bug]: floating point error in skill levelup

### ISSUE THREAD

**Issue by Blazing-Blast** [dr3ams/Roguelike-Adventures-and-Dungeons-2#21]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.3

### Describe your issue

I got level 3 in Endurance and it said I got a boost of 0.300...004%

### Steps to reproduce the issue

Haven't tried to reproduce, but try getting level 3 of endurance

### Additional Information

![2022-09-02_16 44 47](https://user-images.githubusercontent.com/69185984/188180439-f84da18b-6448-4a8b-b3c4-f537d6c9841f.png)

**Comment by DoctorMage** [comment]
Nothing can be done its an issue on pmmos end
