### ISSUE TITLE
[Bug]: Allies summoned by trinkets do not give player kills

### ISSUE THREAD

**Issue by Jamroot** [dr3ams/Roguelike-Adventures-and-Dungeons-2#211]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0a

### Describe your issue

Certain relics (in my case the dark egg) summon friendly mobs to attack enemies under various conditions. These mobs will slay enemies for the player in the same manner as a tamed mob like a dog. However, these mobs kills do not count as player kills, as such they are not registered by the quest book. I have not tested whether they give player drop items, however I would assume not. 

### Steps to reproduce the issue

1. Get dark egg trinket
2. Unlock the "meet your fight" slaying quests
3. check number of kills towards any common mob
4. let friendly vexes kill common mobs
5. confirm kills do not count toward quests

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10834528/latest.log)

**Comment by VanyaBaou** [comment]
Don't think anything can be done about that on our end.
