### ISSUE TITLE
[Suggestion]: PMMO inconsistently displays mob and biome xp gains, so please add 

### ISSUE THREAD

**Issue by Jamroot** [dr3ams/Roguelike-Adventures-and-Dungeons-2#212]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

As discussed with Bizzoula pmmo is, stupid. Please add some information to the quest book about what mobs need to be killed to gain exp in the less obvious skills (light/dark, also that ender drag gives dragonslaying *I know it seems obvious but players are dumb, myself included*)

This is because pmmo will, for some installs, seemingly at random, display no exp value gains for biomes and mobs. For these clients it appears to only display mobs with level requirements to damage, or biomes with... level requirements. Whatever that means. 

How a "bad" client displays:
https://cdn.discordapp.com/attachments/987711713572974612/1079486840203128862/image.png

How a not stupid client displays:
https://cdn.discordapp.com/attachments/987711713572974612/1079486868011368559/image.png

A *lot* of people in the discord confirmed that they have "bad" clients.

**Comment by VanyaBaou** [comment]
We probably won't add this to the quest book, if we do it will say check the glossary for info.

The issue itself should get fixed instead
Can't replicate on my end using fresh installs, never encountered on any recent fresh installs of RAD2 either
