### ISSUE TITLE
[Bug]: Guide to Animal Companionship makes dragons immune to the player

### ISSUE THREAD

**Issue by Jamroot** [dr3ams/Roguelike-Adventures-and-Dungeons-2#213]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0a

### Describe your issue

The guide to animal companionship is an item which is designed to make you not be able to damage passive mobs while you hold it in your inventory. Its actually an item from Terraria originally, and quite helpful as you dont randomly explode your entire chicken farm shooting a stray enchanted arrow. Unfortunately, it seems to for some reason also apply to dragons making it impossible to damage them. I should say, I have tamed dragons and the same thing applies to them (which it should!).

### Steps to reproduce the issue

1. Make new world
2. Get Guide to Animal Companionship
3. Find Dragon
4. Attempt to hit dragon
5. Die to dragon

### Additional Information

There are no associated logs that would be helpful. I would imagine there's a config you can set to prevent this from happening. Ice and Fire's dragons are a weird kind of entity, so it doesnt surprise me that this is occurring with them and you probably want it to happen in the case of tamed dragons.

**Comment by DoctorMage** [comment]
Issue with books code and ice and fire being a buggy mess but enigmatic legacy no longer supports 1.16.5 so unable to fix unless someone makes a pr to fix it themselves
