### ISSUE TITLE
[Bug]: Issue with buddysteel weapons + modifiers

### ISSUE THREAD

**Issue by Archovies** [dr3ams/Roguelike-Adventures-and-Dungeons-2#216]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

I'm not exactly sure if it's something I'm doing wrong, but the damage of the buddysteel sword will not update from 6 for me. 
I'm currently playing on a server of the latest version of RAD 2 (1.0a). Attached is a screenshot of the sword, my buddycard collection, and the sword in JEI. Is it possible I'm doing something wrong or am I right this is an error?
![image](https://user-images.githubusercontent.com/126927930/222864088-fdbf1f1d-5b11-4211-a650-7dd4a282fac7.png)
vs
![image](https://user-images.githubusercontent.com/126927930/222864123-250010cc-2ee6-4b3c-baa6-6695bf59ed82.png)
my binder, for reference:
![image](https://user-images.githubusercontent.com/126927930/222864111-9ce52135-fe3c-4fad-b828-531f8693d528.png)

**Comment by VanyaBaou** [comment]
it looks like you need more power unlocked, you have very few cards.
not sure if you're doing it, but like tooltip says, rightclick while holding to update power unlocked
odds are 12% power unlocked doesn't amount to an increase in damage
not sure on how the numbers work, but i _think_ it only goes up by whole numbers? been awhile since i used it

**Comment by Archovies** [comment]
I took a look in creative. It is not a bug to not have it progress at all at that point. The first damage increase is around 30% of all cards collected. It's just underpowered, not a bug. I would have to open about ~10 packs from each set to get the full set, or more. Duplicates of a higher rarity do not count toward power. This would take weeks of real-world time, and even if i got a perfected buddysteel sword with 86% or so (i got to this point after half an hour of pulling cards in creative) it would still be 9 damage, and I think 10 or 11 at 100%, unless there's a big bonus. At 86% power unlocked with the normal buddysteel sword, I may as well have just gotten 10 emeralds and made and emerald sword out of it. It's not a bug, you are right. But I would like to then suggest some kind of buff on the buddysteel weapons, even if it's just endgame for the perfected budddysteel swords at ~85% collection or something. Right now the only point in getting the cards is for collection, the swords are underpowered. 

PS sorry for the late reply, been working a lot recently.
