### ISSUE TITLE
[Suggestion]: Bronze bull quest

### ISSUE THREAD

**Issue by robolutas** [dr3ams/Roguelike-Adventures-and-Dungeons-2#221]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

It's a change to the bronze bull quest, and by proxy the talos one (if it exists), to state that their body uses gold blocks.

Proof:  (incase pictures didn't work https://canary.discord.com/channels/512339624627011586/987711713572974612/1083172783716053102)
![image](https://user-images.githubusercontent.com/55764796/223878187-4c2fed10-27b9-4f68-a076-7ac87c1bf8fa.png)
![image](https://user-images.githubusercontent.com/55764796/223878202-3288e938-44dd-4944-bdf8-4e11d28d2c32.png)

**Comment by VanyaBaou** [comment]
changed
