### ISSUE TITLE
[Bug]: Crash Error after updating from 1.0 to 1.1

### ISSUE THREAD

**Issue by Thwibble** [dr3ams/Roguelike-Adventures-and-Dungeons-2#222]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

After updating my server to version 1.1 its crashes on start up.
First time running a server for me and my mates, the problem could very well be user error.
I am using Bisect Hosting's in house installer.

### Additional Information

[crash-2023-03-09_03.28.49-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10927445/crash-2023-03-09_03.28.49-server.txt)

**Comment by DoctorMage** [comment]
On the server replace:
config\byg\byg-biomes.json
with the file here https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/blob/f74350baa19eb06bc0a5eaa8e7c3262b02ef6f19/config/byg/byg-biomes.json

can't upload the file you can join discord and find it as well 
https://discord.gg/Byee7EPY
