### ISSUE TITLE
(crash)ftp provider upload issues R.A.D 2

### ISSUE THREAD

**Issue by 9hrt** [dr3ams/Roguelike-Adventures-and-Dungeons-2#228]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

So i uploaded mods to my server and i didn't get a chance to even join and check if everything is working correctly cause it immediately crashed.

### Steps to reproduce the issue

1. i'm turning my server on everything is good
2. i'm trying to join server and its crashing

### Additional Information

crash report: https://pastebin.com/4JL4d5aX
latest.log: https://pastebin.com/BLs1UB9e

**Comment by VanyaBaou** [comment]
Don't upload logs via paste sites, some people can't access them.
Just upload them directly.

Also, what?
>  i uploaded mods to my server
![image](https://user-images.githubusercontent.com/97327658/225148007-b2f87a05-01f2-4e3a-83dc-b8f1acaf69e5.png)


Remove the changes made on your server, or rather re-download the Server Pack and launch it, then join on an unmodified client, and see if it works.

**Comment by DoctorMage** [comment]
@9hrt if your using an ftp server proider one or mutliple files got messed up

just redo the setup but don't send files in bulk

at most 10 or if you can the serverpack as a zip then unzip it inside the ftp
