### ISSUE TITLE
[Bug]: server pack

### ISSUE THREAD

**Issue by Dragonik1** [dr3ams/Roguelike-Adventures-and-Dungeons-2#229]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

serverpack 1.1fix

### Describe your issue

hello when I download the server pack it says that the archive is corrupted please fix it thank you

### Additional Information

unexpected end of the archive

**Comment by DoctorMage** [comment]
Works fine for others and tested myself

normally that error means that you have something blocking the download
