### ISSUE TITLE
Bookshelf from Builders Crafts & Addition accepting items other than books

### ISSUE THREAD

**Issue by LordUnnamed** [dr3ams/Roguelike-Adventures-and-Dungeons-2#230]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

The bookshelves can't accept items other than books when a player tries to insert them, however they do accept any item when fed through a hopper or a simple storage network cable.

### Steps to reproduce the issue

(1) place bookshelf
(2) place hopper pointing into bookshelf
(3) place any item inside hopper
(4) item will be put in bookshelf

### Additional Information

I ran into the issue on a LAN-World.

**Comment by VanyaBaou** [comment]
Not something we can do anything about on our end, you can submit an issue to them if you want.
