### ISSUE TITLE
[Bug]: Game crashes as soon as healing bonfires gets loaded when i try to play with optifine

### ISSUE THREAD

**Issue by DarkAngel1-59** [dr3ams/Roguelike-Adventures-and-Dungeons-2#233]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1 (1.16.5)

### Describe your issue

I have given the game around 8gb of RAM and try to start it and as soon as it starts to load the healing bonfire mod the game with the launcher crashes.
I already have read to the previous report of someone having crashes while trying to start the game with optifine and already deleted the mods that were listed there to resolve the problem (those mods were the magnesium , rubidium and oculus mod).
The solution from the previous report has helped a bit with loading the game but  it wont completely start the game and crash mid way through the loading of the mods

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11042885/latest.log)

**Comment by DoctorMage** [comment]
Remove optifine
