### ISSUE TITLE
[Suggestion]: Add Tetra mod, More customizability for tools

### ISSUE THREAD

**Issue by HerdarDdy** [dr3ams/Roguelike-Adventures-and-Dungeons-2#237]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

While it would probably need some work done balance-wise, in my opinion, adding the Tetra mod would fit the pack style.

**Comment by DoctorMage** [comment]
Balancing issues and making all the pmmo requirements is a hassle
Already been considered and rejected
