### ISSUE TITLE
[Bug]: TemptGoal Crash when Teleporting

### ISSUE THREAD

**Issue by jimmy-chuan** [dr3ams/Roguelike-Adventures-and-Dungeons-2#238]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

when I click U and tp to home from the cave,and then game crash -1.  It never happend until today.   (My bag have many treasure I first get.)

The game crashed whilst exception in server tick loop
Error: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unsupported mob type for TemptGoal

### Steps to reproduce the issue

1.play in cave 
2.click U tp to home
3.I arrive at home and suddenly game crash

### Additional Information

[crash-2023-03-23_23.51.13-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11053157/crash-2023-03-23_23.51.13-server.txt)

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11053233/latest.log)

**Comment by VanyaBaou** [comment]
could you elaborate on what "click U tp to home" means?

**Comment by jimmy-chuan** [comment]
Sorry,I mean I pressed U and open waypoint menu,and use tp.

By the way,I removed the alexsmobs,and entered the game successfully.

**Comment by VanyaBaou** [comment]
I'm not able to replicate this issue.
If you can replicate it and confirm it is alexsmobs causing your crash, you should submit an issue to alexsmobs instead.

**Comment by jimmy-chuan** [comment]
https://github.com/VazkiiMods/Quark/issues/2975

I used this method to successfully enter the game and play, thank you
