### ISSUE TITLE
[Bug]: FTB Ultimine not working as intended (?)

### ISSUE THREAD

**Issue by HerdarDdy** [dr3ams/Roguelike-Adventures-and-Dungeons-2#240]
### General Info

- [ ] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism Launcher 6.3

### Modpack version

1.1

### Describe your issue

Whenever using FTTB Ultimine, shapeless works for most blocks, however, the mining tunnel, escape tunnel and small tunnel do not work at all, with 'small square' only destroys one block (supposed to be a 3x3x1). No matter what block is mined, the same result happens.

### Steps to reproduce the issue

1. Hold FTB Ultimine key
2. Select any mode except 'Shapeless'
3. Mine block and / or look at the render

![image](https://user-images.githubusercontent.com/64714569/227339189-353abcbc-a6d3-4e8c-84be-006a19a072bd.png)

Image shows it with stone, but the block doesn't matter, as it affects all blocks

### Additional Information

![image](https://user-images.githubusercontent.com/64714569/227339386-b0402988-7e03-4884-8b16-218d73ab2df0.png)
![image](https://user-images.githubusercontent.com/64714569/227339514-803113ba-2e0f-47be-af8c-95ccc773c373.png)
![image](https://user-images.githubusercontent.com/64714569/227339585-ab79cc8a-33dd-404a-b3e1-d95f7301fe5a.png)
![image](https://user-images.githubusercontent.com/64714569/227339630-4e295d66-e2b6-4505-848d-488f0c237527.png)
Top right shows the selected shape to mine, middle of the screen shows the render or lack thereof.

**Comment by VanyaBaou** [comment]
stone is blacklisted
everything here is working as intended
mod is being replaced next update anyways
