### ISSUE TITLE
[Bug]: Server disconnects player trying to join

### ISSUE THREAD

**Issue by hersheyunkers** [dr3ams/Roguelike-Adventures-and-Dungeons-2#241]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

Hi i have a very small 2 player person server on aternos, but consistently after 1.1 I've been having this Netty IO error but the closing says Timed Out or sometimes something with encoder/concurrent modification. We jumped from .85 to 1.1 after a few months break, before server worked perfectly as it can, and in 3 days it's been kicking me out consistently and the only fixes I can do is relaunching mc or relaunching server but the kicking out is getting more frequent and relaunching is also time consuming.

Don't do this just send the log file please
 

Here's another version I scrolled up to:

Don't do this just send the log file please

### Additional Information

It doesn't force crash minecraft itself so there's no crash log, but it does not let me join an active online server that the other person can usually join with a breeze (we are on the same wifi).  Consistent rejoining leads to Timed Out - checking the aternos server log shows this varied line most frequently with no other explanation. 

[Netty Epoll Server IO #3/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize com.infamous.dungeons_libraries.commands.arguments.MobEnchantmentArgument@1f0da25f (class com.infamous.dungeons_libraries.commands.arguments.MobEnchantmentArgument) - will not be sent to client!

Fortunately, I was lucky to see more of the log with what I pasted, hopefully it helps with the context! I also tried to post on dungeon libraries issues. Thank you.

**Comment by DoctorMage** [comment]
Send the actual crash report ifle please

**Comment by VanyaBaou** [comment]
Just simply don't use Aternos. It is trash and we don't support it.
RAD2 isn't even available on Aternos anymore afaik.
Also disconnect =/= crash.

**Comment by hersheyunkers** [comment]
Right, I'm starting the process to just move it to your guys' server files because yup aternos is deprecating it soon after 1.1. Thanks for the replies, I'll try my best to transfer.
