### ISSUE TITLE
[Bug]: Incomplete wither skeletons dropping wither skulls 100% of the time

### ISSUE THREAD

**Issue by HerdarDdy** [dr3ams/Roguelike-Adventures-and-Dungeons-2#242]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism Launcher 6.3

### Modpack version

1.1

### Describe your issue

Incomplete wither skeletons from Stalwart dungeons mod always drops wither skeleton skulls when killed.

### Steps to reproduce the issue

1. Find an awful dungeon
2. Kill incomplete wither skeletons
3. 100% of the time will drop a wither skull

### Additional Information

![image](https://user-images.githubusercontent.com/64714569/227384445-ae11d5e2-e184-49db-bb22-e5fd832d1cc7.png)

**Comment by DoctorMage** [comment]
what weapon are you killing them with

**Comment by DoctorMage** [comment]
Seems intended

**Comment by HerdarDdy** [comment]
To answer the comment, I was using a regular iron sword, and fists, both dropped wither skeleton skulls
