### ISSUE TITLE
[Bug]: Incompatibility issue with Productive bees and Majruszs Accessories.

### ISSUE THREAD

**Issue by DocTran** [dr3ams/Roguelike-Adventures-and-Dungeons-2#243]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0a

### Describe your issue

I have on two separate worlds run into a crash by a ticking entity pointing at the farmer bee. I was able to observe the last time the game crashed it was at the moment a farmer bee tried to harvest wheat. Currently in SSP

I notified the Productive bees Author here https://github.com/JDKDigital/productive-bees/issues/369

### Steps to reproduce the issue

Have a Farmer Bee harvest wheat.

[crash-2023-03-19_02.21.19-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11070265/crash-2023-03-19_02.21.19-server.txt)

### Additional Information

Crshe report included
Productive Bees Author said will contact also.
Thank You

**Comment by VanyaBaou** [comment]
Mod is being removed in next pack update.
