### ISSUE TITLE
sudden fps drops

### ISSUE THREAD

**Issue by 9hrt** [dr3ams/Roguelike-Adventures-and-Dungeons-2#244]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

i've been playing on RAD 2 for past 2 days and everything was good till yesterday, when my game started to dropping fps to like 1-3 max and regardless settings that i've been changing to minimum it still was max 1-3 fps i don't know what to do, i was trying to put java arguments and it didn't help. Please help me i still want to enjoy this amazing pack.

### Steps to reproduce the issue

my fps are dropping regardless settings i set maximum is 3fps

### Additional Information

pack is not crashing.

**Comment by DoctorMage** [comment]
Pc specs 
cpu model name
total ram
gpu
and ram allocated in game

easy way of getting this is pressing f3 in game and sending a screenshot
