### ISSUE TITLE
[Question]: Chunk Loading

### ISSUE THREAD

**Issue by Mandalorian-666** [dr3ams/Roguelike-Adventures-and-Dungeons-2#247]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Are there any chunk loading blocks in this modpack/ any way to keep my storage network chunkloaded?

Want to be able to access the simple storage network using the remote but cant see a way to keep the chunk loaded. I am playing on a server with friends.

**Also please let me know if there is a more appropriate place to ask these sort of questions if this isn't the place to do so :)**

**Comment by RecyclingTiger** [comment]
The only way to keep a chunk loaded is by using an undergarden portal. See "Simple Storage remote does not work" in the faq found in the wiki section to figure out how to do it.

**Comment by Mandalorian-666** [comment]
I tried this but the lava just destroys the rails so I don't think it works anymore.

**Comment by Mandalorian-666** [comment]
Found a different version that works without using minecarts.
