### ISSUE TITLE
[Bug]: Multiplayer shop crash

### ISSUE THREAD

**Issue by hackingStrawberry** [dr3ams/Roguelike-Adventures-and-Dungeons-2#248]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Hello Minecraft Launcher (HMCL)

### Modpack version

1.1

### Describe your issue

My game crashes whenever I join a multiplayer server and opens the shop. This is my crash report, i think it has something to do with rendering screen or an icon called "rad2", because on my server whenever i click shop it says
[07:12:40] [Server thread/INFO] [minecraft/DedicatedServer]: [22:02:48] [CraftPresence/ERROR]: Asset name "rad2" does not exist, using cached icon ""...
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11127831/latest.log)
PLS HELP ME
edit: I can open the shop in single player for some reason

### Steps to reproduce the issue

1. Join a multiplayer world
2. Click the first book
3. Click the shop on right top
4. Boom... crashes

### Additional Information

Im using java 1.8.0_341 with windows x86-64

**Comment by Udtk** [comment]
Set online-mode=true

**Comment by Pythoenixx** [comment]
> Set online-mode=true

where i can do this?

**Comment by Gunner76th** [comment]
> > Set online-mode=true
> 
> where i can do this?

Stop your server
Edit the file server.properties 
Set online-mode=true
Start your server

Anyone who doesn't legally own minecraft will be required to purchase it.

**Comment by Gunner76th** [comment]
Also we do not support cracked/illegal launchers
