### ISSUE TITLE
[Bug]: Brew stand  not working

### ISSUE THREAD

**Issue by xuqinkun** [dr3ams/Roguelike-Adventures-and-Dungeons-2#251]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

RAD2-1.16.5-1.1

### Describe your issue

I can't brewing. The vanilla brew stand  not working.
![image](https://user-images.githubusercontent.com/19572081/229744523-74a11536-a7df-4cfe-ac1e-4f0cfc302a28.png)

### Additional Information

,,,

**Comment by xuqinkun** [comment]
I can't put the bottles into the slots.

**Comment by DoctorMage** [comment]
you have to put bottles in one by one not as a stack
