### ISSUE TITLE
[Bug]: I can't hurt my cats.

### ISSUE THREAD

**Issue by xuqinkun** [dr3ams/Roguelike-Adventures-and-Dungeons-2#252]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

RAD2-1.16.5-1.1

### Describe your issue

I can't hurt my domesticated cat in any way. When I shoot my cat with a bow, the arrow bounces off. 
![image](https://user-images.githubusercontent.com/19572081/229784070-6afa3cb1-6fb0-4b1e-bc00-2f127217812b.png)

### Additional Information

...

**Comment by xuqinkun** [comment]
By the way, I don't have any Guide to Animal Companionship in my inventory.

**Comment by xuqinkun** [comment]
By the way, I don't have any Guide to Animal Companionship in my inventory.

**Comment by DoctorMage** [comment]
Does this occur with no armour or trinkets equipped

**Comment by xuqinkun** [comment]
> Does this occur with no armour or trinkets equipped

Yes, this occured even if I unequipped all my armours and trinkets

**Comment by VanyaBaou** [comment]
This is intended. Pet friendly fire is disabled.
