### ISSUE TITLE
[Bug]: Can't Teleport

### ISSUE THREAD

**Issue by NoLuckInvolved** [dr3ams/Roguelike-Adventures-and-Dungeons-2#253]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

1.16.5

### Describe your issue

Whenever I try to teleport, right-click on fullmap or teleport through waypoints, I receive the same message: "Unknown or incomplete command, see below for error   /tp @s -174 74.5 104<--[HERE]"

### Steps to reproduce the issue

1. Press "m" to open world map
2. Right-click anywhere on map
3. Click "Teleport Here"
4. Error msg in chat appears

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11151095/latest.log)

[13:06:47]

**Comment by DoctorMage** [comment]
are you op level 4 on the server
an easy check is to make sure /gamemode creative works
