### ISSUE TITLE
[Bug]: enchantment table unable to view all available enchantments

### ISSUE THREAD

**Issue by 345022817** [dr3ams/Roguelike-Adventures-and-Dungeons-2#255]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

When using an enchantment table I am unable to view all available enchantments.
I can click the button but the GUI does not load have to press esc to get out.

Original Post: [https://github.com/Shadows-of-Fire/Apotheosis/issues/795](url)

### Steps to reproduce the issue

![222279391-51252788-f9e3-4cd2-ba39-40c0598b6f2e](https://user-images.githubusercontent.com/47494915/230424349-ad32445f-fd8d-494f-8659-2e61a679a7b6.gif)

### Additional Information

Need help Plz.

**Comment by DoctorMage** [comment]
known issue
just use jei feature
