### ISSUE TITLE
[Bug]: Simple Storage: Network Collection Interface Infinite Loop Crash

### ISSUE THREAD

**Issue by Cazitron** [dr3ams/Roguelike-Adventures-and-Dungeons-2#257]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

RAD2 - 1.1 [1.16.5] - (Release) - (Current)

### Describe your issue

Attempting to insert an item into a Simple Storage Solutions Network while a Network Collection Interface is attached crashes the world; it does not corrupt it, but a restart is forced upon you. A server will also crash.

### Steps to reproduce the issue

1. Place down a network root from Simple Storage Solutions
2. Attach whatever length of link cables 
3. Then attach a Network Collection Interface to the network
4. Now, just insert an item into the network

You can point a hopper into the Network Collection Interface block and put an item in the hopper, or you can place a network crafting terminal and shift-click an item into the GUI. 

This is repeatable as long as the item has nowhere to go. No attached storage, or all storage attached is full.

### Additional Information

[crash-2023-04-06_15.01.43-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11173866/crash-2023-04-06_15.01.43-server.txt)
[crash-2023-04-06_14.51.54-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11173867/crash-2023-04-06_14.51.54-server.txt)

I can't get the server logs, but likely the same issue.

**Comment by DoctorMage** [comment]
Screen record/screen shot the setup/layout

**Comment by Cazitron** [comment]
![image](https://user-images.githubusercontent.com/46332689/230699101-ef8e3b0c-aab8-459b-9ccb-c3fba0de23be.png)

**Comment by VanyaBaou** [comment]
This isn't an issue we can fix, you should submit an issue to SSN GitHub instead.
