### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CorgiRay17** [dr3ams/Roguelike-Adventures-and-Dungeons-2#26]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.4

### Describe your issue

A bug happened! I can't even join the world in multiplayer. It stays at 'Joining world...' for eternity. It's literally unplayable. And yes, I tried asking for support through bisecthosting team, but nothing works. I've tried joining with and without adding mods. 

### Additional Information

N/a (I deleted the modpack) I had enough ram for it

**Comment by DoctorMage** [comment]
Does the server console show you attempting to join

**Comment by dr3ams** [comment]
No logs, but it looks like pmmo+jei issue strikes back. Anyway, official serverpack isn't released yet so closing it for now
