### ISSUE TITLE
[Bug]: Upon joining world, game freezes, can't close window, and monitors start glitching

### ISSUE THREAD

**Issue by swilly97** [dr3ams/Roguelike-Adventures-and-Dungeons-2#264]
### General Info

- [ ] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

1.1

### Describe your issue

I'm on Linux, Ubunte MATE. I have three monitors, and am launching through ATLauncher. I can get to the start menu and the options menu just fine, but when I try to create/join a world, everything stops. My screens go black for a couple seconds, and when they come back I can move the mouse, but can't interact with anything. There are lines running down the monitors, and the minecraft window freezes. I have to forcibly restart the computer, and I don't get any crash reports about the issue. I downloaded the modpack and didn't make any changes, and redownloaded to double check, with the same results. I know other modpacks work on my computer (I was just playing ATM7), so I'm assuming it's something with this modpacks.

### Steps to reproduce the issue

Start AT Launcher.
Run Roguelike Adventures and Dungeons 2
Attempt to create/join world.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11186204/latest.log)

**Comment by DoctorMage** [comment]
What gpu and cpu does your pc have

**Comment by swilly97** [comment]
I have a Radeon HD 5770 graphics card and an Intel Core i5-4690k CPU

**Comment by DoctorMage** [comment]
Modpack does not play nice with 4 core cpu but bugging out should not occur

remove those mods see if it still happens
    magnesium extras mc (magnesium / rubidium extras)
    oculus
    rubidium
    Road runner
    
  Also how much ram does your pc have and how much allocated to the modpack as well as args being used
