### ISSUE TITLE
[Bug]: Cant turn off auto jump

### ISSUE THREAD

**Issue by HojpMania** [dr3ams/Roguelike-Adventures-and-Dungeons-2#268]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

Cant turn off auto-jump within options/controls. When you switch off and press done, it'll just re-activate no matter what

### Steps to reproduce the issue

1. Go to options menu
2. Go to controls
3. Turn off auto-jump
4. Done
5. Go back to in-game
6. Repeat

### Additional Information

No other additional info

**Comment by DoctorMage** [comment]
step up turn that off
