### ISSUE TITLE
[Bug]: FTB Ultimine is not working

### ISSUE THREAD

**Issue by ZapperBanjo** [dr3ams/Roguelike-Adventures-and-Dungeons-2#269]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.2

### Describe your issue

FTB Ultimine is not working

### Additional Information

FTB Ultimine is not working

**Comment by NewAnnLS** [comment]
There is no ftb ultimine in 1.2, thus it is not possible for it to work.
