### ISSUE TITLE
[Bug]: Vegas spawners inactive

### ISSUE THREAD

**Issue by gatohaus** [dr3ams/Roguelike-Adventures-and-Dungeons-2#27]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.4

### Describe your issue

Hi. I love the upgrade from RAD. Thank you for making this!

Very early game..  Found a Las Vegas structure.  Spawners are inactive.   Collected treasure at night and day.  Not a single mob spawned.    Spawners work in other structures like pyramids and dungeons.   There are some light levels near some spawners that are at zero, so it's not that.   

Attached world gen json. (renamed to .txt for upload)
Las Vegas at 531,-829
[worldgen_settings_export.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9657795/worldgen_settings_export.txt)

### Steps to reproduce the issue

I only have the one, single-player case.  Have not seen other Vegas structures.

### Additional Information

blank

**Comment by DoctorMage** [comment]
Known issue if the player dies at anypoint any mob spawning functions break restart fixes this

**Comment by DoctorMage** [comment]
Spawners should be working now will test an update
