### ISSUE TITLE
[Bug]: pmmo skill xp got reseted

### ISSUE THREAD

**Issue by Pengi4121** [dr3ams/Roguelike-Adventures-and-Dungeons-2#270]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

A player got killed and lost all of his skill level.IDK if he press anything wrong or wat, he dont have this problem when we first start playing.And he is the only player with this problem

### Additional Information

[pmmo.zip](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11230453/pmmo.zip)
Im using scalacube for server provider, and Alice_Exd was the player name.

**Comment by Pengi4121** [comment]
I did, but it happens when ever he died

**Comment by DoctorMage** [comment]
how is the server being hsoted
provider? as in brought it from a host
or hosting on your own pc

find were you access the server files go to the folder called logs send the file called latest here

**Comment by Pengi4121** [comment]
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11238496/latest.log)
i backed up the world and continue to play while ignoring the problem  so I'm not sure if the log has wat u want.
and I bought the server from ScalaCube

**Comment by DoctorMage** [comment]
these are the client side logs they won't help at all I specified grab the server logs
