### ISSUE TITLE
[Bug]: Overpowered Capsule

### ISSUE THREAD

**Issue by ScriptAero** [dr3ams/Roguelike-Adventures-and-Dungeons-2#272]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.2

### Describe your issue

The overpowered capsule that requires netherstar can pick up spawners

### Additional Information

no crash just should be disabled

**Comment by NewAnnLS** [comment]
> no crash just should be disabled

Oversight, it is disabled in next update.

**Comment by ScriptAero** [comment]
Yes I am aware lol, im a tester
