### ISSUE TITLE
[Bug]: Hunger+Agility act as if always running, even if still.

### ISSUE THREAD

**Issue by RexiaXIV** [dr3ams/Roguelike-Adventures-and-Dungeons-2#273]
### General Info

- [ ] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.16.5-0.5

### Describe your issue

I unfortunately am not sure when exactly this happened, or what could've triggered it, but I've noticed that my hunger had been decreasing at an increased rate, even when still and unharmed. I also noticed that I keep getting points in the agility stat, as if I was running/jumping, at a consistent rate, even if I am still.

I do not recall adding any mods that could have affected this (just a few QoL like stack replace and fence jumper, readding prefab and alex's delight).

I think this has been occurring for several sessions already, so closing the game won't work. 

### Steps to reproduce the issue

1. Enter game
2. Hunger stat immediately acts as if running even before moving.

### Additional Information

https://gist.githubusercontent.com/RexiaXIV/c77201f53f252e722042a0b3c767496a/raw/78f5687147cf790791bcb2d3fe5ffa3386056694/gistfile1.txt

**Comment by DoctorMage** [comment]
Remove any mods you added and see if the issue reoccurs
best to just make a new instance of the modpack to test that in

**Comment by RexiaXIV** [comment]
Gotcha, I wasn’t sure if anyone else ever had this issue, so I wanted to check just in case, but I feel a bit silly now. *sheepish*

Apologies! Will be more careful testing with tweaks.
