### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jityuiz** [dr3ams/Roguelike-Adventures-and-Dungeons-2#274]
### General Info

- [ ] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

PCL

### Modpack version

1.6.5

### Describe your issue

无法去往下界

### Additional Information

没有崩溃

**Comment by DoctorMage** [comment]
下界门户不工作

要进入下界，您必须找到地下下界传送门

https://www.curseforge.com/minecraft/mc-mods/yungs-better-portals
