### ISSUE TITLE
[Bug]: Crashes with optifine 

### ISSUE THREAD

**Issue by YoungJelly** [dr3ams/Roguelike-Adventures-and-Dungeons-2#28]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.16.5

### Describe your issue

Crashes on launch due to optifine

### Steps to reproduce the issue

Unknown

### Additional Information

Need help resolving this one.

**Comment by dr3ams** [comment]
Pack has built-in support for shaders. Just drop your shaders in **shaderpacks** folder and select them in video setting.
If you still need Optifine:
1. Go to mods folder
2. delete the following mods 
- rubidium-*.jar 
- oculus-*.jar
- magnesium_extras-*.jar
