### ISSUE TITLE
[Bug]: Cant launch server without crash

### ISSUE THREAD

**Issue by RagingStorm12** [dr3ams/Roguelike-Adventures-and-Dungeons-2#286]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

1.2

### Describe your issue

crash when launching server i hava java 8 / 15 only and when i launch mmo mod has issues with ftb quests

### Steps to reproduce the issue

everytime i launch the server

### Additional Information

[crash-2023-05-08_17.24.57-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11426103/crash-2023-05-08_17.24.57-fml.txt)

**Comment by Exapos** [comment]
Same problem here... Just installed the server-pack from the web and didn't add or update any mod.. And crashing at project MMO... The same goes for any other server-packs that isn't 1.0a that's the only one which works for me
[crash-2023-05-09_11.01.12-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11429295/crash-2023-05-09_11.01.12-fml.txt)

**Comment by Exapos** [comment]
I did some searching and found the cause of the problem.

Follow this for fix #58

**Comment by DoctorMage** [comment]
> I did some searching and found the cause of the problem.
> 
> Follow this for fix #58
> 
> Edit: I suggest mods or developers mention it in the wiki how to start the server, it might not be clear for everyone

it is mentioned in the wiki https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/wiki/Java-Verison-(W.I.P)

**Comment by Exapos** [comment]
> 

Then I suggest to update the[ * How to install](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/wiki/*-How-to-install) page because that's what I had followed and as i said it might not be clear for everyone to search it in the [Java-Version](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/wiki/Java-Verison-(W.I.P))
