### ISSUE TITLE
[Bug]: 2-5 FPS Unless standing still, cannot get game to run

### ISSUE THREAD

**Issue by Thundernova1** [dr3ams/Roguelike-Adventures-and-Dungeons-2#288]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/4a43f16f-48cb-432a-98d8-44988fa873c0)
**Curse forge says modpack version do not say latest**

### Describe your issue

I just can't get the game to play at all. It will load in and as soon as I try to move it shoots down to 1 or 2 FPS or even 0
![1683861936270552021679736160811](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/133306280/1902efc2-20d7-4cb3-af4e-4c14c94c86ea)
![16838619511915302306395195457228](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/133306280/00ade567-253b-4c95-b919-7245872767ff)

### Steps to reproduce the issue

Logging on and attempting to play the game. 

### Additional Information

Not crashing just not running

**Comment by DoctorMage** [comment]
turn off vsync and allocate more ram
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/5e1f0d31-7feb-46b3-b456-1b96befec58d)

**Comment by Thundernova1** [comment]
This fixed the issue! thank you so much!!!
