### ISSUE TITLE
[Question]: Prefab removed in 1.1 

### ISSUE THREAD

**Issue by clytemnestra** [dr3ams/Roguelike-Adventures-and-Dungeons-2#290]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hello, I played on 0.9 and upgraded to 1.3 and saw that Prefab was removed in 1.1

May I ask why and if it will be re-added in the future?

**Comment by DoctorMage** [comment]
It does its just not enabled unless capsules mod author removed that feature
