### ISSUE TITLE
[Suggestion]: megalake biome disabled

### ISSUE THREAD

**Issue by wattarug** [dr3ams/Roguelike-Adventures-and-Dungeons-2#291]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

enable megalake biome in the end, to complete the quests

**Comment by DoctorMage** [comment]
oversight as biome was disabled due to issue will remove quest for next update
