### ISSUE TITLE
[Suggestion]: Server Performance updates/changes

### ISSUE THREAD

**Issue by SavocaMichele** [dr3ams/Roguelike-Adventures-and-Dungeons-2#292]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I've joined the Discord to report some issues I've found and was told to post them here and to state what changes I've made to achieve better server performance. [Message Link](https://discord.com/channels/512339624627011586/512340728215502878/1107699989012021380)

**Tested on RAD2 1.16.5 v1.2**

**Debugging Mods**
> Spark 1.9.1 ([Link](https://www.curseforge.com/minecraft/mc-mods/spark))
> Observable 0.2.1 ([Link](https://www.curseforge.com/minecraft/mc-mods/observable))

**Performance Mods**
> SmoothChunk ([Link](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save))
> Rubidium ([Link](https://www.curseforge.com/minecraft/mc-mods/rubidium))
> Performant ([Link](https://www.curseforge.com/minecraft/mc-mods/performant))
> AI-Improvements ([Link](https://www.curseforge.com/minecraft/mc-mods/ai-improvements))
> Chunk Pregenerator ([Link](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator))

That being said, some of these mods are heavily reliable on the Server Hardware. These mods spread all minecraft tasks to each available thread accross all CPU Cores. Minecraft only using one thread is a major performance issue alone.

**Chunk Pregenrator / Smooth Chunk**
Since this modpack literally has the word "adventure" in it's name, people go exploring - a lot. Chunk loading is a huge task for the Server and mounts like dragon that fly extremely fast will beat the Server up immediately. Chunk pregenerating helps really a lot with this issue but obviously it is very very time consuming and can make the server unplayable for multiple days.

**AI-Improvements**
This is probably the most important step performance wise. This modpack spawns excesive amounts of mobs with different skill-sets and pathfinding logic. The skilled and elite mobs are especially bad for the server. For example a non moving, stationary skilled mimic chest took 500 µs/tick. One singular mimic.. I've debugged a lot and when pressing F3 you can see that the Server load 200+ mobs around you, while you can only see 10 or fewer. 200 mobs times 10 players is just unplayable.

Additionaly Alex's Mobs is pretty nice for Farmers Delight but this mob spawns tons of water creatures together with Aquaculture 2. I disabled the Blob Fishes because they spawn in batches of 40 or more, deep underground where nobody can see them and they're completely useless as well.

The biggest performance issue this modpack has is its huge amount of mob spawning. Skilled and Elite Mobs especially. Not everyone has the patience or money to buy dedicated linux machines and do tons of optimizing, just to play with more than 3 friends on a server. Let alone how expensive "Gaming Servers" like shokbyte- or apex hosting are.

**Additional**
I'm not sure for how long this [Spark Report](https://spark.lucko.me/cGlAIeYYyp) will be available but it shows that "Rad enchants" takes up the most Server Thread. To my understanding it only adds enchantment books to the game so I don't quite get why it needs to do entity checks on every tick.. If you could look into issues like these I think the server would already run a lot smoother.

For further questions you can mention me here.
Thank you for reading and your patience :)

**Comment by SavocaMichele** [comment]
Image of mob tick from Observable
![grafik](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/29930454/11822ec2-1c94-46bf-8d45-96a54c5b2f2a)

**Comment by dr3ams** [comment]
Thank you for report!
