### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deadetou** [dr3ams/Roguelike-Adventures-and-Dungeons-2#293]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Minecraft Launcher Using  36.2.39 1.16.5

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

I keep crashing everytime I load into my multiplayer server...
No clue why. The second I join, I crash.

### Steps to reproduce the issue

Join server
then you crash

### Additional Information

[crash-2023-05-15_21.23.13-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11483073/crash-2023-05-15_21.23.13-client.txt)

**Comment by Gunner76th** [comment]
You do not have enough ram allocated to the game. In Curseforge you need to change the RAM allocation to a minimum of 6144mb, according to the crash report you are only allocating 2048mb of ram.

**Comment by deadetou** [comment]
Do I have to launch from curseforge? I just moved all the mods to a  custom minecraft profile but then when I joined my server I got "failed to synchronize registry data from server"
I am sure all my mods matched though
I don't want to launch from curseforge unless its a last resort.

**Comment by Gunner76th** [comment]
You shouldn't be using the standalone launcher.  Curseforge already
launches that when you go to start the game.  This also explains why your
crash report showed only 2gb of ram allocated.

**Comment by DoctorMage** [comment]
there are altenatives to curseforge
atlauncher, gdlauncher are easiest to setup and use
default mojang launcher is awful when it comes to handling large modpacks
