### ISSUE TITLE
[Bug]:  Server crashes on load

### ISSUE THREAD

**Issue by BritishMindslave** [dr3ams/Roguelike-Adventures-and-Dungeons-2#294]
### General Info

- [x] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.2

### Describe your issue

I was playing the game as of Sunday and when I attempt to load the modpack on a singleplayer world, it crashes.
I assume it has something to do with Java, but my brain is frying trying to figure this out on my own and would love if someone could take a look at what the issue is haha

I _have_ added a few mods, just 4 mods related to Origins that weren't fabirc-related. I had been running just fine, all crashes I've had lead back to this issue alone.

[crash-2023-05-16_15.04.35-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11491809/crash-2023-05-16_15.04.35-client.txt)

### Additional Information

[crash-2023-05-16_15.04.35-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11491823/crash-2023-05-16_15.04.35-client.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11491824/latest.log)

**Comment by Gunner76th** [comment]
From the crash report:
java.lang.RuntimeException: Xaero's Minimap (1.16.5_23.1.0) has crashed! Please report here: bit.ly/XaeroMMIssues

I suggest going to http://www.bit.ly/XaeroMMIssues and reporting the issue to them.

**Comment by BritishMindslave** [comment]
That doesn't seem to be the only issue, as I have crashed once again even though I disabled the minimap.
[hs_err_pid2972.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11492562/hs_err_pid2972.log)
New crash log lol

**Comment by Gunner76th** [comment]
That error is a hard Java crash because it ram out of memory.

**Comment by DoctorMage** [comment]
crash seems related to Xaero but with mods added that can have different effects no matter make a backup of the world
remove mods add see if issue still occurs
