### ISSUE TITLE
[Question]: Where can I enable normal Nether Portals?

### ISSUE THREAD

**Issue by cl500** [dr3ams/Roguelike-Adventures-and-Dungeons-2#296]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Where do I enable the normal Nether Portal? I wanna enable them for our server to build some farms

**Comment by DoctorMage** [comment]
Remove the mod https://www.curseforge.com/minecraft/mc-mods/yungs-better-portals
