### ISSUE TITLE
[Bug]: Spawner issue?

### ISSUE THREAD

**Issue by FlintlockKatze** [dr3ams/Roguelike-Adventures-and-Dungeons-2#297]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

Im sorry if this is not the right place, but spawners seem to be not placeable? I was able to place them in 1.2 and trying to set up a server but when i get a spawner in the description it says Can not be placed. Is this a bug or intended? If its intended anyway to change if?

### Additional Information

Im not sure what log to put here? As it is not a crash report/

**Comment by DoctorMage** [comment]
spawners were never supposed to be placed as mob farms go against the nature of hte packs
just use gates if you wish to mob farms or endermen farms

**Comment by shruue** [comment]
what mod makes that happen?

**Comment by FlintlockKatze** [comment]
If spawners were never supposed to be placed as mob farms (alot of us make farms for food so like cow and sheep spawners as very helpful) then why are there two mods that give the ability to customize/upgrade spawners? I understand it in a way but we have trouble healing since the basic zombie has 150 health xD

The only problem with the gates, is we need food not blaze or endermen gates, so thats an issue xD Only reason we wish to place spawners is so we can have one farm at spawn for everyone to be able to get meat to make better food.

**Comment by DoctorMage** [comment]
Apotheosis spawner mechanics are completley removed
you cant even place spawners when you get them
and spawner mod literally exist to netuer the how good mob spawners are

when your playing a modpack your playing a curated experience so some mods will exist for certain features and not have all those features in it enabled
