### ISSUE TITLE
[Bug]: FPS drops everytime when loading in new chunks

### ISSUE THREAD

**Issue by F0UDIA** [dr3ams/Roguelike-Adventures-and-Dungeons-2#298]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

SKLauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

Hello there,

I have an i5-4670K and a 1070, and the game on the lowest settings (2 chunks, everything fast/off) still has lag spikes everytime i render in new chunks. is it my cpu that isnt strong enough, or what? I have allocated 8GB to MC, and used these java arguments:
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
yet i still have lag. (If it is indeed my cpu that is too weak, would an i7-4790k do the job?) 
I had the mod distant horizons added to the modpack (which i uninstalled and it didnt change anything).
Please note that i have litterally nothing else running besides Fraps and task manager when playing.

### Steps to reproduce the issue

1. Open the game
2. Open a world
3. Load in
4. Enjoy the framedrops from 120fps to 20fps everytime you render in a chunk

### Additional Information

It isnt crashing but here are my latest logs if it can help.
[2023-05-19-6.log.gz](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11522474/2023-05-19-6.log.gz)

**Comment by DoctorMage** [comment]
Sklauncher has not been tested with the modpack
launchers confirmed to work properly 
Curseforge, Atlauncher, Multimc, Gdlauncher

do you have vysnc on and what is your render distance set to

**Comment by DoctorMage** [comment]
Also the modpack does not play nice with 4 core cpus so your cpu will hold you back
