### ISSUE TITLE
[Suggestion]: Spartan Weaponry compatibility Mods for RAD 2

### ISSUE THREAD

**Issue by Prophet-of-Dew** [dr3ams/Roguelike-Adventures-and-Dungeons-2#299]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Something that was really strange was that there is a compatibility mod for Twilight Forest but not Ice and Fire and Upgraded Netherite. Both are existing mods and are featured in other mod packs. They would add new mid and late-game weapons that fit with the Spartan weaponry. 

I believe these are important because they add diversity in weapons for servers with people in the mid and late game who would like to enjoy the variety of early-game Spartan Weaponry. Upgraded Netherite would expand Spartan Weaponry further into the mid-game and be compatible with its armors. Ice and Fire will extend that same variety to the late game, allowing Spartan Weaponry to be viable for endgame gear. While a Fire DragonSteel weapon might be much stronger than Netherite, the Dreadsteel Scythe is already more powerful. The Scythe has 13.5 more damage (an additional 2 diamond swords worth of damage) and .2 more speed along with the fact it can be thrown for range attacks. 

This increase in weapon variety would be significant for servers that enjoy mid and late-game pvp. Having Spartan weaponry goes to only Netherite and having tons of higher-damage weapons feels like an unprompted end to a great part of the game. Most RPGs have greater variety in their endgame which makes different playstyles unique.

Spartan Weaponry: Ice and Fire
https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry-ice-and-fire

Upgraded Netherite : Spartan Weaponry
https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-spartan-weaponry

**Comment by RecyclingTiger** [comment]
These two especially the ice and fire were suggested a lot before and they are being considered however a ton of balancing and pmmo requirements would have to be made for them
