### ISSUE TITLE
[Bug]: Can't join own Sever with Fresh Sever pack install and Modpack install

### ISSUE THREAD

**Issue by VeganSlimJim** [dr3ams/Roguelike-Adventures-and-Dungeons-2#301]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

Downloaded fresh server pack and fresh modpack install and only messed with EULA and ipproperties to join from separate machine. Currently when joining from separate machine the sever is telling me that the mods are mismatched. Fixes I've tried is that I noted the sever mods folder has 251 mods while modpack mods folder has 271 so copy and pasted 251 mods into my machine that is joining the sever, still says incompatible got to join once but subsequent times did not let me join. Another thing to note is when loading the modpack from seperate machine I see it loads 252 mods when I have only 251 mods in the mod folder.  
![unnamed](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/134154538/05e07ae2-26af-4e9e-9dfe-58d82ccf9cec)
![unnamed (1)](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/134154538/06bee66b-6b36-4989-9943-7067eefd142f)
Pictures is what I see when joining from my separate machine

### Steps to reproduce the issue

Install server pack 
change server properties to IPV4 and EULA agreement to true
Install modpack on separate machine
Join sever from separate machine using public ip address that has port forwarding already set up

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11523084/latest.log)
Only messed with line that had my public IP address

**Comment by DoctorMage** [comment]
ignore the mod mismatch
and server mod count as client will have client side mods that the serverpack does not need

step by step how are you starting the serverpack

**Comment by DoctorMage** [comment]
and does the console show you attempting to join the server when you click join

**Comment by VeganSlimJim** [comment]
> and does the console show you attempting to join the server when you click join

**Comment by VeganSlimJim** [comment]
Running through the steps per your comment
> step by step how are you starting the serverpack
Extract Sever modpack
Change EULA to true
Edit Server.properties to add IPV4
Edit LaunchSever.bat to: java -Xmx5000M -Xms5000M -jar forge-1.16.5-36.2.39.jar
(Just because in my experience my minecraft severs don't recongnize Gig ram sizes but that is different thing entirely)
Run LaunchSever.bat application

With fresh pack install on separate computer I input my public ip address to test connecting
Seems to fail to connect the first time then join the world the second
I did not change anything from what I was previously doing but I can repeatable join and disconnect from my sever now.

Yea maybe it was issue of trying again and again or it works today with fresh sever pack and modpack
