### ISSUE TITLE
[Bug]: R.A.D. 2 Modpack fps dropping to 0 every few seconds

### ISSUE THREAD

**Issue by SlaviBUNBG** [dr3ams/Roguelike-Adventures-and-Dungeons-2#302]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

So I was trying to play the Roguelike Adventures and Dragons 2 Modpack and when I started a new world my fps started to go down to 0 every few seconds. First I though it's like this because the chunks are loading, so I wanted some time for the chunks to load. Sadly after that the problem was not fixed. Every few seconds my fps was going to 0. I tried to change all video settings like graphics and stuff to low, particles to minimal and etc. I also removed the VSync. After that generally I was getting like over 100 fps going all the way to 200 fps. But still, every few seconds the fps was going immediately from 100 fps and above to 0 fps. I allocated a good amount of RAM (I also tried to setting the RAM to the maximum in the CurseForge launcher) but still nothing changed. I don't think its from my RAM because I have a good amount of it. (16GB in total) Down in the Additional Information sector I will post two screenshots of a F3 screen when my fps is high and when its 0. If I need to provide any more information, I will gladly provide it, if I will be able to fix this problem, because I saw other people playing this modpack and they didn't have any problems with it, so I was wondering if there is a way to fix this. Thanks to anyone who will try to help me! :)

P.S. This is happening even when I'm not moving, so I don't think its from chunk loading or anything.

### Additional Information

![2023-05-21_09 10 03](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/134169524/9566acee-50ca-4d56-916a-c4c0ba9fdf7d)
![2023-05-21_09 10 43](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/134169524/dcdea5c6-3394-464c-8d14-3f040b685058)

**Comment by DoctorMage** [comment]
allocate more ram to minecraft 
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/81b81a68-69b4-4468-9d46-67ad08bab806)
the minimum is
6144 
reccomended is
8192
this is if you have 16gb of total system ram
