### ISSUE TITLE
[Bug]: Typo in Scaling Difficulty quest

### ISSUE THREAD

**Issue by GoticeKK** [dr3ams/Roguelike-Adventures-and-Dungeons-2#307]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Minecraft Launcher (Vanilla)

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

There's a typo in quest 'Scaling Difficulty', word difficulty in the description is misspelled. (see additional information)

### Additional Information

![typo](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/122047380/e208e100-82ce-4556-b2f8-b9f356045c58)

**Comment by RecyclingTiger** [comment]
Fixed in next update: 
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/7d1613c6675c8e2b6375cb01b08fc3f9a38f8c61
