### ISSUE TITLE
[Bug]: Unable to connect to server: registry synch failure.

### ISSUE THREAD

**Issue by slitterell** [dr3ams/Roguelike-Adventures-and-Dungeons-2#308]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

Client Error - "Failed to synchronize registry data from server, closing connection" 
Server Error - "[12:15:52] [Netty Epoll Server IO #1/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:item is using 45.6501% of max allowed vanilla size
[12:15:52] [Netty Epoll Server IO #1/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:block is using 28.6947% of max allowed vanilla size"

Server log attached as latest.log A lot of errors but I don't know which ones to be concerned about.
Client log attached as latestclient.log

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11643315/latest.log)
[latestclient.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11643324/latestclient.log)

### Steps to reproduce the issue

1. Downloaded "Server Pack" from Curseforge
2. Move to my Linux server.
3. Edit 'LaunchServer.sh' to be "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xms4g -Xmx16g -jar forge-1.16.5-36.2.39.jar nogui
" Otherwise, the server wouldn't launch because it pointed to the wrong java version for a 1.16.5 Minecraft and "-XX:PermSize=256m" isn't a command for Java 8 and later.
4. Run './LaunchServer.sh'
5. Launch Client and try and connect. 

### Additional Information

Logs attached above.

**Comment by DoctorMage** [comment]
were you able to fix the issue? and which linux is this
