### ISSUE TITLE
[Bug]: Server returns "incomplete tags received from server" error when trying to join 

### ISSUE THREAD

**Issue by Dantehiroki** [dr3ams/Roguelike-Adventures-and-Dungeons-2#31]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.16.5 .05a 

### Describe your issue

> [21:15:50] [main/WARN]: Incomplete server tags, disconnecting. Missing: {minecraft:item=[betterendforge:end_lotus_logs, forge:buckets/empty, betterendforge:lucernia_logs, forge:tools/paxels, betterendforge:hammers, forge:tools/shears, betterendforge:tenanea_logs, forge:dusts/lighting, betterendforge:pythadendron_logs, forge:barrels/wooden, betterendforge:dragon_tree_logs, aquaculture:tackle_box, carrots:barter_tokens, forge:tools/snips, aquaculture:fishing_line, betterendforge:mossy_glowshroom_logs, carrots:happy_foods, forge:tools, vanillafoodpantry:decker_deny_list, betterendforge:furnaces, aquaculture:tooltip, carrots:heads/mobs, betterendforge:helix_tree_logs, carrots:null, aquaculture:bobber, forge:foods/raw_kelp, aquaculture:turtle_edible, vanillafoodpantry:birdy_feed, betterendforge:jellyshroom_logs, betterendforge:umbrella_tree_logs, vanillafoodpantry:livestock_feed, forge:tools/hoes, forge:fillet_knife, vanillafoodpantry:polarbear_feed, betterendforge:lacugrove_logs, carrots:drinkable_potion_bottles, carrots:heads], minecraft:enchantment=[carrots:random_enchants_denylist], minecraft:block=[forge:tnt_like, betterendforge:end_lotus_logs, betterendforge:lucernia_logs, minecraft:dirt_like, forge:ice_like, betterendforge:tenanea_logs, forge:vines, betterendforge:gen_terrain, betterendforge:pythadendron_logs, forge:barrels/wooden, forge:farmland, betterendforge:dragon_tree_logs, forge:sugar_cane, forge:other_bonemealables, minecraft:torches, betterendforge:mossy_glowshroom_logs, forge:cobwebs, forge:large_fungus_stems, minecraft:ladders, darkerdepths:grimestone_replacement, forge:ice_blocks, forge:green_vines, betterendforge:helix_tree_logs, forge:grass, betterendforge:end_ground, carrots:null, forge:cactus, betterendforge:jellyshroom_logs, betterendforge:umbrella_tree_logs, minecraft:magma_like, minecraft:levers, betterendforge:lacugrove_logs], minecraft:fluid=[forge:healing, decorative_blocks:thatch]}

### Steps to reproduce the issue

1. open server, 2. open RAD on curseforge 3. Enter multiplayer, 4. Set up IP, 5. Hit join server (showing active and working), Get error (incomplete server tags returned, contact server owner) 

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9816057/latest.log)

**Comment by DoctorMage** [comment]
Is the server being self hosted or are you using a provider

**Comment by Dantehiroki** [comment]
I was using the server pack provided in the latest release (at the time)
and activating it for self hosting.

**Comment by liamoshaughn** [comment]
Im getting the same issue, using a debian server though. Can't run server through .bat have to run through java command.

**Comment by DoctorMage** [comment]
What java version are you using

**Comment by DoctorMage** [comment]
> Im getting the same issue, using a debian server though. Can't run server through .bat have to run through java command.

can you send the server logs

**Comment by ZenMasterSych** [comment]
Same issue with the same log

**Comment by DoctorMage** [comment]
Can someone send the entire log file please

**Comment by DoctorMage** [comment]
Well until someone sends the log nothing can be done as  only two people have reported this issue send the entire log without joining the server if you care so much about your player id

**Comment by liamoshaughn** [comment]
I figured out why this was happening to me, as I was using linux i couldnt run the .bash and was running the normal server.jar instead of the forge.jar. Running into another issue now but will open another issue
