### ISSUE TITLE
[Bug]: World starts freezing after a few minutes of the game

### ISSUE THREAD

**Issue by Vechar** [dr3ams/Roguelike-Adventures-and-Dungeons-2#314]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

Played for about 40 Minecraft days. Everything worked flawlessly. But now when I join the world I can play only for a few minutes and then the game will freeze. Can't even close it.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11875268/latest.log)
![2023-06-24_14 45 51](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/110311711/99649049-9a73-42b5-b2eb-caf939f1b22f)

**Comment by DoctorMage** [comment]
Late response apologies but did you manage to fix the issue
