### ISSUE TITLE
[Bug]: Hangs then crashes at Forge loading screen.

### ISSUE THREAD

**Issue by Unregisterduser** [dr3ams/Roguelike-Adventures-and-Dungeons-2#316]
### General Info

- [x] I didn't added any mods
- [x] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.4a

### Describe your issue

It specifically hangs at stitching beds.png from the atlas mod.
Forge still monitors memory usage like nothing's wrong, it only crashes on Alt+Tab or Ctrl+Alt+Delete.

### Steps to reproduce the issue

I have both Java 8 and 17 installed for multiple versions of Minecraft.

### Additional Information

[crash-2023-06-30_20.06.38-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11923797/crash-2023-06-30_20.06.38-client.txt)

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11923798/latest.log)

**Comment by ZachAttack4321** [comment]
Seems like this is a known issue on the discord, I'm not super tech savy, but the gist of it is you have too many cores. Exact same issue was reported and resolved a bit ago here (hanging on stitching beds.png):
https://discord.com/channels/512339624627011586/512340728215502878/1098093753257971732
^ link to discussion and fix on the discord.

**Comment by JasonElting** [comment]
just want to post the fix here from the discord, in fml.toml under configs change `maxThreads = -1` to `maxThreads = 1`
I did `maxThreads = 4` and that worked for me aswell
