### ISSUE TITLE
[Bug]: World begins to lag to a crawl after seemingly anything happens

### ISSUE THREAD

**Issue by GlitchPenguin** [dr3ams/Roguelike-Adventures-and-Dungeons-2#319]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.4a

### Describe your issue

Me and my buddies have progressed on this world quite a lot after I got a stage 5 ice dragon and going to a snow biome to get dread shards/ kill necromancers, the server stopped responding and I had to get my friend to restart the server. At first I thought it was an issue with the server but recently my friend stopped hosting a server and instead we play using hamachi, but the same thing still happened. Any blocks I broke didn't drop and I couldn't interact with anything. If I tried loading chunks nothing would happen.

### Steps to reproduce the issue

1. Start game.
2. Go to snow biome or load any chunks
3. Game is no longer responding to blocks breaking

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11928847/latest.log)

**Comment by ZachAttack4321** [comment]
Any chance you could screen record with f3 open when the bug happens? Curious if it's the same issue that's been popping up in the discord the past few days.

**Comment by GlitchPenguin** [comment]
> Any chance you could screen record with f3 open when the bug happens? Curious if it's the same issue that's been popping up in the discord the past few days.

Sure, I'll try tomorrow or today (if I don't forget)

**Comment by GlitchPenguin** [comment]
I tried playing again for a good while, and for some reason the bug isn't happening anymore. I have no clue why it fixed. before this it was bugged for like a week, I guess i'll close this for now, i'll reopen it if I can get a clip of it happening.
