### ISSUE TITLE
[Crash]:  killing a mob cause the world lose

### ISSUE THREAD

**Issue by ThunderZar03** [dr3ams/Roguelike-Adventures-and-Dungeons-2#32]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.5a

### Describe your issue

All perfect, but when i killed an ultimate zombie, in the precise moment he died the world freeze, the game never unlocked and never crashed, when i brute closed the game after an 10 minute of wait and restarded it, the game starded without problem but the world never opened again, when i try to join to it, the world loading reach 100% and freeze to it....this is a little scare, because if i play for 40h and after 40h i lose the world for a zombie.....is a little ugly...for the rest is really beathiful this project.
I think it can be the drop of the zombie, and whatever i can provide the crash report

### Steps to reproduce the issue

killing a ultimate zombie

### Additional Information

[crash-2022-10-21_19.12.49-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9844472/crash-2022-10-21_19.12.49-server.txt)
[crash-2022-10-21_19.27.38-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9844473/crash-2022-10-21_19.27.38-server.txt)
[crash-2022-10-21_18.30.33-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9844474/crash-2022-10-21_18.30.33-server.txt)
[crash-2022-10-21_18.33.54-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9844475/crash-2022-10-21_18.33.54-server.txt)

**Comment by DoctorMage** [comment]
This is an issue with corail and sophsticated backpacks update boths of those mods and it will be fixed

**Comment by dr3ams** [comment]
fixed in 0.6
