### ISSUE TITLE
[Suggestion]: Toms Simple Storage Mod wireless terminal infinite range with Beacon

### ISSUE THREAD

**Issue by fr3dr** [dr3ams/Roguelike-Adventures-and-Dungeons-2#320]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Simple Storage had infinite range, So why not Toms Simple Storage?

**Comment by DoctorMage** [comment]
Not Possible due to how the mod is designed

and infinite storage range goes against the nature of the pack somewhat due to how  it trilivalizes loot storing and dungeon running

**Comment by Janvier123** [comment]
RAD2 Run on MC 1.16.5 and Tom's Simple Storage Mod 1.2.19 is the latest version for MC 1.16.5, the "beacon feature" was not "invented" or added until Tom's Simple Storage Mod 1.3.0 witch runs on MC 1.18.2

https://www.curseforge.com/minecraft/mc-mods/toms-storage/files/3706364
