### ISSUE TITLE
[Suggestion]: Please add spartan weaponary: ice and fire (1.16.5)

### ISSUE THREAD

**Issue by Zhy28** [dr3ams/Roguelike-Adventures-and-Dungeons-2#322]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Please add the "Spartan Weaponary: ice and fire", I add one to the mod pack but the req is too high.

**Comment by DoctorMage** [comment]
Has been rejected multiple times due to how unfairly balanced it is
