### ISSUE TITLE
[Bug]: Failed to start server tried multiple methods to no avail.

### ISSUE THREAD

**Issue by PhonessCS** [dr3ams/Roguelike-Adventures-and-Dungeons-2#324]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.4a

### Describe your issue

I cant start the server I'm not sure if its an issue with java or something I did wrong but any response would greatly be appreciated.
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/139736983/072eb591-a208-4ccf-ae5c-47d431ced5bd)

### Steps to reproduce the issue

start the server...

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12066216/latest.log)

**Comment by DoctorMage** [comment]
You dont have java 8 installed

If your not using java 18 for anything uninstall it and install java 8 64 bit
