### ISSUE TITLE
[Bug]: Crashing on game start

### ISSUE THREAD

**Issue by WobbyChip** [dr3ams/Roguelike-Adventures-and-Dungeons-2#327]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

TLauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

36.2.39

### Describe your issue

Just downloaded modpack and it doesn't work. It just crashes whenever I try to start a game. I even gave it 32GB, but I guess it was not a memory issue.

### Steps to reproduce the issue

1. Instal modpack in TLauncher
2. Start the game.

### Additional Information

[crash-2023-07-25_23.28.30-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12165401/crash-2023-07-25_23.28.30-client.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12165404/latest.log)

**Comment by DoctorMage** [comment]
Tlauncher is unsupported due to modifying modpacks on there end and a plethora of other reasons

if you legally own mc there is no reason to be using that launcher unless you like malware
