### ISSUE TITLE
[Bug]: Game crashes when attempting to load a singleplayer world.

### ISSUE THREAD

**Issue by MommaDragon** [dr3ams/Roguelike-Adventures-and-Dungeons-2#328]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Starting up the game itself is fine, but loading into the world almost instantaneously crashes it. Repeated three times.
The first tip displays, then the map loading square, then crash seconds after the square (of doom).

This problem just started _today,_ and not last night - if that helps with anything.

### Steps to reproduce the issue

1. Install on CurseForge (well, okay, have re-installed it after Cyclic Redundancy Check error, and move your save back in)
2. Go into the game, as normal
3. Load up your world
4. The game crashes

### Additional Information

[crash-2023-07-26_08.58.46-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12172669/crash-2023-07-26_08.58.46-server.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12172667/latest.log)

If you're looking for the crash text:

> The game crashed whilst exception in server tick loop
> Error: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 17 path $

**Comment by DoctorMage** [comment]
was this world ever opened to lan

**Comment by MommaDragon** [comment]
Nope. Never.

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/232#issuecomment-1648752133

Try this only slgiht issue would be world name as singleplayer cant have two worlds of the same name

can always just move the broken world out of the saves folder

make sure to backup the world beforehand

**Comment by MommaDragon** [comment]
Only ever had *one* world, to be honest. Though, there were some related problems in a different modpack... except, its case was freezing.

That was a corrupt _folder_, at that time. It seems that, after doing a disk scan and repair, and reinstalling the modpack, the problem was fixed...? At least, it seems like it's fixed. Maybe it was trying to read a corrupt file from the save and, instead of a freeze, it was going to a crash and saying "malformed line" as some form of code was broke.

Should this be closed, then?

**Comment by DoctorMage** [comment]
As long as the issue is fixed then yes report will be closed
