### ISSUE TITLE
[Bug]: incompatible fml modded server

### ISSUE THREAD

**Issue by ThisIsKetts** [dr3ams/Roguelike-Adventures-and-Dungeons-2#329]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curse Forge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Just installed the mod pack to run on a server, when going to join it says incompatible fml modded server, I can still join, but not too sure why this issue is showing

### Steps to reproduce the issue

Have reinstalled a new version on the server aswell as the modpck through curse forge and still getting the same issue. Not to sure if its my end or an issue with the modpack

### Additional Information

https://1drv.ms/u/s!AqGRMA-lK_-nhbUAxwOQlHxtrsI85Q?e=QthAeP

link to debug log

**Comment by DoctorMage** [comment]
How is the server being hosted

if your using the red x to determine if you can join a server or not
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/f675b311-487e-4b54-978a-70dec5ebb6fa)

DONT forge does not have a check for purely client side mods so some modpacks will always have it appear the only way to confirm you cant join a server is by joining it
