### ISSUE TITLE
[Bug]: Repeating 3 Second Speed Boost

### ISSUE THREAD

**Issue by PixieNinja23** [dr3ams/Roguelike-Adventures-and-Dungeons-2#33]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.5a

### Describe your issue

I have a 3 second speed boost which activates every 3 seconds, which results in my view zooming in a little every 3 time it activates.

How can I disable this? I'd rather go without the speed boost if I can stop the constant zooming.

Only recently started the game, no equipment causing the speed boost.

### Steps to reproduce the issue

1) Do anything/nothing.
2) Screen zooms in a little then back out every 3-4 seconds.

### Additional Information

-

**Comment by dr3ams** [comment]
Did you also checked all curious slots?

**Comment by PixieNinja23** [comment]
Yes, only have the charm you start the game with that gives you a swimming boost.

Started a test world, and it seems to kick in once you've levelled agility in Project MMO.

**Comment by PixieNinja23** [comment]
Further update;

It's definitely Project MMO.

It's a biome boost, and was present for me in a plains biome. The speed boost should update before it runs out, but for me it drops for a split second then is reinstated.

I've filed it as a bug on Project MMO, but it's previously been raised with them and then closed assuming it's down to server lag, when it doesn't seem to be.

**Comment by dr3ams** [comment]
Interesting. 
For the next update I'll completely disable positive/negative effects for biomes because I encountered an issue like that but with slowness and weakness. 
They're focused on more recent versions of PMMO and MC so probably it won't be fixed.
