### ISSUE TITLE
[Bug]: Health bar keeps getting cut short after dying

### ISSUE THREAD

**Issue by UNSTABLEDAYZ** [dr3ams/Roguelike-Adventures-and-Dungeons-2#330]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.4a

### Describe your issue

After playing the modpack for a bit, I ran into the problem after dying to a bunch of mobs. My health bar had only 5 and half hearts, at first i thought it was some sort of curse or mechanic from one of the mods that I wasn't aware of, but after researching nothing came up whatsoever. I would die within two hits of anything so the game obviously counts those as my only hearts. I've found exiting the world and loading it again fixes it, but I die so often its very annoying.
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/128583992/bbb998fc-1bdb-4ecd-bf31-28e2a764f1d9)

### Steps to reproduce the issue

1. Load up a world
2. Get killed with a command or mob

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12271185/latest.log)

**Comment by ScriptAero** [comment]
Are you using seven curses, are you wearing broken heart charm, do you have deaths odium on any gear whatsoever

**Comment by DoctorMage** [comment]
Pay attention to the curses on your gear
and what you equip

You most likely either have somehting enchanted with death's odium or ring of seven curses

**Comment by DoctorMage** [comment]
How to remove Health lost by Death's Odium:
- Get yourself 2 Cookies
- Enchant both with Death's Odium
- hold both in stack in your main hand
- eat 1 of them
