### ISSUE TITLE
[Bug]: Shield won't function properly

### ISSUE THREAD

**Issue by OriZeria** [dr3ams/Roguelike-Adventures-and-Dungeons-2#331]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.5

### Describe your issue

Whenever I try to use a vanilla shield (including with modded enchantments etc) the shield will play the animation of equiping instead, just blinking without actually being used. I'm not sure if this bug works on other shields, but the vanilla shield just doesn't work. There aren't any requirements to use it listed.

### Steps to reproduce the issue

Just try to use a shield, for me it doesn't work and just blinks.

### Additional Information

N/A, no crash

**Comment by DoctorMage** [comment]
Did you add any mods or make any changes to the modpack?
