### ISSUE TITLE
[Bug]: Combining STACKED enchanted books... creates an error item?

### ISSUE THREAD

**Issue by MommaDragon** [dr3ams/Roguelike-Adventures-and-Dungeons-2#337]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

Check "additional information" for the screenshot showing exactly what is going on.

The book enchantments don't matter; it just has to involve stacked books (why can you stack enchantments?)... and the FIRST item has to be stacked.

This is not a crash - it's entirely item-based. Probably just a bug because of enchantments being allowed to stack, though... probably just how the game can't handle things too well and KubeJS having to "step in."

### Steps to reproduce the issue

1. Make your anvil and books (that you probably found)
2. Attempt to put a stack in the first slot and any amount of books in the second slot
3. KubeJS complains.
4. Do the same, but 1 book to (at least) 2 books.
5. The extra book is strangely missing, resulting in... otherwise normal enchanted book.

### Additional Information

![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/106483611/5e10b42d-d999-4d71-96c3-f8815a5eb934)

Stack of 2 being added to 1.

![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/106483611/e33f48e9-8a6a-463f-a99e-0c69092cd62d)

Stack of 1 being added to 2. Two stack is level 2 enchantment, resulting in... level 2 enchantment.

It's extremely niche.

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12424440/latest.log)

Latest.log, if (really) necessary.

**Comment by DoctorMage** [comment]
This is intended to prevent dupes/ deleting books

vanilla only supports 1 book

books stacking is a qol of life feature added to the modpack

**Comment by DoctorMage** [comment]
my bad
bottom image should not be possible 

only one book can be applied at a time this will be fixed next update

anymore can void excess books or lead to dupe

**Comment by Zarchyar** [comment]
Updated script to "fix" this for the next update
