### ISSUE TITLE
[Bug]: Shop crash and I cant see my coins when my cursor is on it

### ISSUE THREAD

**Issue by StaiMeer** [dr3ams/Roguelike-Adventures-and-Dungeons-2#338]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

I play with Friend on a server that is offline because I have the purchased version but he does not have the purchased version of mc. The strange thing is that his shop works but my shop doesn't. When I click on it, it doesn't even show how much money I have and when I click on it, the game stops for 1 second and a screen appears where Saving World is written and the game crashes into the launcher. Where does it show an error message, Error -1 The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

### Steps to reproduce the issue

1. Open quest book (in multiplayer) 2. Go to the right corner 3. Click on shop icon 4. Boom, Game crash

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12438810/latest.log)

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/wiki/Common-Issues#clicking-on-shop-crashes
