### ISSUE TITLE
[Suggestion]: Prehistoric Fauna

### ISSUE THREAD

**Issue by gdawg1006** [dr3ams/Roguelike-Adventures-and-Dungeons-2#339]
### General Info

- [X] I would like to propose new mod
- [X] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I think this mod would be a cool thing to add as it allows us to make museums, adds a new boss, and 3 new dimensions. One thing you could add is a dinoslayer title for killing every dinosaur. There’s also the prehistoric delight which adds support to farmers delight

**Comment by DoctorMage** [comment]
mcreator mods are an instant no to little configurabillity and to many issues
