### ISSUE TITLE
[Suggestion]: emblem not in baubles

### ISSUE THREAD

**Issue by BattleZone1999** [dr3ams/Roguelike-Adventures-and-Dungeons-2#340]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

the mod that offers specializations give an emblem for your class and now it is unusable unless in offhand and it kinda makes your class useless one of the things me and my buddies really liked about this pack and i just would like a spot for it again

**Comment by DoctorMage** [comment]
theres an emblem slot in curios thats were it goes boost are still applied

**Comment by Arsenic-Soap** [comment]
Apparently it seems like the emblem slot exists when in Singleplayer. But when in Multiplayer on a server, it is not there.

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/af993a2c-66e9-401f-9b0f-ae01211b4db9)

**Comment by DoctorMage** [comment]
that only occurs if the server was updated from an older version of the modpack then the server config needs to be reset

**Comment by Arsenic-Soap** [comment]
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/19756163/1a07e475-66cd-400a-b175-7ff11f850cb2)
I have tried resetting the configs for the server, but still the emblem slot and the cursed ring slot do not exist. ive looked in the config and it says that they are there, they just arent showing up in game.

**Comment by DoctorMage** [comment]
does it show in default configs folder for emblem option?
does it show in server configs for emblem existing if so its a server provider issue

**Comment by Arsenic-Soap** [comment]
The server config was empty for curios, so i put in all the proper information. But after a server reset, it proceeded to delete all the information in the server config that i had just changed. Any suggestions? or should i just try to contact the server provider?

**Comment by DoctorMage** [comment]
you also are making the server is turned off when making file changes?

**Comment by Arsenic-Soap** [comment]
Fixed it! Server said it was off, but apparently was not fully shutdown. Thanks. 
Half asleep and a little too hasty, but we got to it in the end, Thanks again
