### ISSUE TITLE
[Suggestion]: How to transfer skills, etc. files

### ISSUE THREAD

**Issue by xperternier** [dr3ams/Roguelike-Adventures-and-Dungeons-2#341]
### General Info

- [ ] I would like to propose new mod
- [X] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Originally, online mode was turned on, but the friend is not genuine, all turned off.
Please tell me how to transfer skill level and fb mission files to another person
THANKS

**Comment by DoctorMage** [comment]
join the discord and look at this thread https://discord.com/channels/512339624627011586/1066364160809644123
