### ISSUE TITLE
[Bug]: Ice and Fire Dragon Roosts/Caves/Skeletons generating incorrectly.

### ISSUE THREAD

**Issue by Cheesedoghotdog** [dr3ams/Roguelike-Adventures-and-Dungeons-2#344]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

I've tried everything, but roosts, caves, and skeletons from Ice and Fire just don't generate! In any biome! I know this is a problem with the mod on newer versions, but I didn't expect it to be an issue in this modpack. I've tried editing configs to enable dragon spawning, but that has proved fruitless.

### Steps to reproduce the issue

1. Open a world.
2. Look around.
3. Try changing the config file and repeat.

### Additional Information

No crash report.

**Comment by DoctorMage** [comment]
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/04bd5b52-bc15-4cdc-bd46-8c9d90e300f0)

did oyu make any changes to the modpack add any mods or remove any?

skeletons have been disabled for a long time https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/blob/main/config/iceandfire-common.toml
