### ISSUE TITLE
[Bug]: ProjectMMO is not loading correctly

### ISSUE THREAD

**Issue by Jamflof** [dr3ams/Roguelike-Adventures-and-Dungeons-2#345]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Not Applicable, downloaded server pack and am running manually

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

serverpack 1.6

### Describe your issue

Attempting to launch the server, ProjectMMO does not load correctly.

### Steps to reproduce the issue

Step 1: run start.bat
Step 2: wait for it to load
Step 3: server crashes without loading

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12709259/latest.log)
[crash-2023-09-24_13.23.20-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12709260/crash-2023-09-24_13.23.20-fml.txt)

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58#issuecomment-1328237062
