### ISSUE TITLE
[Bug]: Twilight Portal not working

### ISSUE THREAD

**Issue by Robert12432** [dr3ams/Roguelike-Adventures-and-Dungeons-2#346]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

After creating the twilight forest portal i am unable to go through. Unsure why as the portal is created but when me or other players on the server try to go through it wont let us.

### Additional Information

No crashes just wont let us through

**Comment by DoctorMage** [comment]
how is the server being hosted?

does /forge dimension tp work
(forgot the exact command)

do other portals work

does it only work if one player is online?

**Comment by Robert12432** [comment]
Server is hosted on my home pc. After restarting the servers few times it
started working. I have no clue what was going on. Other portals did work
such as the nether  it just wouldn't let us is through to the twilight.
Everything seems to be working now though and I'm sorry to bother you.
