### ISSUE TITLE
[Bug]: Open crash

### ISSUE THREAD

**Issue by Battleboy96** [dr3ams/Roguelike-Adventures-and-Dungeons-2#347]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

SKlauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.6

### Describe your issue

When i try and open the game with the launcher above, it tries to load but the game window doesn't even open and I get the latest.log file attached below.    
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12732222/latest.log)

### Steps to reproduce the issue

I think this may be caused by my device but here are the steps. 

1. Open SKlauncher
2. Find the modpack (download it if not already)
3. Click play
4. Wait around 20 seconds 

### Additional Information

URL for latest.log
https://mclo.gs/UCNdcdv

**Comment by DoctorMage** [comment]
sklauncher is unsupported due to allowing the game to be played without owning an offical mojang account

please use a supported launcher like curseforge

**Comment by Battleboy96** [comment]
ok the problem has resolved itself anyway
