### ISSUE TITLE
[Bug]: Problem with server, usage 150% of CPU

### ISSUE THREAD

**Issue by Cubeplayer99** [dr3ams/Roguelike-Adventures-and-Dungeons-2#348]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

HI,
I have problem with server based on 1.7 RAD 2 modpack, everything was good until now, cmd give comms like this every few seconds and usage for CPU is 150%, and after player Arti leaves CPU usage drops to 80-90%
Im not experienced server admin so sorry if I waste your time but I hope Im gonna get some answers that help.

[Server thread/INFO] [radenchants/]: (xArtii) has prevented spawn of Mob (Zombie) chunkX: 729 / chunkZ: -64 / Pos [BlockPos{x=11679, y=33, z=-1017}] / Radius (4)

[Netty Epoll Server IO #0/WARN] [co.co.Connectivity/]: Login payload for Registry minecraft:item is using 45.7369% of max allowed vanilla size

[Server thread/INFO] [randompatches/]: Changing UUID of duplicate entity blue_skies:gatekeeper from e42b9d8d-bd1c-4e52-9f62-8218f21a27c0 to 783fac61-1216-482a-aed9-c73cc93345d9

[Worker-Main-13/WARN] [ModernFix/]: The namespace dungeons_plus contains an outdated structure file, which can cause worldgen lag. Please view debug.log for the full filename, determine which mod provides the structure, and report to the mod/datapack author, including the debug log.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/12835626/latest.log)

**Comment by DoctorMage** [comment]
server specs

cpu model
total ram

**Comment by Cubeplayer99** [comment]
CPU 5 x 4300 Mhz
Ram 10 Gb ddr4 2666Mhz

**Comment by DoctorMage** [comment]
Apologies for the very late response.

is a dedicated server or self hosting and were any mods added or pregen done?
