### ISSUE TITLE
[Bug]: Magic mirror no working

### ISSUE THREAD

**Issue by Renegod64** [dr3ams/Roguelike-Adventures-and-Dungeons-2#349]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curse forge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

I cant use the magic mirror no matter how many levels i have or anything. tried in another world aswell and still cant get it to work.

### Additional Information

Does not crash just wont use the magic mirror

**Comment by ScriptAero** [comment]
If its the circular magic mirror you have to hold right click and it doesn't work cross dimensions it will be rather slow
