### ISSUE TITLE
[Bug]: modpack makes minecraft use 98% of my AMD Ryzen 9 7945HX CPU

### ISSUE THREAD

**Issue by jack652** [dr3ams/Roguelike-Adventures-and-Dungeons-2#350]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

RAD2 - 1.7 [MC1.16.5]

### Describe your issue

when playing this modpack minecraft use 98% of my CPU, making the gane unplayable because I have 0 FPS, slideshow moment
<img width="335" alt="image" src="https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/48365199/28f82ef4-1239-4b75-8f74-fc8bce944272">

### Steps to reproduce the issue

1. launch modpack
2. launch a world

### Additional Information

Processor	AMD Ryzen 9 7945HX with Radeon Graphics, 2501 Mhz, 16 Core(s), 32 Logical Processor(s)

**Comment by DoctorMage** [comment]
what gpu exactly and how much total ram

also having 
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/115cff11-e839-427e-8a9b-84736539d748)
the actual core usage is much more useful than overrall usage

**Comment by DoctorMage** [comment]
also first time playing the modpack or played it before? as well as does it take time for this to occur

**Comment by jack652** [comment]
first time trying the modpack
ram 32GB
GPU NVIDIA GeForce RTX 4070 Laptop GPU
here's the cpu usage with the logical processor graph
<img width="485" alt="image" src="https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/48365199/61879d54-c0b6-4430-9ba3-6b2bf99b4f43">

**Comment by DoctorMage** [comment]
next time you record can you have the f3 menu up

**Comment by DoctorMage** [comment]
also have nothing running in the background other than whatever your using to screen record, task manager and mc/curseforge

best scenario after restarting your pc
