### ISSUE TITLE
[Bug]: blessed blade enchanted disappearing

### ISSUE THREAD

**Issue by banzpopto** [dr3ams/Roguelike-Adventures-and-Dungeons-2#351]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

cureforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

blessed blade did disappearing when i enchanted to item or any weapon even use commend to test enchanted blessed blade is still disappear

### Additional Information

nothing else

**Comment by DoctorMage** [comment]
you have to obtain it via apex enchanting https://github.com/TinyModularThings/UniqueEnchantments/wiki/Apex-Module-%5C-Addon

**Comment by DoctorMage** [comment]
to elaborate the enchant will remove itself if its not applied via the apex enchanting method
