### ISSUE TITLE
[Bug]: Grave Key does not Teleport to grave anymkore

### ISSUE THREAD

**Issue by michaelhieu** [dr3ams/Roguelike-Adventures-and-Dungeons-2#352]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

Grave Key is no longer teleporting us to our graves, but it does work to access tombstone. It was working fine from when we started the modpack until just recently today. I don't know if it is a bug or if it is a part of the game. Please inform. 

### Steps to reproduce the issue

1. Dying from anything
2. Respawned with Grave Key
3. Holding Right Click to Teleport to Grave
4. Nothing Happens

### Additional Information

[2023-11-05-5.log.gz](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/13263151/2023-11-05-5.log.gz)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/13263153/latest.log)

**Comment by DoctorMage** [comment]
are you sure its an actual enchanted grave key check for the enchantment glint

during halloween all keys by default were enchanted

**Comment by michaelhieu** [comment]
On the key itself, it says right click on grave soul for teleportation. before the most recent Sunday, we have been able to do just that. Unless we were interpreting grave souls incorrectly, I will try to test more things out then with this.
