### ISSUE TITLE
[Bug]: Twilight Forest Progression Bugs

### ISSUE THREAD

**Issue by Saulnocap** [dr3ams/Roguelike-Adventures-and-Dungeons-2#356]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

TLauncher, Mojang Launcher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

A bug is happening to me and my partners with the modpack, we have not access to progression on the Twilight Forest, after I defeated both, Litch and Naga, it doesn't open up the map to go ahead with the MushroomTaurus or the Shadow Knight, nor any other boss, We're not able to have a progression on the mod, please advise

### Steps to reproduce the issue

1. Go to the multiplayer world
2. Create portal, hop in the Twilight
3. Defeat Naga and Litch
4. Issue found, Biomes not opening up in the Twilight Dimension:  (Swamp and Dark Forest)

### Additional Information

No crash reports
![2023-11-12_20 21 06](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/129406876/9dfb25f0-ee78-4fd6-a73d-7c88bde834ab)
![2023-11-12_20 22 41](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/129406876/c7e18224-7026-4588-ad5e-a53519560563)

**Comment by DoctorMage** [comment]
If you legally own the game

use an actual launcher (easiest being curseforge https://www.curseforge.com/download/app)

not one that installs malware and keyloggers onto your sytem

mojang launcher is not made for large modpacks or modpacks in general don't try its not worth the headache
