### ISSUE TITLE
[Bug]: Just Enough Resources not working

### ISSUE THREAD

**Issue by SuperFurias** [dr3ams/Roguelike-Adventures-and-Dungeons-2#358]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

FTBApp

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

Just like the title says, the Just Enough Resources is pretty much useless inside the modpack, because every single category it adds, is hidden in the config under hidden tabs. and i am trying really hard to understand why.
The just enough resouces mod adds 4 or 5 new categories. but each of them in this modpack is.. hidden. i didn't like it, so i restored the mod to its default settings, and in single player works without any problem. but now the issue is in the server i am hosting. because the mod doesn't work in the server.
i tried everything i could to make it work, but the Just Enough Resources is not even a mod present in the server pack, there is only jei in it. so i don't really understand why this happens. i need the Just Enough Resources to work inside my server, because its useful.

### Steps to reproduce the issue

open modpack, open mods list, open Just Enough Resources settings, reset the category "Hidden Tabs" and restart the game. play single player, works, play multiplayer, it doesn't work. (not LAN, multiplayer)

### Additional Information

I don't know what logs to provide. its just the mod not working in multiplayer and working perfectly fine in single player.

**Comment by ScriptAero** [comment]
Upon review it seems like this mod isnt left in intentionally, it wont properly display the things it was meant to
