### ISSUE TITLE
[Bug]: Glyph Press Crashing

### ISSUE THREAD

**Issue by Treygon** [dr3ams/Roguelike-Adventures-and-Dungeons-2#36]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.6

### Describe your issue

Whenever anyone tries using a glyph press, them and anyone near them crashes.

### Steps to reproduce the issue

On the glyph press, right click with magical clay, then right click with a proper material like cobweb. After that, it crashes, and the materials used disappear, along with the source amount used.

### Additional Information

`
[crash-2022-10-26_16.27.01-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9873615/crash-2022-10-26_16.27.01-client.txt)
`

**Comment by dr3ams** [comment]
![2022-10-30_13 33 14](https://user-images.githubusercontent.com/7347489/198876091-30c79390-6db5-4a3e-9bac-5f62a6f27b1c.png)
![2022-10-30_13 33 22](https://user-images.githubusercontent.com/7347489/198876092-79accef5-5d3b-4218-b6e6-9f4df5f28797.png)
![2022-10-30_13 33 27](https://user-images.githubusercontent.com/7347489/198876095-e71a2cd2-5913-4a9a-bd39-23c2a90610d5.png)
![2022-10-30_13 33 33](https://user-images.githubusercontent.com/7347489/198876097-4e014774-1584-4e38-b053-ed27ff1312af.png)

**Comment by dr3ams** [comment]
Works for me. Provide latest.log located in your logs folder.
