### ISSUE TITLE
[Bug]: Unable to craft buddy card displays

### ISSUE THREAD

**Issue by ick49** [dr3ams/Roguelike-Adventures-and-Dungeons-2#361]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.8

### Describe your issue

I am unable to craft the buddy card displays, I am able to see the items via JEI but it has no recipe. I am able to use them and place them down in creative however I can not craft them. 

I apologize if they were disabled for a known bug or some other reason I was unable to find anything related to this problem other than one post where one person had the same issue and it was unresolved.

Thank you for your time

### Additional Information

![Creative buddy](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/153573387/0f2a4d45-61b2-4ec8-8ba5-4cd4b28b475b)
![card display](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/153573387/ab7e7ed5-dfc2-4d22-8ffc-25bd5bb6e05e)
![crafting card display](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/153573387/787b5151-b878-47d8-917e-76a908a8f4e2)

**Comment by RecyclingTiger** [comment]
The card displays being disabled is intentional. I'll remove them from JEI next update
