### ISSUE TITLE
[Bug]: Sleeping Doesn't Move To Sunrise In Tropicraft

### ISSUE THREAD

**Issue by Ibadca** [dr3ams/Roguelike-Adventures-and-Dungeons-2#362]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [x] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.7

### Describe your issue

In both single and multiplayer games, attempting to sleep after entering the tropicraft realm does not advance the  player to the next morning. The bed does create a respawn point for the player, and the player character lies down as if to sleep. This also occurs with the Comforts sleeping bag (not creating a spawn point, as intended). In multiplayer, A player in the overworld can sleep to cause the night to pass in the Tropicraft realm.

### Steps to reproduce the issue

1. At sunset on a beach in the overworld, sit in a Tropicraft chair and drink a piña colada, which will teleport you to the Tropicraft realm.
2. Place a bed or a Comforts sleeping bag down on a surface.
3. Right click with the mouse on the bed or sleeping bag at night to use it.
4. Observe results.

### Additional Information

Only the Comforts sleeping bag was tried in multiplayer. Both the minecraft bed and the comforts sleeping bag were tried in singleplayer.

**Comment by Ibadca** [comment]
Updated to 1.8. Still not working in single player.

**Comment by RecyclingTiger** [comment]
This might be intentional since it also occurs in other dimensions like atum.
These dimensions day/night cycles are synchronized with the overworld though so sleeping in the overworld will make other dimensions also move to sunrise
