### ISSUE TITLE
[Bug]: incompatible fml modded server

### ISSUE THREAD

**Issue by darkerraven** [dr3ams/Roguelike-Adventures-and-Dungeons-2#364]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

prism launcher 

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.8 

### Describe your issue

this thing 
![javaw_PQFTCCOXZ2](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/115076107/b6be2c94-ec6c-4840-94b4-988d293796d0)

### Steps to reproduce the issue

launch Roguelike Adventures and Dungeons 2 on prism launcher and start the server from curseforge Server Packs I downloaded from this link https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2/files/4919910 that's it 

### Additional Information

I don't have anything yet

**Comment by RecyclingTiger** [comment]
This is not a bug
The server can still be joined, all rad2 servers have this
mainly has to do with the server not having client mods which is intentional as servers don't need them
