### ISSUE TITLE
[Bug]: Heal can't be augmented with Extend Time, even though it says it can (Unsure if log is needed)

### ISSUE THREAD

**Issue by pontorka** [dr3ams/Roguelike-Adventures-and-Dungeons-2#366]
### General Info

- [ ] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.8

### Describe your issue

As the title says. When creating a Self Heal spell with Ars Nouveau spellbook it says that Heal cannot be augmented with Extend Time, even though Heal Itself says otherwise. (If this is an added feature and was written somewhere I'm sorry I'm dumb XD).

### Additional Information

https://imgur.com/a/9xRPAas

**Comment by ScriptAero** [comment]
This is an intentional change, it was way too abusable and we chose to remove that instead of nerfing extend time as a whole.
