### ISSUE TITLE
[Suggestion]: Nomadic Tents Mod

### ISSUE THREAD

**Issue by SQbuilder** [dr3ams/Roguelike-Adventures-and-Dungeons-2#37]
### General Info

- [x] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

https://www.curseforge.com/minecraft/mc-mods/nomadic-tents

These tents are essentially upgradeable pocket dimensions. Encourages the nomadic playstyle. Recipe tweaks may be needed for balancing?

**Comment by VanyaBaou** [comment]
Bag of Yurting is already in the pack and serves the same purpose
