### ISSUE TITLE
[Bug]: Mods(253) propieties ALL FALSE

### ISSUE THREAD

**Issue by ImGeiBriel** [dr3ams/Roguelike-Adventures-and-Dungeons-2#370]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Forge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.9

### Describe your issue

All structure mods such as ice and fire, Ores etc are in False therefore they are not generated when downloading the Server Pack

### Additional Information

SErver

**Comment by DoctorMage** [comment]
Late response

But how is the server being hosted
Provider or self

if self hosting what operating system

what java version is hte server using 

step by step how did you setup the server
