### ISSUE TITLE
[Bug]: fps drop

### ISSUE THREAD

**Issue by alaoui1235** [dr3ams/Roguelike-Adventures-and-Dungeons-2#374]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

prisme

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.9

### Describe your issue

fps drops to 0 every few seconds

### Additional Information

[Uploading latest.log…]()

**Comment by RecyclingTiger** [comment]
How much RAM did you allocate to the pack? Having too much can cause frame drops

**Comment by alaoui1235** [comment]
> How much RAM did you allocate to the pack? Having too much can cause frame drops

4 gb
My pc specs : intel i5 g7 gen11
8gb of ram
Intel iris xe 
Thanks for helping
