### ISSUE TITLE
[Bug]: Cannot use Restock backpack upgrade on lootr chests.

### ISSUE THREAD

**Issue by VoidTyrant** [dr3ams/Roguelike-Adventures-and-Dungeons-2#375]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.9

### Describe your issue

I got the restock upgrade (sophisticated backpacks) which let's me shift right-click to obtain items from chests, but it doesn't work on the Lootr chests. It just places the backpack down every time I try to do so. It appears to work with all other containers though. The problem also occurs with the deposit upgrade and the Lootr chests. 

### Steps to reproduce the issue

1. Get backpack with Restock Upgrade. 
2. Test withdrawing items from regular chest. 
3. Try the same with Lootr chest.

### Additional Information

Maybe has something to do with lootr having its own shift right-click function?[
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/14475798/latest.log)
](url)

**Comment by RecyclingTiger** [comment]
This is because lootr uses a different storage system than most chests; similar to the ender chest the items in the chest are unique to each player so blocks like hoppers and the backpack can't extract from them.
