### ISSUE TITLE
[Bug]: Crash when accessing shop in SINGLE-PLAYER

### ISSUE THREAD

**Issue by recapgit** [dr3ams/Roguelike-Adventures-and-Dungeons-2#377]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

SKlauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.9, and now 1.10a

### Describe your issue

The game crashes everytime I enter my single-player world and try to enter the shop, also I can't see how many coins I have. Also, in other world that I had, I COULD enter the shop but the coins were always empty, even if i completed a quest and then entered the shop, there would be 0 coins.

### Steps to reproduce the issue

1. Enter the world
2. Go to quests
3. Click to enter the shop in top right corner
4. Crash

### Additional Information

[crash-2024-03-16_14.19.06-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/14624668/crash-2024-03-16_14.19.06-client.txt)
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/14624672/latest.log)

**Comment by Gunner76th** [comment]
The use of cracked/pirated/illegal launchers is not supported.  If you do not legally own minecraft you will be required to legally purchase minecraft and use a legal launcher to receive support.  Approved launchers are as follows:
Curseforge 
ATLauncher
GDLauncher
PrismMC 
FTB Launcher

No further support for this issue will be provided.
