### ISSUE TITLE
[Suggestion]: PMMO 1.0E7 XP gain

### ISSUE THREAD

**Issue by UndeadPlays** [dr3ams/Roguelike-Adventures-and-Dungeons-2#379]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I'm in a server setting so balancing features like 1.0E7 XP gain from a single quest seems to be more of a bug than a feature - Servers only been open for aprox 70HR. I'll provide what each players original level and after level of claiming a few quests in this example Endurance.

Your launcher
Curseforge

Modpack version (Do not say latest check curseforge has it on modpacks icon)
1.10a

Describe your issue 
Holy Grail, Witherite Shield, Diamond Brooch, Mark Of The Champion, and Full Witherite armor set. Is it possible to maybe reduce/remove the minimal 200xp that it gives you to claim those Pathfinder quests since FTBquests boosts PMMO XP gain? From my understanding (I asked in the discord) that since it's FTBquests rewarding it - it's further boosted resulting in nearly a billion of XP gain off 200? Is this a fully intended feature to be able to max all your PMMO that way? 

Steps to reproduce the issue
See above - Equip and claim any of the Pathfinder quests. 

Additional Information:

Before :
Player #1
Level 37
Player #2
Level 56

After :
Player #1
Level 127
Player #2
Level 117

(apologize for incorrect format before)

<img width="342" alt="Screenshot_20" src="https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/35238013/213840d4-91bc-4475-a307-6dd6a06b617e">

**Comment by dr3ams** [comment]
Not intended. Is this only related to Pathfinder quests?

**Comment by dr3ams** [comment]
revised and adjusted in https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/7b781e04c1084235feec939ea00a1a9014e3d22e

Sorry for any inconveniences!

**Comment by UndeadPlays** [comment]
So it seems pretty much anything related to receiving PMMO XP from quests can be abused this way - Even the mob coin for example.

**Comment by ScriptAero** [comment]
Changed in 1.11
