### ISSUE TITLE
[Bug]: Project_MMO-1.16.5-3.67.6 faile 

### ISSUE THREAD

**Issue by hightimes76** [dr3ams/Roguelike-Adventures-and-Dungeons-2#382]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.11

### Describe your issue

I have integrated the modpack into our Nitrado portfolio.  After starting, the server crashes when loading Project_MMO 3.67.6.

I tried to start with Java 11 & 8, nothing happens. After checking the latest version of Project_MMO for 1.16.5, I uploaded mod version 3.69.0. With this version the server starts correctly.

### Steps to reproduce the issue

1. Install Modpack via Modpack Chooser on Nitrado
2. Wait some Seconds, the Server is crashing and creates a Crash Report
3. Check the Crash-report and you can see the Mod Project MMO (pmmo) has failed to load correctly

### Additional Information

Crash-Report with Project_MMO 3.67.6
[crash-2024-06-07_07.15.12-fml.txt](https://github.com/user-attachments/files/15721912/crash-2024-06-07_07.15.12-fml.txt)

Serverlog with Project_MMO 3.67.6 
[2024-06-07-2.log](https://github.com/user-attachments/files/15721907/2024-06-07-2.log)

Debuglog with Project_MMO 3.67.6 
[debug-1.log](https://github.com/user-attachments/files/15721948/debug-1.log)

Serverlog with Project_MMO 3.69.0
[latest.log](https://github.com/user-attachments/files/15721926/latest.log)

Debuglog with Project_MMO 3.69.0
[debug.log](https://github.com/user-attachments/files/15721970/debug.log)

**Comment by Gunner76th** [comment]
Your problem is sure to Nitrado use Java 11. Once your server is set to use Java 11 you can't change it to Java 8. This is a fault with Nitrado and is a reason why we no longer recommend or support them as a minecraft host provider.  

Also you shouldn't go changing mod versions,  especially PMMO.

**Comment by hightimes76** [comment]
Well I also tried it on my own Root server, same problem but thanks then we will take out R.A.D and R.A.D 2 at Nitrado now.

It's because of the mod Project_MMO 3.67.6.

**Comment by Gunner76th** [comment]
Project_MMO-1.16.5-3.67.6 is the version you should be using and only with Java 8 64 bit. https://adoptium.net/temurin/releases/?version=8&os=windows&arch=x64&package=jre

If you have multiple versions of Java installed on your machine, then typically the highest version will be the one used. You either need to uninstall other versions or use Absolute Pathing in the launchserver.bat/launchserver.sh file so that the proper version of java is used to launch your server. If you are getting this same exact crash on your own PC then it is because you have multiple versions of java installed.

**Comment by hightimes76** [comment]
That makes no sense I can choose with which Java the server starts ^^ 

but it seems to be fixed after 5 restarts the Server was able to load the Mod
