### ISSUE TITLE
[Bug]: Heating Unit quest 

### ISSUE THREAD

**Issue by Gunner76th** [dr3ams/Roguelike-Adventures-and-Dungeons-2#383]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.11

### Describe your issue

As reported by a user in Discord, ( https://discord.com/channels/512339624627011586/1251370904538320957 ) there is a quest in the Culinary Expedition chapter that is impossible to complete. The quest in question is the Heating Unit quest. The Heating Unit has been removed from JEI, as has its crafting recipe. Additionally, that unit requires there to be a method of generating RF for it to even be used by the Oven. RAD 2 has no method of generating RF, making said unit pointless. 

As the item in question cannot be crafted, the quest cannot be completed. The quest in question should be removed ASAP as it is not relevant to RAD 2, nor can the item required for it be crafted or obtained. 

### Steps to reproduce the issue

Install the modpack on your launcher of choice, selecting version 1.11 (version confirmed to have this issue, may be present in previous versions)
Search JEI for @cooking and notice the Heating Unit does not exist
Open quest book and go to the Culinary Expedition chapter, and see the quest which cannot be completed. 

### Additional Information

![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/5566872/9cecee12-14a1-427e-bb47-8fb8d2366c9d)

![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/5566872/2b3e43ff-b29f-4f70-8198-247df7346936)

**Comment by RecyclingTiger** [comment]
Fixed in 1.12 as part of commit #384
