### ISSUE TITLE
[Bug]: Unexpected Error whilst starting instance RAD2

### ISSUE THREAD

**Issue by JJensen1234** [dr3ams/Roguelike-Adventures-and-Dungeons-2#386]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.11 [MC1.16.5]

### Describe your issue

Click "play" and it tries to load for ~1 second then kicks back to the home screen.
Errors: 
Unable to start pack... please see instance logs...
Unexpected error whilst starting instance.

### Steps to reproduce the issue

1. Go to curseforge. 
2. Click on play for the RAD2 1.11[MC1.16.5] version.
3. The errors populate.

### Additional Information

Here is the latest log, no log is created for the date the errors are occurring.
[2024-07-11-1.log.gz](https://github.com/user-attachments/files/16202959/2024-07-11-1.log.gz)

**Comment by JJensen1234** [comment]
Correction, it is on the FTB launcher.

**Comment by Gunner76th** [comment]
Please get the log file named latest. What you posted is an archive.

**Comment by JJensen1234** [comment]
Can you indicate where to find that in the folder structure?

**Comment by Gunner76th** [comment]
Exact same place you got the other file from, the logs folder.

**Comment by JJensen1234** [comment]
[latest.log](https://github.com/user-attachments/files/16203059/latest.log)

**Comment by Gunner76th** [comment]
According to that log file your game started successfully with no documented errors, you were able to log into the world,  and then leave the world.  

Go to the main instance folder, where you see the config, logs,  mods,  and other folders.  Scroll to the bottom and see if there are any files that start with hs err pid. If there is drag them here.

**Comment by JJensen1234** [comment]
That log file is from 7/11, the error is occurring 7/13 and no log file generated.
No file with hs err, there is an app.pid, but can't put that here.

**Comment by Gunner76th** [comment]
Give me a few to install FTB on my PC and check a few things.  There might be a log file for FTB itself that will contain the error details.

**Comment by JJensen1234** [comment]
Sounds good, as a note I installed curseforge and the mod pack worked.

**Comment by Gunner76th** [comment]
![image](https://github.com/user-attachments/assets/2eb0d234-6705-42cd-967b-f0cc61a07e17)

In the FTB app click on the Gear icon on the left side of the App. Then click on APP
From there, click on blue Logs button. 
Once the logs folder opens, upload the logs shown below

![image](https://github.com/user-attachments/assets/b74a0506-dee6-4aec-a3e3-b9309d1c12e8)
![image](https://github.com/user-attachments/assets/046a97cd-6a16-4c8f-95b3-1e59f5fb1829)



Also I suggest joining our Discord so that we can work on this in real time. https://discord.gg/r5N7PSgrDx

**Comment by JJensen1234** [comment]
I did that and the problem persists.

**Comment by Gunner76th** [comment]
you did what?
I didnt say to do anything to your launcher yet, other than to get the log files for me so I can see what error is being thrown on startup.

**Comment by JJensen1234** [comment]
My bad, read it wrong.
Just see the latest log I don't see the other 2
[latest.log](https://github.com/user-attachments/files/16203303/latest.log)
![image](https://github.com/user-attachments/assets/38e59fc9-a04a-4d53-8ce4-dcee60745172)

**Comment by Gunner76th** [comment]
You are in the wrong folder then. 
C:\Users\<user>\AppData\Local\.ftba\logs
You need to go to that folder and get the files I listed.

**Comment by Gunner76th** [comment]
might be at the very bottom of your list

**Comment by JJensen1234** [comment]
Is this the right one? 
![image](https://github.com/user-attachments/assets/2464a349-9cc2-4bbf-b3f5-cbc29f0754eb)

**Comment by Gunner76th** [comment]
Please get on discord so we can work on this in real time. Also scroll to the bottom of that folder and you should see the FTB log files

**Comment by JJensen1234** [comment]
Voice chat or just a text chat?
If text chat, which one?

**Comment by Gunner76th** [comment]
#tech-support Ping me once you are on there

**Comment by JJensen1234** [comment]
Just use curseforge.
