### ISSUE TITLE
[Question] Tool Editor

### ISSUE THREAD

**Issue by Dragatona** [dr3ams/Roguelike-Adventures-and-Dungeons-2#39]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Can you find "Tool Editor" in vanilla village houses? So far, I have seen none. If you cant, could it be added to the shop?

**Comment by firecrauter** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/43#issuecomment-1322717473

**Comment by VanyaBaou** [comment]
It's _supposed_ to spawn in vanilla villages, but Random Loot's datapack setup doesn't seem to actually work
So they are unobtainable, and most likely won't be added to shop
