### ISSUE TITLE
[Bug]: Restoring registry backup, this should never happen

### ISSUE THREAD

**Issue by nsfxz** [dr3ams/Roguelike-Adventures-and-Dungeons-2#396]
### General Info

- [ ] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.12

### Describe your issue

we have been playing for the last 2 days and suddenly one of your member cannot connect anymore with this issue listed below

### Additional Information

![Screenshot_54](https://github.com/user-attachments/assets/3ea3ede6-b762-4a1e-ab2a-34336ff20680)
![image (27)](https://github.com/user-attachments/assets/90be8407-bda2-4d90-8de5-af96a3ce9e85)

**Comment by Gunner76th** [comment]
At present we do not have enough information to be able to investigate this issue. 

We would need the logs from the server (file is named latest.log and debug.log) as well as any crash reports associated with this issue. We also need to know what the player was doing prior to this happening. Please attach the files directly, do not use pastebin like sites.

**Comment by nsfxz** [comment]
We only added simple voice chat mod thats all

The player having an issue reinstalled their modpack and it fixed the issue so not sure what caused this
