### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by period5663** [dr3ams/Roguelike-Adventures-and-Dungeons-2#398]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

RAD2 - 1.12 [MC1.16.5] - (Release) - (current)

### Describe your issue

Game will crash when a legendary ring bauble from Magical Jewelery mod is equipped in the ring slot on players baubles.

Continues crashing after world finishes loading on subsequent attempts to load world.

### Steps to reproduce the issue

1. Obtain a ring bauble from JEI search or the creative menu.
2. Search recipe by hovering over ring with mouse and get the "Legendary" ring by saving the item to JEI quick access, or smith the ring into a legendary ring with the smithing table.
3. Equip the ring bauble in the ring slot. This should freeze and crash the game after a few seconds. The world is now softlocked and cannot be loaded into again.

https://github.com/user-attachments/assets/70eb3562-e2f1-4a08-8ba3-6e20b8cbad50

### Additional Information

[crash-2024-12-23_02.56.44-server.txt](https://github.com/user-attachments/files/18222499/crash-2024-12-23_02.56.44-server.txt)
[latest.log](https://github.com/user-attachments/files/18222501/latest.log)

**Comment by RecyclingTiger** [comment]
The rings in the creative and jei menu should have red text that says: "This item have no effects or attributes attached to it, and therefore does nothing! This item can't be upgraded!"

As the text says, they cannot be upgraded and trying to smith it normally does nothing.
Using creative or cheats to bypass this should never happen in regular survival.

Rings obtained in survival have extra effects attached to them that make them upgradeable and not crash.
