### ISSUE TITLE
[Bug]: quests being 100% done but unable to claim rewards

### ISSUE THREAD

**Issue by infinityblade21** [dr3ams/Roguelike-Adventures-and-Dungeons-2#40]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge/ftb

### Modpack version

RAD2-1.16.5-0.6a

### Describe your issue

so as i was doing quests in the blue skies questline they wouldnt register as finished even though they say they are a 100% done and after i updated it fixed the problem with the we need to go deeper quest but not the everbright and everdawn quest

### Steps to reproduce the issue

sorry i dont even know how to reproduce it since i had just been playing and it happened in the last version and i updated and it didnt really fix the two quests

### Additional Information

![image](https://user-images.githubusercontent.com/76133169/198848960-b5515ea7-93e9-4019-a7a7-81a3b98138ce.png)

**Comment by dr3ams** [comment]
fixed in 0.8
