### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Wonkiero41** [dr3ams/Roguelike-Adventures-and-Dungeons-2#42]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

tlauncher

### Modpack version

0.6a

### Describe your issue

me and 2 of my friends were trying to play the modpack in multiplayer but as soon as we join the server he tell us "connection closed - mismatched mod channel list.

### Steps to reproduce the issue

 ![immagine_2022-10-30_175946005](https://user-images.githubusercontent.com/117032194/198891295-ad771f76-7298-4314-8bbf-b284cbc1b88a.png)

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9896350/latest.log)

**Comment by dr3ams** [comment]
Client and server have different mods. You either added/deleted something in mods or connecting with wrong client version.
