### ISSUE TITLE
The game crash in singleplayer for nothing

### ISSUE THREAD

**Issue by MineTL200** [dr3ams/Roguelike-Adventures-and-Dungeons-2#44]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.6a

### Describe your issue

When I playing on my singleplayer world after a moment my game crash.

### Steps to reproduce the issue

1. Play a singleplayer world

### Additional Information

I don't understand why it's crashing I don't have big redstone machine or other thing.

**Comment by MineTL200** [comment]
[crash-2022-11-01_10.17.09-client.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9908530/crash-2022-11-01_10.17.09-client.txt)

**Comment by DoctorMage** [comment]
You need to find hte mod geckolib and replace teh version used or just dont use any weapons from mowzies mobs
https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3989820

**Comment by MineTL200** [comment]
Okay thanks, If you want my game crash by the pathfinding mob of mobwies mod

**Comment by MineTL200** [comment]
Now It's Ice and Fire Mod

**Comment by MineTL200** [comment]
The game crashes a lot of times for no reason

**Comment by MineTL200** [comment]
My game crash 14 times !!

**Comment by DoctorMage** [comment]
Send The crash report please

**Comment by dr3ams** [comment]
Yeah, send 14 crash reports please
