### ISSUE TITLE
[Bug]: Game crashes on world join

### ISSUE THREAD

**Issue by UnknownTMx** [dr3ams/Roguelike-Adventures-and-Dungeons-2#45]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.6

### Describe your issue

After a 3-4 hours of playing the modpack i couldn't really do anything as the game wouldnt even load me into my world, at best i could put afew items in a chest or run around a bit before the game crashes.

### Steps to reproduce the issue

1. Start game 
2. Join world
3. Game freezes when the world loads in
4., I can avoid crashing instantly if i let the world slowly load by constantly going in the menu(esc) and back in the game though it freezes after a less than a minute after that and crashes.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/9910295/latest.log)

**Comment by dr3ams** [comment]
Log provided is from original **Roguelike Adventures and Dungeons**. You either need to post it [there](https://github.com/SamaraIsnt/Roguelike-Adventures-and-Dungeons/issues) or provide logs from RAD 2
