### ISSUE TITLE
[Bug]: Blaze spawner (and some other spawners) not spawning any mobs

### ISSUE THREAD

**Issue by SenseiArcher** [dr3ams/Roguelike-Adventures-and-Dungeons-2#46]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.6a

### Describe your issue

So I recently started the modpack, went in the nether, found a blaze spawner but it isn't spawning anything. I tried blocking light sources, turning to peaceful and back to normal (i thought it was a mob cap problem).

### Steps to reproduce the issue

I tried searching on youtube if it happened to anyone else but didn't find anything so i don't know if it's reproduceable

### Additional Information

screenshot of the spawner

![Screenshot (2)](https://user-images.githubusercontent.com/90576171/199324912-b2a57e13-d805-4695-bf9c-4606c119aa1c.png)

**Comment by DoctorMage** [comment]
Known issue due to player dying mob spawners have issues spawning mobs
