### ISSUE TITLE
[Bug]: Armor breaking in one hit

### ISSUE THREAD

**Issue by SonicNico** [dr3ams/Roguelike-Adventures-and-Dungeons-2#47]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Cursforge

### Modpack version

0.6a

### Describe your issue

I've been playing the modpack for about a week now, and suddenly my armor started breaking in one hit despite it being on full durability. It happened to two of my friends ancient gear, as well as my own, and it also happened to my random loot mod armor that had everlasting on it, meaning it wasn't supposed to be able to take durability damage, let alone break. Is there some mechanic that I'm not aware of, or is this just a bug?

### Steps to reproduce the issue

I don't know how to reproduce it consistently, but it seemed to happen occasionally when I would get hit by something. One second my armor would be at 100% durability, the next I hear a breaking sound and one of my pieces of armor is gone.

### Additional Information

It's been happening in multiplayer, but I don't know if it happens in single player due to how long we've been on this world, and it's only started recently.[https://pastebin.com/YrRk1Rzz](url)

**Comment by SonicNico** [comment]
Just happened again. Stepped outside, got shot by a skeleton once, and my helmet instantly broke.

**Comment by CsBSkEpTiC** [comment]
This is also happening to me in .8 as of now, I have a clip of it happening as well showing armor durability before and after and all what happened within the time frame. It's happened to me quite a few times and its made me stuck at progression because every time I finally get my chestplate helmet or leggings to continue playing it randomly just breaks. and I'm not sure if its from damage because I lagged for a few seconds and afterwards it just broke from nothing while opening a chest. I was on LAN when this happened and I believe I was on the other times as well.

**Comment by dr3ams** [comment]
Streaker's Will from Unique Enchantments - Battle  on mob is causing this

**Comment by SonicNico** [comment]
> Streaker's Will from Unique Enchantments - Battle on mob is causing this

I thought that could possibly be the case, but I couldn't think of any way for me to test it.

**Comment by dr3ams** [comment]
No problems! Mod dev is aware about this issue and trying to fix it. This more of a note or reminder :)

**Comment by SonicNico** [comment]
> No problems! Mod dev is aware about this issue and trying to fix it. This more of a note or reminder :)

Awesome!

**Comment by MemedHams** [comment]
Experienced this as well- can be incredibly brutal in late game. Considering we have a mod where you're intended to level up specific pieces of armor over multiple sessions of play, the results can be really disheartening

**Comment by DoctorMage** [comment]
fixed in 0.9
