### ISSUE TITLE
[Bug]: shop bug

### ISSUE THREAD

**Issue by SILVA123451e** [dr3ams/Roguelike-Adventures-and-Dungeons-2#59]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATlauncher

### Modpack version

RAD2 0.7

### Describe your issue

A bug happened!
when ever i point at the shop the game crash not even clicking or after using it just pointing make the game crash and i cant open the shop via another keybind it also crash the game.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10049623/latest.log)

**Comment by DoctorMage** [comment]
Can you confirm if the server was in online mode or offline mode?

**Comment by SILVA123451e** [comment]
Offline mode
