### ISSUE TITLE
Cannot Eat Mushroom Stew

### ISSUE THREAD

**Issue by RecyclingTiger** [dr3ams/Roguelike-Adventures-and-Dungeons-2#6]
**Describe the bug**
Vanilla Mushroom Stew cannot be consumed.

**To Reproduce**
1. Make Vanilla Mushroom Stew using modded mushrooms or the farmer's delight stove. **DO NOT MAKE MUSHROOM SOUP, which is a similar item from the Healing Soup mod**
2. Try to eat the stew
3. The player is stuck in the eating animation as if it was lagging, but they can eat other foods just fine.

**Expected behavior**
The player would consume the stew and get the comfort effect from farmer's delight

**Comment by TheFlame52** [comment]
Mushroom stew can be eaten just fine by an auto-feeding backpack.
