### ISSUE TITLE
[Suggestion]: Waystones cannot be placed

### ISSUE THREAD

**Issue by sighmonn** [dr3ams/Roguelike-Adventures-and-Dungeons-2#61]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Hey all, having a blast with the pack and I appreciate all the hard work you do. I noticed I couldn't place Waystones down after buying one from the store, it seems in the "waystones-server.toml" config it's set to creative only. Just wanted to give you a heads up and anyone who is having the same issue. 

The specific line in the config is 35-37:

#These options define restrictions when managing waystones.
	[server.restrictions]
		#If enabled, only creative players can place, edit or break waystones. This does NOT disable the crafting recipe.
		restrictToCreative = true

**Comment by diogoalexsmachado** [comment]
Hey, this was fixed in version 0.8, you can update and you're good to go :)

**Comment by VanyaBaou** [comment]
Fixed in version 0.8 https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/commit/f14822cac578e418ec4e3a5be53dc35bbf474528
