### ISSUE TITLE
[Bug]: Reinforced enchantment stopping from performing full damage attacks

### ISSUE THREAD

**Issue by diogoalexsmachado** [dr3ams/Roguelike-Adventures-and-Dungeons-2#62]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am using the latest version of the modpack
- [ ] I am crashing and can provide my crash report(s)

### Your launcher

GDLauncher

### Modpack version

0.8

### Describe your issue

Once I have any item with the enchantment "Reinforced" the weapon is lowered and I cannot make a full damage attack

### Steps to reproduce the issue

1. Equip any item with Reinforced
2. Try to attack any entity

### Additional Information

![image](https://user-images.githubusercontent.com/16367903/202971813-4ce98a92-0d30-47b5-a717-2561a7c5ed3c.png)

**Comment by VanyaBaou** [comment]
Works fine in a test instance (only UE Base + Utils) with Level 10 Reinforced on all equipment
Should be related to some other mod

**Comment by DoctorMage** [comment]
fixed in 0.9
