### ISSUE TITLE
[Bug]:  server crashes whenever someone goes around Cockatrice from the iceandfire MOD

### ISSUE THREAD

**Issue by johnall203** [dr3ams/Roguelike-Adventures-and-Dungeons-2#63]
### General Info

- [x] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

0.8

### Describe your issue

When exploring the server in survival -easy mode the server crashes when players get near Cockatrice from the ice and fire MOD. 

### Steps to reproduce the issue

explore and find Cockatrice.

### Additional Information

[crash-2022-11-23_13.39.24-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10078476/crash-2022-11-23_13.39.24-server.txt)
[crash-2022-11-22_21.49.49-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10078477/crash-2022-11-22_21.49.49-server.txt)

**Comment by DoctorMage** [comment]
Update to 0.85 cockatrices are disabled
or manually disable them yourself
