### ISSUE TITLE
[Bug]: Random Loot Mod and FTB Ultimine conflict causing items not to drop and vanish

### ISSUE THREAD

**Issue by CsBSkEpTiC** [dr3ams/Roguelike-Adventures-and-Dungeons-2#65]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.8

### Describe your issue

Noticed items no longer dropped from block being broke as well as any item in your inventory dropped while in this glitch (items dropped would just vanish). I tested it in a custom pack with just Random Loot Mod and items dropped after like normal, however when FTB Ultimine was added, Items lo longer dropped in the world. East to replicate, happens every time. Current temporary fix, exit out of the modpack and relaunch the pack. Have not tested with the Axe if ultimine allows felling of trees and if so, does it also replicate this issue is unknown. also unknown if armor breaking will cause this as well as swords. only known tool causing this is Pickaxe.

### Steps to reproduce the issue

1.) Get a Random Loot Mod pickaxe 2.) Break the pickaxe while using FTB Ultimine's Vein Mine 3.) drop any item you want to see vanish or break any block, nothing drops.

### Additional Information

No crashes happen for this bug, a simple and easy to replicate issue with conflicting mods

**Comment by puppydemon20** [comment]
I was able to replicate this bug in my mutliplayer server running the entirety of RAD2. One of my friends was chopping down willows like a maniac and suddenly items we dropped would vanish completely. I can't say for certain that the items were despawning or deleting, but they definitely aren't where I dropped them. Attempting to avoid this issue is somewhat easy at least.

**Comment by dr3ams** [comment]
For now **temporary** fix would be limiting ftb ultimine's work when the tool reaches certain durability. I'll set it to 20.

    # This will stop mining if tool reaches X durability. It's possible it won't work with special tool types. 
    # Default: 0
    # Range: 0 ~ 100
    prevent_tool_break: 20

in configs/ftbultimine.snbt
