### ISSUE TITLE
[Bug]: Gameplay is filled with stutter.

### ISSUE THREAD

**Issue by ItsAymn** [dr3ams/Roguelike-Adventures-and-Dungeons-2#66]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.85

### Describe your issue

It's been happening since 0.6a. The game and everything loads up fine till I enter a world, then it is almost unplayable as it keeps freezing(but not being labelled as not responding by task manager) and become playable again, this repeats almost every second, output log says **Can't keep up! Is the server overloaded? Running 15760ms or 315 ticks behind**.
My system (Laptop-Lenovo ThinkPad E15 Gen2) specs are:
CPU: AMD Ryzen 5 4500U with Radeon Graphics
RAM: 24.0GB at 3200MHz
Disk(PCIe SSD): Toshiba BG4 KBG40ZNT256G 256GB

### Steps to reproduce the issue

1. Start the game as you normally do; Open Curseforge, Select the modpack, Click PLAY on the Minecraft Launcher when it comes up(you can have the output log launch as well if you like)
2. Once RAD2 launches; Singleplayer, Join a world(create new world or join, issue still persists)
3. Once you load in you'll see it more or less right away. (I did not chan.ge FPS settings or Render Distances so its not due to that)

### Additional Information

latest.log below
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10091717/latest.log)

**Comment by dr3ams** [comment]
Can you please add the following mod to the mods folder and see if it will make any differences? 
https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks/files/3750103

**Comment by ItsAymn** [comment]
Doesn't seem to have fixed the 'stutter' issue, however, it does load a lot faster now. New logs below:
[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10095192/latest.log)

**Comment by DoctorMage** [comment]
PC Specifcation? 
Ram
Cpu (model name)

**Comment by ItsAymn** [comment]
My system (Laptop-Lenovo ThinkPad E15 Gen2) specs are:
CPU: AMD Ryzen 5 4500U with Radeon Graphics
RAM: 24.0GB at 3200MHz
Disk(PCIe SSD): Toshiba BG4 KBG40ZNT256G 256GB
Runs most modpacks just fine(RLcraft, AOF5, RAD1, etc)

**Comment by DoctorMage** [comment]
How much ram allocated to the modpack

**Comment by ItsAymn** [comment]
No clue, to be honest, I haven't messed around with those settings(mostly because I don't know how to). So probably the default allocation forge has (if that's a thing).

**Comment by DoctorMage** [comment]
8gb
![image](https://user-images.githubusercontent.com/85318453/204154491-5b899b2e-91d0-4afd-8cfb-bad1f27c15bf.png)

**Comment by ItsAymn** [comment]
The problem was still there with 8GB, 9GB seems to be what it likes.
Works fine now.
Thanks for the help

**Comment by DoctorMage** [comment]
Sounds like garbage collection next tiem it occurs

Screen record f3 menu active
https://www.pcmag.com/how-to/how-to-capture-video-clips-in-windows-10

**Comment by ItsAymn** [comment]
garbage collection?

**Comment by DoctorMage** [comment]
Java term

Simple explanation of the issue your having is the ram amount you have to the modpack is not enough
As by the time some ram was freed up it was already being used again
This is shown by consistent freezes on your end after playing for a while

**Comment by ItsAymn** [comment]
Oh, I get it now. It's fine now by the way. So should I close this issue?
