### ISSUE TITLE
[Suggestion]: Add a mod or function that allows forced chunk loading for simple storage network

### ISSUE THREAD

**Issue by excwhyyy** [dr3ams/Roguelike-Adventures-and-Dungeons-2#67]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

It would be great for there to be a function or mod added that allows forced chunk loading so that I can access my simple storage network anywhere in the world, I can't seem to find any in the current version of the modpack. I would suggest FTB Chunks but that would probably conflict with the already existing map/mini-map mod. Just a thought.

**Comment by VanyaBaou** [comment]
Would recommend setting up Simple Storage Network near spawn chunks, as they are always loaded

Currently no chunk loaders are in the pack, and might not be as they cause lag on servers, and there isn't much need for them besides SSN.

**Comment by Chifilly** [comment]
> and might not be as they cause lag on servers

Surely the server could just disable them, or limit their usage with server-side mods, whereas it would be super helpful for solo worlds or small servers with trusted friends.

Another option would be to add a chunk-loading mod ourselves, however the joy of using a pre-made modpack is the vetting process that's been done already so people know that mods work together - at least mostly.

If anyone knows of a mod that would work well, I'd love to know.

**Comment by VanyaBaou** [comment]
If you are single-player or playing only with a friend group in a server, just use the [forceload](https://minecraft.fandom.com/wiki/Commands/forceload) command
