### ISSUE TITLE
How can i play w/ optifine? When i try the game not even open

### ISSUE THREAD

**Issue by JRCCampos1** [dr3ams/Roguelike-Adventures-and-Dungeons-2#68]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

How can i play w/ optifine? When i try the game not even open

**Comment by DoctorMage** [comment]
Check the pinned modpack already has magensium/rubidium extra as well as oculus so no need for optifine

**Comment by DoctorMage** [comment]
Pack has built-in support for shaders. Just drop your shaders in **shaderpacks** folder and select them in video setting.
If you still need Optifine:
1. Go to mods folder
2. delete the following mods 
- oculus-1.2.6.jar
- magnesium_extras-mc1.16.5_v1.4.0.jar-*.jar
- rubidium-0.2.10.jar
