### ISSUE TITLE
[Bug]: Atum portals failing to open

### ISSUE THREAD

**Issue by MemedHams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#69]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.85

### Describe your issue

The Atum portal, which relies on building a 5x5 "tomb" structure and then throwing a scarab inside, does not appear to be working.
I've made repeated attempts in different locations, with both sandstone cobblestone and normal sandstone. 

Of lesser note, the textures for these items are exactly the same currently, which can be confusing.

### Steps to reproduce the issue

1: Build the Atum Portal according to specifications available online
2: Craft a scarab and throw it inside.
3: Portal fails to open.

### Additional Information

![2022-11-30_03 06 45](https://user-images.githubusercontent.com/45698967/204741971-2bcfcf64-eedc-4e08-a470-1a5a62e582a8.png)

**Comment by DoctorMage** [comment]
screenshot the entire portal

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/205521202-529e17d6-8888-4f73-af2e-de5bf8fec91e.png)

**Comment by MemedHams** [comment]
A single block of the lower frame of my portal was made of the visually identical "cobbled sandstone", disregard issue
