### ISSUE TITLE
[Bug]: Unusable Enchantments

### ISSUE THREAD

**Issue by MemedHams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#70]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.85

### Describe your issue

Some of the modpack's enchantment books appear to be unusable, displaying no icon or acceptable enchant items in their tooltip and being unable to enchant any item in the anvil.
Ones I've seen so far:
-Mirror
-Illager's Bane
-Potion Barrier
-Lightning Focus
-Chain Reaction
-Rush
-Lucky Explorer
-Swiftfooted
-Beehive
-Speed Aura
-Radiance Shot
-Arrow Hoarder
-Cooldown Shot
-Opulent Shield
-Harpoon Shot
-Fire Trail
-Gravity
-Rampaging
-Exploding
-Thundering
-Soul Siphon
-Weakening
-Life Steal Aura

Most of these seem to come from the "Dungeon Gear" mod, not sure what's up there.

### Steps to reproduce the issue

1: Find one of the mentioned enchant book
2: Try to enchant something
3: Fail

### Additional Information

![2022-12-01_05 14 35](https://user-images.githubusercontent.com/45698967/205026862-0c72aae3-aedd-4e18-bbdc-80781e5d03fc.png)

**Comment by DoctorMage** [comment]
Dungeon gears enchantments can only can be applied to dungeon gears equipment
