### ISSUE TITLE
[Suggestion]: Boost Endurance Aquisition

### ISSUE THREAD

**Issue by MemedHams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#71]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I think the scaling to progression metric on most of the skills is fairly well-set, but endurance tends to massively lag behind armor progression, especially when it reaches higher levels

Looking to speed it up, I ended up designing a water-flow based idle track that constantly damaged me to one heart then healed me to full to try and compensate-

I ultimately left it on for few hours, but when I'd gotten back I only got from 30 to 37. 

Realistically this isn't what players are intended to do, and even with it the scaling is pretty tedious, so you can see how actually getting endurance from normal damage can be even more of a slog.

I'd recommend punching armor sets down by 5 to ten levels in terms of endurance requirement, or potentially improve the speed at which you gain it.

**Comment by VanyaBaou** [comment]
That example doesn't really work when PMMO decreases XP gain when you're AFK.

Rate _could_ be upped slightly, as multiple people have complained about it and resort to things like standing in lava with Muscle Milk

Modifiers also negate need for higher armor stats on equipment though, so armor only needs high durability and special bonuses
