### ISSUE TITLE
[Suggestion]: Elite bosses?

### ISSUE THREAD

**Issue by MemedHams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#73]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Bosses seem to frequently spawn as "elite" or "legendary" versions, with considerably boosted health, speed, and perks. 
My first spawned wither was Elite with lively- something that made it near-impossible to kill. It also gained the speed to pursue entities at a rate faster than running, which was a bit unfortunate. 

Wasn't entirely sure if this wasn't intentional, so I didn't submit it as a bug report. That being said, it doesn't feel like fully intended behavior.

**Comment by DoctorMage** [comment]
No way of controlliong what champion mobs spawns tier is randomized

**Comment by VanyaBaou** [comment]
We can control the minTier and maxTier for specific entities, and a list of whitelisted/blacklisted affixes 
defaultconfigs/champions-entities.toml

> [[entities]]
	entity = "minecraft:creeper"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"

**Comment by DoctorMage** [comment]
> We can control the minTier and maxTier for specific entities, and a list of whitelisted/blacklisted affixes defaultconfigs/champions-entities.toml
> 
> > [[entities]]
> > entity = "minecraft:creeper"
> > minTier = 0
> > maxTier = 0
> > presetAffixes = []
> > affixList = []
> > affixPermission = "BLACKLIST"

Mean more of a case the chance of each rarity spawning did check the config and nothing to control which tier would spawn aka 50% for uncommon 1% for legendary something like that

**Comment by DoctorMage** [comment]
I stand corrected can lock them behind game stages https://github.com/TheIllusiveC4/Champions/wiki/Game-Stages-Integration

**Comment by DoctorMage** [comment]
locked their spawning behind wither or ender dragon kill as of 0.96a
