### ISSUE TITLE
[Bug/Crash]: Server keeps crashing on startup 

### ISSUE THREAD

**Issue by kamilikot2** [dr3ams/Roguelike-Adventures-and-Dungeons-2#74]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.85

### Describe your issue

Hi, so today when I wanted to create server for my friends I found this wierd "crash"? that happens every time I try to start server
ps. Sorry for my english 

### Steps to reproduce the issue

1. Launch server and it immediately crashes

### Additional Information

[log.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10146753/log.txt)

**Comment by DoctorMage** [comment]
https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58#issuecomment-1328237062
