### ISSUE TITLE
[Bug]: I can't download the game in curseforge

### ISSUE THREAD

**Issue by IceHybrid961** [dr3ams/Roguelike-Adventures-and-Dungeons-2#76]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.16.5

### Describe your issue

I can't even download the game as I keep getting this message no java executable found cannot execute post-installation task and I am not sure what I am doing wrong I think all the apps are updated but I am not sure why it is not installing 

### Additional Information

I have nothing to show yet

**Comment by DoctorMage** [comment]
did you manually change the java version curseforge uses

**Comment by DoctorMage** [comment]
do you have normal minecraft installed
does creating a vanilla 1.16.5 instance work?

**Comment by IceHybrid961** [comment]
I have not launched normal minecraft in awhile do you think that could be the issue I am normally running minecraft through technic launcher or cursedforge

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/205904278-4a2bbe6b-adb1-4949-b733-0e75e3065a5e.png)
![image](https://user-images.githubusercontent.com/85318453/205904310-fa07aedc-0507-4474-b6ee-8f327fb5a98a.png)
see if this works

**Comment by DoctorMage** [comment]
try vanilla
then forge

**Comment by DoctorMage** [comment]
![image](https://user-images.githubusercontent.com/85318453/205904380-490ba8ed-df7c-40e2-8cca-8f059035eabb.png)
otherwise try this

**Comment by DoctorMage** [comment]
Any updates

**Comment by IceHybrid961** [comment]
Ok here is a update I opened the java minecraft normally and that fixed it because I guess it was outdated and I never got the updates which is why it didn't work so it does work now
