### ISSUE TITLE
[Bug]: Multiplayer Game Crash: When using any scroll that gives a buff to a fellow player, the game will crash, and the world is unplayable past there.

### ISSUE THREAD

**Issue by obigowens** [dr3ams/Roguelike-Adventures-and-Dungeons-2#78]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.85

### Describe your issue

When using a scroll that provided resistance to my teammate, the scroll effect applied to both of us and then our games both crashed. the server we were on reported 0 errors in the console and when we tried to join back the game would crash again. we quickly figured out that if either 1 of us is in the server than we don't crash, but the instant another player joins, the game will crash to desktop. 
This crash has not generated a crash log, only a latest.log file. 
The attached file is the only log created by the crash, which happened 6 different times while testing.
EDIT: When 1 person loads back in, they also cannot access the quest book as it says "Quests Locked!" not sure if this is relevant but its definitely new.

### Steps to reproduce the issue

Use the resistance scroll that allows you to hold right click on a teammate and give them the buff. after using, wait around 30s or less, and then your game will crash to desktop. after that 1 player may enter the server without any issue, but as soon as the other player joins, both games will crash. the server will also not report any issues from my testing so far.

### Additional Information

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10172927/latest.log)

**Comment by DoctorMage** [comment]
Send the entire log please not just a snippet 
from the client and server please

**Comment by DoctorMage** [comment]
also remove optifine
it can cause issues with mods dont care if it never happened before remove it anyway
