### ISSUE TITLE
[Bug]: Game crashes due to Ars Arsenal armor

### ISSUE THREAD

**Issue by Chifilly** [dr3ams/Roguelike-Adventures-and-Dungeons-2#79]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

GDL

### Modpack version

0.85

### Describe your issue

I was doing some exploring, then the game crashed with `AL lib: (EE) alc_cleanup: 1 device not closed`. Looking at the crash log it seems to be caused by `com.minttea.minecraft.arsarsenal.common.armor.AirRobes` and shaders. If shaders are enabled before loading, it crashes during loading. If I disable shaders I can load in, but enabling shaders immediately crashes the game.

### Steps to reproduce the issue

1. Load a world
2. Have whatever `com.minttea.minecraft.arsarsenal.common.armor.AirRobes` is for loaded in the area (not too deep into the mod pack yet, so don't know what needs to be spawned for the above to exist)
3. Enable shaders
4. Game crashes

### Additional Information

- [crash-2022-12-11_04-37-54-client-txt](https://gist.github.com/Chifilly/d008887bee5c92b28e15470aee36aa21#file-crash-2022-12-11_04-37-54-client-txt)
- [latest.log](https://gist.github.com/Chifilly/d008887bee5c92b28e15470aee36aa21#file-latest-log)
- I'm using BSL 8.1.02.3 and have also tested Complementary 4.0.1

I don't 100% know whether this is a modpack issue that can be fixed with an updated mod or something, a mod issue that needs fixing to then be added to the modpack, or a shaders issue, but I thought this was the most appropriate place to post, and could be forwarded to the relevant place if needed.

**Comment by Chifilly** [comment]
Actually, just as I posted this I was going to load in without shaders to carry on playing, and now it's crashing with the same issue, so maybe shaders aren't the issue. I updated the latest.log file (I meant to upload it as a separate gist file, but I forgot to change the title of the file so it overwrote the old one, and there doesn't seem to be a revert changes option)

**Comment by VanyaBaou** [comment]
Known issue with Ars Arsenal, _they_ need to update the mod with newest geckolib version.
For now, removing it from applicable items in improved mobs will work, read [here](https://discord.com/channels/512339624627011586/987711713572974612/1050585649469730817).

**Comment by Chifilly** [comment]
Gotcha, thanks! Although that link takes me nowhere, probably because I'm not in the Discord server it's linked to? I just get a placeholder server view with `No text channels`

**Comment by VanyaBaou** [comment]
Yes it's a link to a message in our discord server, containing a replacement file and instructions on how

**Comment by DoctorMage** [comment]
Fixed in 0.9 well sort of just made mobs not be able to spawnn with that armour
