### ISSUE TITLE
Buddy Card display

### ISSUE THREAD

**Issue by Chewbiegum** [dr3ams/Roguelike-Adventures-and-Dungeons-2#8]
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: RoadRunner BlockEntityList: Adding the same BlockEntity object twice: {x:-535,y:64,ForgeCaps:{"improvedmobs:opened_flag":{HasBeenOpened:0b}},z:-757,Items:[],id:"buddycards:card_display",locked:0b,player:""}
Exit Code: -1

**Comment by dr3ams** [comment]
for reference https://github.com/MaxNeedsSnacks/roadrunner/issues/38

should be fixed in the next update
