### ISSUE TITLE
[Suggestion]: Add tags to silver pickaxe

### ISSUE THREAD

**Issue by gurns07** [dr3ams/Roguelike-Adventures-and-Dungeons-2#81]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

The Silver Pickaxe from Ice and Fire lacks tags. This is annoying, as it means it will auto-smelt in my backpack. Please add tags. 

Thanks in advance,
gurns

**Comment by DoctorMage** [comment]
Can you explain a bit more please?
so if you put it in your backpack with an autosmelt upgrade it will be put inside the furnace correct?

**Comment by VanyaBaou** [comment]
This is expected behavior
Non-wooden pickaxes are smeltable, so they will try to smelt if you do not set a filter
Set up a filter for the upgrade
