### ISSUE TITLE
[Bug]: Apotheosis Ticking block entity

### ISSUE THREAD

**Issue by Tr1ssys** [dr3ams/Roguelike-Adventures-and-Dungeons-2#82]
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.9

### Describe your issue

Server just crashing when i am playing, crash report says that Apotheosis mod tries to spawn boss? Not quite sure, attaching two crash-reports.

### Additional Information

https://pastebin.com/nkg68rN5 (latest.log)
https://pastebin.com/35W8nuDH (first crash)
https://pastebin.com/KSA22VPq (second crash)

**Comment by elsawim** [comment]
Wanted to second this. Exact same setup, issue, and crash report.

**Comment by aDerpling** [comment]
Seems like it's an issue with Apotheosis spawning boss mobs for sure. Changing the spawn chance for boss mobs to 0 in the Apotheosis config seems to make the crash no longer occur. (for anyone wondering, it's the "Surface Boss Chance" setting in the deadly.cfg file of the apotheosis config folder)

**Comment by DogsTongue** [comment]
Likely related to https://github.com/Shadows-of-Fire/Apotheosis/issues/732

**Comment by wasdspace** [comment]
Probably related to the recent(1 month ago) introduction of Apotheosis's compatibility in Dungeons Suites. At least this happened to me after that.

**Comment by ILove07Gold** [comment]
> Seems like it's an issue with Apotheosis spawning boss mobs for sure. Changing the spawn chance for boss mobs to 0 in the Apotheosis config seems to make the crash no longer occur. (for anyone wondering, it's the "Surface Boss Chance" setting in the deadly.cfg file of the apotheosis config folder)

thank you, this fixed the issue for me.

**Comment by TurboSlayer** [comment]
My friend really likes the bosses - is there a different workaround?

**Comment by wasdspace** [comment]
That seems to be the problem: https://github.com/Thelnfamous1/Dungeons-Gear/issues/177
Seems to need a fix data pack before its next update.

**Comment by TurboSlayer** [comment]
Modpack version 0.95a seems to contain a newer version of [Dungeons-Gear](https://github.com/Thelnfamous1/Dungeons-Gear). If anyone can confirm that the issue is resolved that would be great.

**Comment by Kamisoi** [comment]
Running server on 0.95a; still receiving this [crash](https://cpaste.org/?937798f4bb7150aa#G3PSFQStraDhMPH4WmpUghtQKFQeaxEAXpW6B2JHAtRf)

**Comment by VanyaBaou** [comment]
Issue is confirmed to be Dungeons Gear Apotheosis compatibility (datapack)
Dev is aware of issue and has fixed it already, see [newest version](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear/files/4277051)
