### ISSUE TITLE
Prefab Advanced Farm is not craftable anymore[Bug]: 

### ISSUE THREAD

**Issue by sciarcan** [dr3ams/Roguelike-Adventures-and-Dungeons-2#83]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.9

### Describe your issue

Advanced farm from Prefab is not craftable anymore but it was in 0.85.
In the changelog that is not written

### Steps to reproduce the issue

Search for Advanced Farm in JEI, nothing shows up

### Additional Information

No screenshot needed

**Comment by VanyaBaou** [comment]
Not a bug, it's disabled.
