### ISSUE TITLE
[Bug]: cant use crafting table or furnace

### ISSUE THREAD

**Issue by holyburgers** [dr3ams/Roguelike-Adventures-and-Dungeons-2#84]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

0.9

### Describe your issue

A bug happened! for some reason i simply cannot use a crafting table or furnace.
i downloaded and tried out the mod pack today but sadly could not get very far since there is only so much you can do when limited to the 2x2 crafting grid in your inventory (right click works fine for everything else so far i can block and open doors + chests i found i could also interact with a blast furnace in a village even tho the normal furnace next to it wouldnt open) 
i tried making a new world just for the hell of it but didnt fix it
also tried normal crafting table and from 2 different special kinds from other wood

### Steps to reproduce the issue

well the reproduction steps are simple i just put a crafting table on the ground and right click it

### Additional Information

https://gist.github.com/holyburgers/7cab53bcce3451159883465540d39190

**Comment by DoctorMage** [comment]
Did you try reinstalling the modpack as no one else is reporting this issue
