### ISSUE TITLE
[Suggestion]: Crates rework

### ISSUE THREAD

**Issue by dr3ams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#88]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Mainly:
Crates:
- [x] relics crate, delete(or increase quantity of) crafting materials and decrease price
- [x] artefact crate (contains relics too)
- [x] dungeon gear crate (separate it to 3 probably - armor/weap/artifact)

Coins:
![image](https://user-images.githubusercontent.com/7347489/207319892-224b7c28-662b-451e-833e-8c9acf75be8f.png)

**Comment by VanyaBaou** [comment]
Don't believe there is a way to do submit multiple times at once for repeatable quests.
Might need to ask [Quest Additions](https://www.curseforge.com/minecraft/mc-mods/quests-additions) dev if it's possible to add something like this in their [discord](http://discord.gg/a74pzUw2Gw).

**Comment by dr3ams** [comment]
- divided Dungeons Gear Crate into 3 different crates: 
	- gear
	- weapons
	- artifacts

- added Dungeons Gear Crates(gear, weapons, artifacts) to the shop (money); 

- added Dungeons Gear Crates(gear, weapons, artifacts) to the quest shop(quest coins), you can choose exactly which item you want;

- created Relics Materials Crate and added to the shop(money), deleted Relics materials from Relics crate;

- added Relics materials crate to the quest shop(quest coins), you can choose exactly which item you want;

- reduced the prices in money shop for: Artifact Crate, Dungeons Gear crate(gear, weapons, artifacts), Relics crate. Items you get are random so that's fair.
