### ISSUE TITLE
Add Coins to goblin traders

### ISSUE THREAD

**Issue by dr3ams** [dr3ams/Roguelike-Adventures-and-Dungeons-2#9]
datapack

**Comment by VanyaBaou** [comment]
i second this, honestly need more trade options in goblin trader
most of them are junk besides the ore multiplying
money hoarding goblin sounds very fitting 👍

**Comment by dr3ams** [comment]
**Added:**
Copper coin (common)
Box (common)
Lockbox (common)
Iron coin (uncommon)
Gold coin (uncommon)
Randomite Ore
Basic Case
Golden Case
