### ISSUE TITLE
[Bug]: Sudden Death to Void (Ender Eyes)

### ISSUE THREAD

**Issue by VanyaBaou** [dr3ams/Roguelike-Adventures-and-Dungeons-2#91]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

0.9

### Describe your issue

Mobs wearing the Ender Eyes enchantment from Unique Enchantments, player dies to void
Reporting so people know it is the cause

Temporary fix is to disable Ender Eyes in **config\ue\ue.toml**

Dev (Xaikii) is aware of issue, knows the fix, and will try to release a hotfix tomorrow

### Steps to reproduce the issue

Find mob with Ender Eyes
Get Hit
Die to void

### Additional Information

boop

**Comment by DoctorMage** [comment]
fixed by resetting config

**Comment by VanyaBaou** [comment]
Temporary fix for players
change `affected_entities = ["minecraft:player"]` to `affected_entities = ["minecraft:enderman"]`
