### ISSUE TITLE
[Suggestion]: Replace FTB Ultimine with Ore Excavation

### ISSUE THREAD

**Issue by VanyaBaou** [dr3ams/Roguelike-Adventures-and-Dungeons-2#92]
### General Info

- [X] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

[Mod](https://www.curseforge.com/minecraft/mc-mods/ore-excavation)

What we lose:
- Veinmine working on harvesting crops (SIckles, and Scythes exist and will actually have a purpose now)
- Highlights on Shapeless vein-mining (not sure why, its the only one without highlights)

What we gain:
- Players can make custom shapes, up to 5x5
- A whitelist for blocks, that supports tags (tags:forge:ores, tags:forge:logs, etc.)

Issues:
- Highlights blacklisted stuff for some reason

**Comment by DoctorMage** [comment]
done in 1.2
