### ISSUE TITLE
Adjust Excavtation & Woodcutting Levels

### ISSUE THREAD

**Issue by DoctorMage** [dr3ams/Roguelike-Adventures-and-Dungeons-2#93]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

due to the lack of utility shovels have either merge the stat into mining or removing
same with woodcutting

**Comment by VanyaBaou** [comment]
"x" being Mining/Excavation/Woodcutting 
make new skill "Gathering", no functionality, simply a name for "cumulation xp in X", used for Requirements

make things that require X instead require Gathering
make things that give xp to X give Gathering xp as well
make things that boost xp X boost Gathering as well

change Quest awards for X to award Gathering as well

Gathering will have total value of all 3 skills
Specific bonuses from X will still function properly

Think this will work fine?

**Comment by DoctorMage** [comment]
yep sounds good 
main issue with the woodcutting adn excavating is their tools are rarely used unless you like building

**Comment by VanyaBaou** [comment]
implemented
