### ISSUE TITLE
[Suggestion]: Remove Healing Soup

### ISSUE THREAD

**Issue by VanyaBaou** [dr3ams/Roguelike-Adventures-and-Dungeons-2#95]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Mod is confusing, breaks recipes, and doesn't make much sense to include. 0 value.
Also apparently had issues with eating or something? Not sure on that part.

**Comment by dr3ams** [comment]
done for next update
