### ISSUE TITLE
[Bug]: shaders

### ISSUE THREAD

**Issue by GodLikeInfernal** [dr3ams/Roguelike-Adventures-and-Dungeons-2#96]
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

rad2-1.16.5-0.9

### Describe your issue

When shaders are enabled and loaded it causes you to be in full bright mode so everything is maximum brightness even in caves with no torches and extra setting true darkness enabled and set to pitch black.

### Steps to reproduce the issue

install shaders and enable them. I was using ComplementaryShaders_v4.0.1.

### Additional Information

Not crashing.

**Comment by VanyaBaou** [comment]
Known issue, disable the no nv flash mod.
