### ISSUE TITLE
[Suggestion]: Remove UnionLib

### ISSUE THREAD

**Issue by VanyaBaou** [dr3ams/Roguelike-Adventures-and-Dungeons-2#99]
### General Info

- [ ] I would like to propose new mod
- [ ] I would like to propose new quests
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Mod is leftover from (pre?) alpha.
No mods use this library.

**Comment by dr3ams** [comment]
removed
